In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as la
from scipy.integrate import quad

# Actividad 08: Algebra Lineal y Matrices

---
### Profesor: Juan Marcos Marín
### Nombre: David Alejandro Pérez
*Métodos computacionales 2024-II*

---

#1

Escriba una función que calcule el producto escalar y vectorial para dos vectores, compare sus resultados con `np.dot` y `np.cross`.

In [ ]:
def escalar(v, w):
  mul = []
  if len(v) == len(w):
   for i in range(len(v)):
    s = v[i]*w[i]
    mul.append(s)
  return sum(mul)

v = np.array([2,4,3])
w = np.array([9,3,5])

def cross(v, w):
  if len(v) == 2:
    a, b = v[0], v[1]
    x, y = w[0], w[1]
    return [0, 0, a*y - b*x]

  elif len(v) == 3:
    a, b, c = v[0], v[1], v[2]
    x, y, z = w[0], w[1], w[2]
    cross = [b*z - c*y, c*x - a*z, a*y - b*x]
    return cross



In [ ]:
escalar(v,w) == v@w

True

In [ ]:
cross(v,w) == np.cross(v,w)

array([ True,  True,  True])

#2

Crear una función llamada `mulmat()` donde a partir de dos matrices $A$ y $B$ encuentre su multplicación. También realiza una función que calcule la transpuesta y otra el determinante de una matriz $3\times 3$. Compare sus resultado con `@`, `np.dot`, `transpose` y `la.det`.

In [ ]:
def mulmat(A, B):

  if A.shape[1] == B.shape[0]:
    C = np.zeros((A.shape[0], B.shape[1]))
    for i in range(A.shape[0]):
      for j in range(B.shape[1]):
        s=0
        for k in range(B.shape[0]):
         s += A[i,k]*B[k,j]
        C[i,j] = s

    return C
  else: return ValueError("Las dimensiones de las matrices no son validas pa llevar a cabo AB")

def transpose(A):
  B = np.zeros((A.shape[1], A.shape[0]))
  for i in range(A.shape[0]):
    for j in range(A.shape[1]):
      B[j,i] = A[i,j]
  return B

def det3(A):
  if A.shape[0] == 3 and A.shape[1] == 3:
    return A[0,0]*A[1,1]*A[2,2] + A[0,1]*A[1,2]*A[2,0] + A[0,2]*A[1,0]*A[2,1] - A[0,2]*A[1,1]*A[2,0] - A[0,1]*A[1,0]*A[2,2] - A[0,0]*A[1,2]*A[2,1]
  else: return ValueError("La matriz no es de 3x3")


In [ ]:
A = np.random.randint(0,8, (3,3))
B = np.random.randint(3,15, (3,3))

A,B

(array([[4, 2, 3],
        [2, 2, 1],
        [5, 6, 4]]),
 array([[ 9,  9, 13],
        [ 6,  4,  9],
        [ 6, 14, 14]]))

In [ ]:
mulmat(A,B) == A@B

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [ ]:
mulmat(A,B) == np.dot(A,B)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [ ]:
transpose(A) == A.T

False

In [ ]:
np.isclose(det3(A), np.linalg.det(A))

True

#3
Escriba tres matrices aleatorias $A$, $B$ y $C$ de $3\times 3$, y demuestre las siguientes relaciones:

In [ ]:
# estas seran las matrices para comprobar
A = np.random.randint(0,1000, (3,3))
B = np.random.randint(0,1000, (3,3))
C = np.random.randint(0,1000, (3,3))
c = np.random.randint(1,10)

print(f""" A es :
{A}
      """)

print(f""" B es :
{B}
      """)

print(f""" C es :
{C}
      """)

print(f"""El escalar (c) es : {c}
      """)

 A es :
[[ 89 908 272]
 [502 665 338]
 [725 781 966]]
      
 B es :
[[563 880 891]
 [142 387 766]
 [729 363 491]]
      
 C es :
[[278 987 946]
 [632 506 876]
 [455 138 560]]
      
El escalar (c) es : 3
      


- $ \mathbf{A}\mathbf{B} \neq \mathbf{B}\mathbf{A} $, en general.

In [ ]:
mulmat(A, B) == mulmat(B, A)

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

- $ (\mathbf{A}\mathbf{B})\mathbf{C} = \mathbf{A}(\mathbf{B}\mathbf{C}) $.

In [ ]:

mulmat(mulmat(A,B), C) == mulmat(A, mulmat(B,C))

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

- $ \mathbf{A}(\mathbf{B} + \mathbf{C}) = \mathbf{A}\mathbf{B} + \mathbf{A}\mathbf{C} $.

In [ ]:
mulmat(A, B+C) == mulmat(A,B) + mulmat(A,C)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

- $ (\mathbf{A} + \mathbf{B})\mathbf{C} = \mathbf{A}\mathbf{C} + \mathbf{B}\mathbf{C} $.

In [ ]:
mulmat(A+B,C) == mulmat(A,C) + mulmat(B,C)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

- $ (\mathbf{A}\mathbf{B})^\top = \mathbf{B}^\top \mathbf{A}^\top $.

In [ ]:
mulmat(A,B).T == mulmat(B.T, A.T)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

- $ \det(\mathbf{A}\mathbf{B}) = \det(\mathbf{A}) \det(\mathbf{B}) $.

In [ ]:
abs(np.linalg.det(mulmat(A,B)) - np.linalg.det(A)*np.linalg.det(B)) < 1e-11

False

- $ (\mathbf{A}^\top)^\top = \mathbf{A} $.

In [ ]:
(A.T).T == A

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

- $ (c\mathbf{A})^\top = c\mathbf{A}^\top $.

In [ ]:
(c*A).T == c*A.T

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

- $ (\mathbf{A} + \mathbf{B})^\top = \mathbf{A}^\top + \mathbf{B}^\top $.

In [ ]:
(A+B).T == A.T + B.T

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

#4

El **Teorema de Laplace** es un método para calcular el determinante de una matriz cuadrada, particularmente útil para matrices de orden mayor a 2. Este teorema se basa en la expansión del determinante por los elementos de una fila o una columna cualquiera.



$$
\det(A) = \sum_{j=1}^n (-1)^{1+j} a_{1j} M_{1j}
$$

donde:
- $a_{1j}$ es el elemento de la primera fila y columna $j$.
- $M_{1j}$ es el menor asociado al elemento $a_{1j}$, es decir, el determinante de la submatriz de $3 \times 3$ que se obtiene al eliminar la fila 1 y la columna $j$.
- $(-1)^{1+j}$ es el signo correspondiente al cofactor del elemento $a_{1j}$.

Podemos realizar una función recursiva para el cálculo del determinante, sabiendo que el valor del determinante de una matriz de orden uno es el único elemento de esa matriz, y el de una matriz de orden superior a uno es la suma de cada uno de los elementos de una fila o columna por los Adjuntos a ese elemento, como en la función recursiva se emplea la misma función definida el cálculo lo haremos por Menor complementario, un ejemplo desarrollado por la primera fila sería:

$$
   \det (A_{j,j}) =
   \left \{
   \begin{array}{llcl}
      si & j = 1 & \to & a_{1,1} \\
                                 \\
      si & j > 1 & \to & \displaystyle \sum_{k=1}^j \; (-1)^{(1+k)} \cdot a_{1,k} \cdot \det( \alpha_{1,k})
   \end{array}
   \right .
$$

Realice una función que encuentre el determinante de una matriz usando la recursividad aqui planteada, explique explicitamente su código

In [ ]:
# Realizaremos una funcioon que nos cacule la ij-esima submatriz

def submatriz_inador(A, i, j):

    subf = np.delete(A, i, axis=0)
    sub = np.delete(subf, j, axis=1)

    return sub


def laplace(A):
  if np.shape(A)[0] == 1:
    return A[0,0]       # si la matriz tiene solo un elemento este sera el determinante
  else:
    det = 0
    for j in range(np.shape(A)[0]):
      det += (-1)**(1+j)*A[0,j]*laplace(submatriz_inador(A, 0, j))  # se reutilizara la funcion recursivamente hasta que cada submatriz se reduzca a unsolo termino y se aplique el primer condicional.


    return det

laplace(A), np.linalg.det(A), abs(laplace(A) - np.linalg.det(A))




(-208631324, -208631323.99999976, 2.384185791015625e-07)

#5

El método de Jacobi reescribe el sistema $ Ax = b $ descomponiendo la matriz $ A $ como:

$$
A = D + L + U,
$$

donde:
- $ D $: Matriz diagonal de $ A $,
- $ L $: Matriz triangular inferior sin la diagonal,
- $ U $: Matriz triangular superior sin la diagonal.

El sistema se reorganiza como:

$$
x = D^{-1}(b - (L + U)x).
$$

Esto se implementa iterativamente como:

$$
x_i^{(k+1)} = \frac{1}{a_{ii}} \left(b_i - \sum_{j \neq i} a_{ij} x_j^{(k)}\right),
$$

donde $ a_{ii} $ son los elementos diagonales de $ A $.

* Escriba una función explicita que realice de manera iterativa este método con una tol = 1e-7 y un máximo de 100 iteraciones. Defina una documentación clara que explique los métodos usados, lasa entradas y salidas.

* Para una matriz aleatoria 5$\times$ 5, encuentre la solución usando su función y determine el error con respecto a `solve` y el método de inversa de matriz.

In [ ]:
# Matriz normal
A = np.random.randint(-1000,1000, 25).reshape(5,5)
b = np.random.randint(-1000,1000, 5)


# Mariz con la diagunal mucha mas grande en magnitud que el resto de sus componentes
A_d = np.tril(A, -1) + np.diag(1000*np.diag(A)) + np.triu(A, 1)

A_d

array([[ 794000,    -298,     970,     944,    -690],
       [    676, -946000,    -909,    -117,    -576],
       [    632,    -726, -619000,    -472,    -484],
       [    417,     148,    -779, -411000,     460],
       [    206,     190,     684,     817, -458000]])

In [ ]:
#a)
def Jacobi(A, b, tol=1e-7, Nmax=100):
  """
  Esta función implementa el metodo de Jacobi para encontrar las soluciones a sistemas
  lineales, dadas su matriz de coeficientes asociadas 'A' y su repectiva solucion'b'

  - Parametros -

  A: mariz de coeficientes asociados.
  b: vector.
  tol: tolerancia de convergencia.
  Nmax: Numero maximo de iteraciones.

  - Devuelve :

  xk : array con el vector solucion.
  """
  x = np.zeros_like(b, dtype = float)
  D = np.diag(np.diag(A))
  L = np.tril(A) - D
  U = np.triu(A) - D
 # print(U)
  #print(D)
  D_inv = np.linalg.inv(D)
  #print(D_inv)

  for i in range(Nmax):
    xk = D_inv@(b - ((L + U) @ x))

    #print(np.max(np.abs(xk - x)))

    if np.max(np.abs(xk - x)) < tol:

      print(f'El resultado converge despues de {i} iteraciones')
      return xk
    x = xk


  print('No converge')
  return xk

#b)
sol = Jacobi(A,b, Nmax = 100)
sol_r = np.linalg.solve(A,b)

print(f"""para A normal:
{sol, sol_r}
      """)

sol_d = Jacobi(A_d,b, Nmax = 100)
sol_r_d = np.linalg.solve(A_d,b)

print(f"""para A con elementos en la diagonal de mayor magnitud al resto:
{sol_d, sol_r_d}""")

print("""
veamos que el metodo de Jácobi es deficiente para resolver sistemas de ecuaciones cualquiera,
pero muy bueno para resolver sistemas de ecuaciones donde los coeficientes de la diagonal de
la matriz de coeficientes son mucho mas mayores a losdemas coeficientes asociados a las variables""")



No converge
para A normal:
(array([ 2.63070472e+34,  8.78456544e+34,  1.08943827e+35,  8.58671032e+34,
       -7.91597656e+34]), array([-0.67462607,  3.65630478, -0.17230987, -2.7364661 , -5.45158912]))
      
El resultado converge despues de 2 iteraciones
para A con elementos en la diagonal de mayor magnitud al resto:
(array([-0.00077548,  0.00031657, -0.00154623,  0.00240688, -0.00152443]), array([-0.00077548,  0.00031657, -0.00154623,  0.00240688, -0.00152443]))

veamos que el metodo de Jácobi es deficiente para resolver sistemas de ecuaciones cualquiera,
pero muy bueno para resolver sistemas de ecuaciones donde los coeficientes de la diagonal de
la matriz de coeficientes son mucho mas mayores a losdemas coeficientes asociados a las variables


#6

Verifique que cualquier matriz hermitiana de 2 × 2 $ L $ puede escribirse como una suma de cuatro términos:

$$ L = a\sigma_x + b\sigma_y + c\sigma_z + dI $$

donde $ a $, $ b $, $ c $ y $ d $ son números reales.

Las cuatro matrices de Pauli son:

$$ \sigma_x = \begin{pmatrix} 0 & 1 \\ 1 & 0 \end{pmatrix}, \quad \sigma_y = \begin{pmatrix} 0 & -i \\ i & 0 \end{pmatrix}, \quad \sigma_z = \begin{pmatrix} 1 & 0 \\ 0 & -1 \end{pmatrix}, \quad I = \begin{pmatrix} 1 & 0 \\ 0 & 1 \end{pmatrix} $$




In [ ]:
# Sean a,,b,c,d numeros reales cualquieras:
a = np.random.random()*np.random.randint(-100,100)
b = np.random.random()*np.random.randint(-100,100)
c = np.random.random()*np.random.randint(-100,100)
d = np.random.random()*np.random.randint(-100,100)

print(f"""
a es : {a}
b es : {b}
c es : {c}
d es : {d}

      """)

# Ahora definamos lasmatrices de Pauli:
sigx = np.array([[0,1],[1,0]])
sigy = np.array([[0,-1j],[1j,0]])
sigz = np.array([[1,0],[0,-1]])
I = np.array([[1,0],[0,1]])
L = a*sigx + b*sigy + c*sigz + d*I

# Verifiquemos las condiciones de hermiticidad de una matriz
np.conjugate(L.T) == L



a es : -50.76920737116371
b es : 38.73951643517992
c es : -69.8990032693908
d es : -21.102259983596486

      


array([[ True,  True],
       [ True,  True]])