In [31]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as la

# Actividad 08: Algebra Lineal y Matrices

---
### Profesor: Juan Marcos Marín
### Nombre: Miguel Ángel Jaramillo Valencia
*Métodos computacionales 2024-II*

---

#1

Escriba una función que calcule el producto escalar y vectorial para dos vectores, compare sus resultados con `np.dot` y `np.cross`.

In [32]:
A = np.array([4, 5, 6])
B = np.array([7, 8, 9])
C = np.zeros([len(A)])
D = np.zeros([len(A)])
def P_punto(A, B):

  C = np.zeros([len(A)])

  if len(A) != len(B):
    return ('Las dimensiones de los vectores son diferentes')

  for i in range(len(A)):

    C[i] = A[i] * B[i]

  S = np.sum(C)

  D[0] = A[1] * B[2] - A[2] * B[1]
  D[1] = A[0] * B[2] - A[2] * B[0]
  D[2] = A[0] * B[1] - A[1] * B[0]
  return S, np.dot(A,B), D, np.cross(A,B)

In [33]:
P_punto(A,B)

(122.0, 122, array([-3., -6., -3.]), array([-3,  6, -3]))

#2

Crear una función llamada `mulmat()` donde a partir de dos matrices $A$ y $B$ encuentre su multplicación. También realiza una función que calcule la transpuesta y otra el determinante de una matriz $3\times 3$. Compare sus resultado con `@`, `np.dot`, `transpose` y `la.det`.

In [53]:
def mulmat(A, B):

  filas_A = A.shape[1]
  filas = A.shape[0]
  columnas = B.shape[1]

  new_matrix = np.zeros((filas, columnas))


  for i in range(filas):
    for j in range(columnas):
      sum = 0
      for k in range(filas_A):

        sum += A[i, k] * B[k, j]

      new_matrix[i , j] = sum

  return new_matrix, A @ B


def transpuesta(A):

  filas = A.shape[0]
  columnas = A.shape[0]

  new_A = np.zeros((columnas, filas))

  for i in range(filas):
    for j in range(columnas):

      new_A[i, j] = A[j, i]

  return new_A, A.T

def det(A):

  n = len(A)
  suma = 0

  if n == 1:
      return A[0,0]

  else:
    for j in range(n):

      submatriz = A[1 : ,[k for k in range(n) if k!=j]]

      suma += (-1) ** (1 + j) * A[0, j] * det(submatriz)

    return suma

In [35]:
A = np.random.randint(1, 100, size = (3,3))
B= np.random.randint(1, 100, size = (3,3))

mulmat(A, B)

(array([[ 7075.,  6248.,  7991.],
        [10050.,  8132.,  9757.],
        [ 5104.,  2836.,  3077.]]),
 array([[ 7075,  6248,  7991],
        [10050,  8132,  9757],
        [ 5104,  2836,  3077]]))

In [36]:
transpuesta(A)

(array([[73., 83., 11.],
        [15., 16., 48.],
        [36., 85., 31.]]),
 array([[73, 83, 11],
        [15, 16, 48],
        [36, 85, 31]]))

In [55]:
det(A), la.det(A)

(217391, 217391.0)

#3
Escriba tres matrices aleatorias $A$, $B$ y $C$ de $3\times 3$, y demuestre las siguientes relaciones

- $ \mathbf{A}\mathbf{B} \neq \mathbf{B}\mathbf{A} $, en general.
- $ (\mathbf{A}\mathbf{B})\mathbf{C} = \mathbf{A}(\mathbf{B}\mathbf{C}) $.
- $ \mathbf{A}(\mathbf{B} + \mathbf{C}) = \mathbf{A}\mathbf{B} + \mathbf{A}\mathbf{C} $.
- $ (\mathbf{A} + \mathbf{B})\mathbf{C} = \mathbf{A}\mathbf{C} + \mathbf{B}\mathbf{C} $.
- $ (\mathbf{A}\mathbf{B})^\top = \mathbf{B}^\top \mathbf{A}^\top $.
- $ \det(\mathbf{A}\mathbf{B}) = \det(\mathbf{A}) \det(\mathbf{B}) $.
- $ (\mathbf{A}^\top)^\top = \mathbf{A} $.
- $ (c\mathbf{A})^\top = c\mathbf{A}^\top $.
- $ (\mathbf{A} + \mathbf{B})^\top = \mathbf{A}^\top + \mathbf{B}^\top $.



In [56]:
A1 = np.random.randint(1, 100, size = (3,3))
B1 = np.random.randint(1, 100, size = (3,3))
C = np.random.randint(1, 100, size = (3,3))

In [57]:
print(A1 @ B1)
print('')
print(B1 @ A1)

[[ 8260 10364  4992]
 [ 9447 16231  6027]
 [10560 13196  5450]]

[[ 9951  5762  8080]
 [ 7783  8282  6931]
 [14373 14070 11708]]


In [59]:
print((A1 @ B1) @ C)
print('')
print(A1 @ (B1 @ C))

[[ 889788  562692 1783616]
 [1283172  684361 2449164]
 [1125930  689172 2230680]]

[[ 889788  562692 1783616]
 [1283172  684361 2449164]
 [1125930  689172 2230680]]


In [61]:
print(A1 @ (B1 + C))
print('')
print(A1 @ B1 + (A1 @ C))

[[14776 13736 17344]
 [15156 22299 19915]
 [15504 17826 17028]]

[[14776 13736 17344]
 [15156 22299 19915]
 [15504 17826 17028]]


In [62]:
print((A1 + B1) @ C)
print('')
print(A1 @ C + (B1 @ C))

[[12456  5023 22292]
 [ 9972  9724 23364]
 [13392 10347 28774]]

[[12456  5023 22292]
 [ 9972  9724 23364]
 [13392 10347 28774]]


In [63]:
print((A1 @ B1).T)
print('')
print(B1.T @ A1.T)

[[ 8260  9447 10560]
 [10364 16231 13196]
 [ 4992  6027  5450]]

[[ 8260  9447 10560]
 [10364 16231 13196]
 [ 4992  6027  5450]]


In [65]:
print(la.det(A1 @ B1))
print('')
print(la.det(B1) * la.det(A1))

-33560085856.000015

-33560085856.00001


In [66]:
print((A1.T).T)
print('')
print(A1)

[[44 84 32]
 [92 44 65]
 [47 50 75]]

[[44 84 32]
 [92 44 65]
 [47 50 75]]


In [67]:
print((3 * A1.T).T)
print('')
print(3 * A1)

[[132 252  96]
 [276 132 195]
 [141 150 225]]

[[132 252  96]
 [276 132 195]
 [141 150 225]]


In [68]:
print((A1 + B1).T)
print('')
print(A1.T + B1.T)

[[ 49 150 146]
 [177  84 141]
 [ 57  98 110]]

[[ 49 150 146]
 [177  84 141]
 [ 57  98 110]]


#4

El **Teorema de Laplace** es un método para calcular el determinante de una matriz cuadrada, particularmente útil para matrices de orden mayor a 2. Este teorema se basa en la expansión del determinante por los elementos de una fila o una columna cualquiera.



$$
\det(A) = \sum_{j=1}^n (-1)^{1+j} a_{1j} M_{1j}
$$

donde:
- $a_{1j}$ es el elemento de la primera fila y columna $j$.
- $M_{1j}$ es el menor asociado al elemento $a_{1j}$, es decir, el determinante de la submatriz de $3 \times 3$ que se obtiene al eliminar la fila 1 y la columna $j$.
- $(-1)^{1+j}$ es el signo correspondiente al cofactor del elemento $a_{1j}$.

Podemos realizar una función recursiva para el cálculo del determinante, sabiendo que el valor del determinante de una matriz de orden uno es el único elemento de esa matriz, y el de una matriz de orden superior a uno es la suma de cada uno de los elementos de una fila o columna por los Adjuntos a ese elemento, como en la función recursiva se emplea la misma función definida el cálculo lo haremos por Menor complementario, un ejemplo desarrollado por la primera fila sería:

$$
   \det (A_{j,j}) =
   \left \{
   \begin{array}{llcl}
      si & j = 1 & \to & a_{1,1} \\
                                 \\
      si & j > 1 & \to & \displaystyle \sum_{k=1}^j \; (-1)^{(1+k)} \cdot a_{1,k} \cdot \det( \alpha_{1,k})
   \end{array}
   \right .
$$

Realice una función que encuentre el determinante de una matriz usando la recursividad aqui planteada, explique explicitamente su código

In [40]:
def det(A):

  n = len(A)
  suma = 0

  if n == 1:
      return A[0,0]

  else:
    for j in range(n):

      submatriz = A[1 : ,[k for k in range(n) if k!=j]]

      suma += (-1) ** (1 + j) * (A[0, j] * det(submatriz))
    return suma

In [41]:
A = np.random.randint(1, 100, size = (3,3))

det(A), np.linalg.det(A)

(217391, 217390.9999999999)

#5

El método de Jacobi reescribe el sistema $ Ax = b $ descomponiendo la matriz $ A $ como:

$$
A = D + L + U,
$$

donde:
- $ D $: Matriz diagonal de $ A $,
- $ L $: Matriz triangular inferior sin la diagonal,
- $ U $: Matriz triangular superior sin la diagonal.

El sistema se reorganiza como:

$$
x = D^{-1}(b - (L + U)x).
$$

Esto se implementa iterativamente como:

$$
x_i^{(k+1)} = \frac{1}{a_{ii}} \left(b_i - \sum_{j \neq i} a_{ij} x_j^{(k)}\right),
$$

donde $ a_{ii} $ son los elementos diagonales de $ A $.

* Escriba una función explicita que realice de manera iterativa este método con una tol = 1e-7 y un máximo de 100 iteraciones. Defina una documentación clara que explique los métodos usados, lasa entradas y salidas.

* Para una matriz aleatoria 5$\times$ 5, encuentre la solución usando su función y determine el error con respecto a `solve` y el método de inversa de matriz.

In [139]:
def jacobi(A, B, tol=1e-7, max_iter=100):
    n = len(B)
    x = np.zeros_like(B, dtype=float)  # Solución inicial (x = 0)

    for k in range(max_iter):
        x_new = np.copy(x)

        for i in range(n):
            suma = sum(A[i, j] * x[j] for j in range(n) if j != i)
            x_new[i] = (B[i] - suma) / A[i, i]

        # Examinar la convergencia
        if np.max(np.abs(x_new - x)) < tol:
            print(f'Converge después de {k + 1} iteraciones')
            return x_new

        x = x_new

In [141]:
A = np.random.randint(1, 100, size=(5, 5))
B = np.random.randint(1, 100, size=(5,))

for i in range(len(A)):
    A[i, i] = np.sum(np.abs(A[i, :])) + 1  # sin esta línea no da bien la solución

jacobi_ = jacobi(A, B)

solve_ = np.linalg.solve(A, B)

print("Solución con Jacobi:", jacobi_)
print("Solución con la.solve:", solve_)
print("Diferencias:", np.abs(jacobi_ - solve_))

Converge después de 77 iteraciones
Solución con Jacobi: [-0.03624754  0.01067666  0.18711973  0.36398629  0.3340749 ]
Solución con la.solve: [-0.03624758  0.01067662  0.18711969  0.36398625  0.33407487]
Diferencia: [4.14521098e-08 3.94312631e-08 3.85767509e-08 3.74068541e-08
 3.05393033e-08]


#6

Verifique que cualquier matriz hermitiana de 2 × 2 $ L $ puede escribirse como una suma de cuatro términos:

$$ L = a\sigma_x + b\sigma_y + c\sigma_z + dI $$

donde $ a $, $ b $, $ c $ y $ d $ son números reales.

Las cuatro matrices de Pauli son:

$$ \sigma_x = \begin{pmatrix} 0 & 1 \\ 1 & 0 \end{pmatrix}, \quad \sigma_y = \begin{pmatrix} 0 & -i \\ i & 0 \end{pmatrix}, \quad \sigma_z = \begin{pmatrix} 1 & 0 \\ 0 & -1 \end{pmatrix}, \quad I = \begin{pmatrix} 1 & 0 \\ 0 & 1 \end{pmatrix} $$




In [175]:

sigma_x = np.array([
    [0, 1],
    [1, 0]
])

sigma_y = np.array([
    [0, -1j],
    [1j, 0]
])

sigma_z = np.array([
    [1, 0],
    [0, -1]
], dtype = complex)

I = np.array([
    [1, 0],
    [0, 1]
])

In [190]:
A = np.random.rand(2, 2) + 1j * np.random.rand(2, 2)

L = A.conj().T

L

array([[0.44735886-0.64716526j, 0.26752113-0.206323j  ],
       [0.54065107-0.2903736j , 0.45849512-0.85089019j]])

de los hechos siguientes se calculan a, b, c y d:

$c_0$ = $(a + d) / 2$

$c_1$ = $Re$$(b)$

$c_2$ = $Im(b)$

$c_3$ = $(a - d) / 2$

siendo a, b, c y d las entradas de la matriz

In [194]:
d, b, a, c = (L[0,0] + L[1,1]) / 2, (L[0,1]).real, L[0,1].imag, (L[0,0] - L[1,1]) / 2

In [193]:
a * sigma_x + b * sigma_y + c * sigma_z + d * I

array([[ 0.44735886-0.64716526j, -0.206323  -0.26752113j],
       [-0.206323  +0.26752113j,  0.45849512-0.85089019j]])