In [2]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as la

# Actividad 08: Algebra Lineal y Matrices

---
### Profesor: Juan Marcos Marín
### Nombre: Simón Cortés
*Métodos computacionales 2024-II*

---

#1

Escriba una función que calcule el producto escalar y vectorial para dos vectores, compare sus resultados con `np.dot` y `np.cross`.

In [ ]:
def producto_escalar(v,u):
  n_v = v.shape
  n_u = u.shape
  if n_v != n_u:
    raise ValueError ('Los vectores deben tener la misma dimensión')
  producto = 1
  suma = 0
  for i in range(v.size):
    producto = v[i]*u[i]
    suma += producto
  return suma

def producto_vectorial(v,u):
  n_v = v.size
  n_u = u.size
  if n_v != 3:
    raise ValueError ('Los vectores deben tener dimensión 3')
  elif n_u != 3:
    raise ValueError ('Los vectores deben tener dimensión 3')
  i = np.array([
      [v[1], v[2]],
      [u[1], u[2]]
  ])
  j = np.array([
      [v[0], v[2]],
      [u[0], u[2]]
  ])
  k = np.array([
      [v[0], v[1]],
      [u[0], u[1]]
  ])
  vector = np.array([la.det(i), -la.det(j), la.det(k)])
  return vector


In [ ]:
v = np.array([1,2,3])
u = np.array([4,5,6])

producto_punto = producto_escalar(v,u)
print(f'El valor del producto escalar con la función es {producto_punto} y con np.dot es {np.dot(v,u)}')

producto_cruz = producto_vectorial(v,u)
productocruz_np = np.cross(v,u)
print(f'El valor del producto vectorial con la función es {producto_cruz} y con np.cross es {np.cross(v,u)}')


El valor del producto escalar con la función es 32 y con np.dot es 32
El valor del producto vectorial con la función es [-3.  6. -3.] y con np.cross es [-3  6 -3]


#2

Crear una función llamada `mulmat()` donde a partir de dos matrices $A$ y $B$ encuentre su multplicación. También realiza una función que calcule la transpuesta y otra el determinante de una matriz $3\times 3$. Compare sus resultado con `@`, `np.dot`, `transpose` y `la.det`.

In [5]:
def mulmat(A,B):
  fil_A = A.shape[0]
  col_A = A.shape[1]
  fil_B = B.shape[0]
  col_B = B.shape[1]
  if col_A != fil_B:
    raise ValueError ('Las matrices no se pueden multiplicar')
  C = np.zeros((fil_A,col_B))
  for i in range(fil_A):
    for j in range(col_B):
      for k in range(col_A):
        C[i,j] += A[i,k]*B[k,j]
  return C

def transpuesta(A):
  fil_A = A.shape[0]
  col_A = A.shape[1]
  A_T = np.zeros((col_A,fil_A))
  for i in range(col_A):
    A_T[i] = A[:,i]
  for j in range(fil_A):
    A_T[:,j] = A[j]
  return A_T

def determinante(A):
  if A.shape[0] != 3:
    raise ValueError ('La matriz no 3x3')
  elif A.shape[1] != 3:
    raise ValueError ('La matriz no 3x3')
  det = ((A[0,0]*A[1,1]*A[2,2]) + (A[1,0]*A[2,1]*A[0,2]) + (A[2,0]*A[0,1]*A[1,2]))-((A[0,2]*A[1,1]*A[2,0]) + (A[1,2]*A[2,1]*A[0,0]) + (A[2,2]*A[0,1]*A[1,0]))
  return det

In [10]:
A = np.array([
    [1,2,0],
    [2,0,1],
    [0,1,3]
])

B= np.array([
    [3,2,1,3],
    [6,5,4,6],
    [9,8,7,9]
])

C = mulmat(A,B)
print(f'El resultado de AB con la función es {C}')
print(f'El resultado de AB con @ es {A@B}')
print()
A_T = transpuesta(A)
print(f'La transpuesta de A con la función es {A_T}')
print(f'La transpuesta de A con transpose es {A.transpose()}')
print()
det_A = determinante(A)
print(f'El determinante de A con la función es {det_A}')
print(f'El determinante de A con la funcion es {la.det(A)}')

El resultado de AB con la función es [[15. 12.  9. 15.]
 [15. 12.  9. 15.]
 [33. 29. 25. 33.]]
El resultado de AB con @ es [[15 12  9 15]
 [15 12  9 15]
 [33 29 25 33]]

La transpuesta de A con la función es [[1. 2. 0.]
 [2. 0. 1.]
 [0. 1. 3.]]
La transpuesta de A con transpose es [[1 2 0]
 [2 0 1]
 [0 1 3]]

El determinante de A con la función es -13
El determinante de A con la funcion es -13.0


#3
Escriba tres matrices aleatorias $A$, $B$ y $C$ de $3\times 3$, y demuestre las siguientes relaciones

- $ \mathbf{A}\mathbf{B} \neq \mathbf{B}\mathbf{A} $, en general.
- $ (\mathbf{A}\mathbf{B})\mathbf{C} = \mathbf{A}(\mathbf{B}\mathbf{C}) $.
- $ \mathbf{A}(\mathbf{B} + \mathbf{C}) = \mathbf{A}\mathbf{B} + \mathbf{A}\mathbf{C} $.
- $ (\mathbf{A} + \mathbf{B})\mathbf{C} = \mathbf{A}\mathbf{C} + \mathbf{B}\mathbf{C} $.
- $ (\mathbf{A}\mathbf{B})^\top = \mathbf{B}^\top \mathbf{A}^\top $.
- $ \det(\mathbf{A}\mathbf{B}) = \det(\mathbf{A}) \det(\mathbf{B}) $.
- $ (\mathbf{A}^\top)^\top = \mathbf{A} $.
- $ (c\mathbf{A})^\top = c\mathbf{A}^\top $.
- $ (\mathbf{A} + \mathbf{B})^\top = \mathbf{A}^\top + \mathbf{B}^\top $.



In [ ]:
A = np.random.randint(1,6, (3,3))
B = np.random.randint(1,6, (3,3))
C = np.random.randint(1,6, (3,3))
c = np.random.randint(1,10)

# Conmutatividad
print(f'AB = {mulmat(A,B)}')
print(f'BA = {mulmat(B,A)}')
print('¿Se cumple la conmutatividad?', np.array_equal(A@B, B@A))
print()
#Asociatividad
print(f'(AB)C = {mulmat(mulmat(A,B),C)}')
print(f'A(BC) = {mulmat(A,mulmat(B,C))}')
print('¿Se cumple la asociatividad?', np.array_equal(mulmat(mulmat(A,B),C), mulmat(A,mulmat(B,C))))
print()
#Distributividad 1
print(f'A(B+C) = {mulmat(A,B+C)}')
print(f'AB + AC = {mulmat(A,B) + mulmat(A,C)}')
print('¿Se cumple A(B+C) = AB + AC?', np.array_equal(mulmat(A,B+C), mulmat(A,B) + mulmat(A,C)))
print()
#Distributividad 2
print(f'(A+B)C = {mulmat(A+B,C)}')
print(f'AC + BC = {mulmat(A,C) + mulmat(B,C)}')
print('¿Se cumple (A+B)C = AC + BC?', np.array_equal(mulmat(A+B,C), mulmat(A,C) + mulmat(B,C)))
print()
#Transpuesta de producto de matrices
print(f'(AB)^T = {transpuesta(mulmat(A,B))}')
print(f'B^T A^T = {transpuesta(B) @ transpuesta(A)}')
print('¿Se cumple (AB)^T = B^T A^T', np.array_equal(transpuesta(mulmat(A,B)), transpuesta(B) @ transpuesta(A)))
print()
#Distribución de Determinante
print(f'det(AB) = {determinante(mulmat(A,B))}')
print(f'det(A) * det(B) = {determinante(A) * determinante(B)}')
print('¿Se cumple det(AB) = det(A) * det(B)?', determinante(mulmat(A,B)) == determinante(A) * determinante(B))
print()
#Transpuesta de la Transpuesta
print(f'(A^T)^T = {transpuesta(transpuesta(A))}')
print(f'A = {A}')
print('¿Se cumple (A^T)^T = A?', np.array_equal(transpuesta(transpuesta(A)),A))
print()
#Transpuesta como operador lineal: multiplicación por escalar
print(f'(cA)^T = {transpuesta(c*A)}')
print(f'cA^T = {c*transpuesta(A)}')
print('¿Se cumple (cA)^T = cA^T?', np.array_equal(transpuesta(c*A),c*transpuesta(A)))
print()
#Transpuesta como operador lineal: suma
print(f'(A+B)^T = {transpuesta(A+B)}')
print(f'A^T + B^T = {transpuesta(A) + transpuesta(B)}')
print('¿Se cumple (A+B)^T = A^T + B^T?', np.array_equal(transpuesta(A+B),transpuesta(A) + transpuesta(B)))

AB = [[50. 38. 49.]
 [31. 19. 28.]
 [55. 35. 54.]]
BA = [[39. 45. 50.]
 [34. 38. 47.]
 [33. 43. 46.]]
¿Se cumple la conmutatividad? False

(AB)C = [[360. 500. 224.]
 [200. 287. 125.]
 [376. 523. 233.]]
A(BC) = [[360. 500. 224.]
 [200. 287. 125.]
 [376. 523. 233.]]
¿Se cumple la asociatividad? True

A(B+C) = [[83. 80. 69.]
 [50. 45. 40.]
 [93. 80. 77.]]
AB + AC = [[83. 80. 69.]
 [50. 45. 40.]
 [93. 80. 77.]]
¿Se cumple A(B+C) = AB + AC? True

(A+B)C = [[65. 93. 41.]
 [43. 63. 27.]
 [70. 82. 42.]]
AC + BC = [[65. 93. 41.]
 [43. 63. 27.]
 [70. 82. 42.]]
¿Se cumple (A+B)C = AC + BC? True

(AB)^T = [[50. 31. 55.]
 [38. 19. 35.]
 [49. 28. 54.]]
B^T A^T = [[50. 31. 55.]
 [38. 19. 35.]
 [49. 28. 54.]]
¿Se cumple (AB)^T = B^T A^T True

det(AB) = -832.0
det(A) * det(B) = -832
¿Se cumple det(AB) = det(A) * det(B)? True

(A^T)^T = [[4. 3. 5.]
 [2. 3. 2.]
 [3. 5. 5.]]
A = [[4 3 5]
 [2 3 2]
 [3 5 5]]
¿Se cumple (A^T)^T = A? True

(cA)^T = [[36. 18. 27.]
 [27. 27. 45.]
 [45. 18. 45.]]
cA^T = [[36. 18

#4

El **Teorema de Laplace** es un método para calcular el determinante de una matriz cuadrada, particularmente útil para matrices de orden mayor a 2. Este teorema se basa en la expansión del determinante por los elementos de una fila o una columna cualquiera.



$$
\det(A) = \sum_{j=1}^n (-1)^{1+j} a_{1j} M_{1j}
$$

donde:
- $a_{1j}$ es el elemento de la primera fila y columna $j$.
- $M_{1j}$ es el menor asociado al elemento $a_{1j}$, es decir, el determinante de la submatriz de $3 \times 3$ que se obtiene al eliminar la fila 1 y la columna $j$.
- $(-1)^{1+j}$ es el signo correspondiente al cofactor del elemento $a_{1j}$.

Podemos realizar una función recursiva para el cálculo del determinante, sabiendo que el valor del determinante de una matriz de orden uno es el único elemento de esa matriz, y el de una matriz de orden superior a uno es la suma de cada uno de los elementos de una fila o columna por los Adjuntos a ese elemento, como en la función recursiva se emplea la misma función definida el cálculo lo haremos por Menor complementario, un ejemplo desarrollado por la primera fila sería:

$$
   \det (A_{j,j}) =
   \left \{
   \begin{array}{llcl}
      si & j = 1 & \to & a_{1,1} \\
                                 \\
      si & j > 1 & \to & \displaystyle \sum_{k=1}^j \; (-1)^{(1+k)} \cdot a_{1,k} \cdot \det( \alpha_{1,k})
   \end{array}
   \right .
$$

Realice una función que encuentre el determinante de una matriz usando la recursividad aqui planteada, explique explicitamente su código

In [ ]:
def determinante_laplace(A):
  if A.shape[0] != A.shape[1]: #Comprueba que la matriz sea cuadrada
    raise ValueError ('La matriz no es cuadrada')
  if A.shape[0] == 1: #Comprueba el caso j=1
    return A[0,0] #Regresa a(1,1)
  else: #Si no se cumple j=1, implementa el Teorema de Laplace
    det = 0
    for k in range(A.shape[0]):
      matriz_menor = np.delete(np.delete(A,0,axis=0), k, axis=1) #Para cada k en la sumatoria, calcula la matriz menor A[1,k]
      det += (-1)**(k) * A[0,k] * la.det(matriz_menor) #Para cada k en la sumatoria, calcula el valor del determinante dada la matriz menor A[1,k]
    return det


In [ ]:
A = np.random.randint(1,6, (3,3))
det_laplace = determinante_laplace(A)
print(f'El determinante de la matriz {A} con la función recursiva es {det_laplace}')
print(f'El determinante de la matriz {A} con la función de numpy es {la.det(A)}')


El determinante de la matriz [[5 3 4]
 [3 3 1]
 [3 5 3]] con la función recursiva es 26.0
El determinante de la matriz [[5 3 4]
 [3 3 1]
 [3 5 3]] con la función de numpy es 26.0


#5

El método de Jacobi reescribe el sistema $ Ax = b $ descomponiendo la matriz $ A $ como:

$$
A = D + L + U,
$$

donde:
- $ D $: Matriz diagonal de $ A $,
- $ L $: Matriz triangular inferior sin la diagonal,
- $ U $: Matriz triangular superior sin la diagonal.

El sistema se reorganiza como:

$$
x = D^{-1}(b - (L + U)x).
$$

Esto se implementa iterativamente como:

$$
x_i^{(k+1)} = \frac{1}{a_{ii}} \left(b_i - \sum_{j \neq i} a_{ij} x_j^{(k)}\right),
$$

donde $ a_{ii} $ son los elementos diagonales de $ A $.

* Escriba una función explicita que realice de manera iterativa este método con una tol = 1e-7 y un máximo de 100 iteraciones. Defina una documentación clara que explique los métodos usados, lasa entradas y salidas.

* Para una matriz aleatoria 5$\times$ 5, encuentre la solución usando su función y determine el error con respecto a `solve` y el método de inversa de matriz.

In [ ]:
def jacobi(A, b, tol = 1e-7, max_iter = 100):
  x = np.zeros_like(b, dtype=float)

  for k in range(max_iter):
    x_nuevo = np.copy(x)

    for i in range(len(A)):
      suma = np.dot(A[i, :],x) - A[i,i]*x[i]
      x_nuevo[i] = (b[i] - suma)/A[i,i]

    if np.linalg.norm(x_nuevo - x) < tol:
      print(f'El método convergió con {k+1} iteraciones')
      return x_nuevo
    x = x_nuevo

  print('El método no convergió después de 100 iteraciones')
  return x

In [ ]:
A = np.random.randint(1,6, (5,5)).astype(float)

# Como el método de Jacobi solo funciona si la matriz es diagonalmente dominante,
# hay que asegurarnos que se cumpla la condición para las matrices generadas aleatoriamente.

for i in range(len(A)):
  A[i,i] = np.sum(np.abs(A[i])) + 1 #Se fuerza a que la diagonal sea mayor que la suma de los otros términos

b = np.random.randint(1,6,5).astype(float)

x_jacobi = jacobi(A,b)
x_np = np.linalg.solve(A,b)
x_inv = np.linalg.inv(A) @ b

error_np = np.linalg.norm(x_np - x_jacobi)
error_inv = np.linalg.norm(x_inv - x_jacobi)

print(f'La solución del sistema Ax=b para A={A} y b={b} es:')
print(f'Con la función: {x_jacobi}')
print(f'Con np.solve: {x_np}')
print(f'Con el método de la inversa de la matriz: {x_inv}')
print(f'El error con respecto a np.solve es {error_np}')
print(f'El error con respecto al método de la inversa es {error_inv}')

El método convergió con 52 iteraciones
La solución del sistema Ax=b para A=[[15.  1.  3.  2.  3.]
 [ 5. 17.  4.  3.  2.]
 [ 3.  2. 14.  3.  4.]
 [ 4.  5.  2. 20.  5.]
 [ 3.  2.  4.  1. 15.]] y b=[5. 1. 5. 2. 1.] es:
Con la función: [ 0.2822856  -0.10082267  0.31816987  0.05311497 -0.06473375]
Con np.solve: [ 0.28228562 -0.10082265  0.31816989  0.05311499 -0.06473374]
Con el método de la inversa de la matriz: [ 0.28228562 -0.10082265  0.31816989  0.05311499 -0.06473374]
El error con respecto a np.solve es 3.8974391500863285e-08
El error con respecto al método de la inversa es 3.897439150233518e-08


#6

Verifique que cualquier matriz hermitiana de 2 × 2 $ L $ puede escribirse como una suma de cuatro términos:

$$ L = a\sigma_x + b\sigma_y + c\sigma_z + dI $$

donde $ a $, $ b $, $ c $ y $ d $ son números reales.

Las cuatro matrices de Pauli son:

$$ \sigma_x = \begin{pmatrix} 0 & 1 \\ 1 & 0 \end{pmatrix}, \quad \sigma_y = \begin{pmatrix} 0 & -i \\ i & 0 \end{pmatrix}, \quad \sigma_z = \begin{pmatrix} 1 & 0 \\ 0 & -1 \end{pmatrix}, \quad I = \begin{pmatrix} 1 & 0 \\ 0 & 1 \end{pmatrix} $$




In [ ]:
#Definimos las matrices de Pauli
sigma_x = np.array([
    [0,1],
    [1,0]
])

sigma_y = np.array([
    [0,-1j],
    [1j,0]
])

sigma_z = np.array([
    [1,0],
    [0,-1]
])

I = np.array([
    [1,0],
    [0,1]
])

#Creamos una Matriz Hermitiana L
parte_real_L = np.random.randint(-5,5,(2,2))
parte_imag_L = np.random.randint(-5,5,(2,2))*1j
B = parte_real_L + parte_imag_L
L = (B + B.conj().T)/2

#Creamos una matriz como una combinación lineal de cuatro escalares a,b,c,d con las cuatro matrices de Pauli
from sympy import symbols, Eq, solve
a,b,c,d = symbols('a b c d')
L_ = a*sigma_x + b*sigma_y + c*sigma_z + d*I

#Igualando los componentes [i,j] de ambas matrices creamos un sistema 4x4
eq1 = Eq(L[0,0], L_[0,0])
eq2 = Eq(L[0,1], L_[0,1])
eq3 = Eq(L[1,0], L_[1,0])
eq4 = Eq(L[1,1], L_[1,1])

#Solucionamos el sistema 4x4 y comprobamos que siempre existe una solución única para a,b,c y d
sol = solve((eq1,eq2,eq3,eq4), (a,b,c,d))

print(f'Dada una matriz Hermitiana aleatoria {L}, esta se puede escribir en términos de las matrices de Pauli como:')
print(f'a{sigma_x} + b{sigma_y} + c{sigma_z} + d{I} = {L_}')
print(f'Donde a={sol[a]}, b={sol[b]}, c={sol[c]} y d={sol[d]}')
print(f'Debido a que:')
print(f'{L} = {sol[a]*sigma_x + sol[b]*sigma_y + sol[c]*sigma_z + sol[d]*I}')
print('y por lo tanto:')
print(f'{L[0,0]} = {sol[c]+sol[d]}')
print(f'{L[0,1]} = {sol[a]-sol[b]*1j}')
print(f'{L[1,0]} = {sol[a]+sol[b]*1j}')
print(f'{L[1,1]} = {-sol[c]+sol[d]}')

Dada una matriz Hermitiana aleatoria [[-2. +0.j -1.5+4.j]
 [-1.5-4.j -4. +0.j]], esta se puede escribir en términos de las matrices de Pauli como:
a[[0 1]
 [1 0]] + b[[ 0.+0.j -0.-1.j]
 [ 0.+1.j  0.+0.j]] + c[[ 1  0]
 [ 0 -1]] + d[[1 0]
 [0 1]] = [[c + d a - 1.0*I*b]
 [a + 1.0*I*b -c + d]]
Donde a=-1.50000000000000, b=-4.00000000000000, c=1.00000000000000 y d=-3.00000000000000
Debido a que:
[[-2. +0.j -1.5+4.j]
 [-1.5-4.j -4. +0.j]] = [[-2.00000000000000 -1.5 + 4.0*I]
 [-1.5 - 4.0*I -4.00000000000000]]
y por lo tanto:
(-2+0j) = -2.00000000000000
(-1.5+4j) = -1.5 + 4.0*I
(-1.5-4j) = -1.5 - 4.0*I
(-4+0j) = -4.00000000000000
