<a href="https://colab.research.google.com/github/Elizajr/CursoMetodosComputacionales/blob/main/Act_09_DiagonalizacionMatrices.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Autovalores, autovectores, polinomio caracteristico, diagonalización.

In [ ]:
import numpy as np
from numpy import linalg
import sympy as sy
from IPython.display import display, Latex

In [ ]:
ma = np.matrix([[1,-1, 4],
               [3, 2,-1],
               [2, 1,-1]])

mb = np.matrix([[3, -5],
                [1, -1]])

A = sy.Matrix(ma)

B = sy.Matrix(mb)
display(Latex("A="),A)
print(" ")
display(Latex("B="), B)

<IPython.core.display.Latex object>

Matrix([
[1, -1,  4],
[3,  2, -1],
[2,  1, -1]])

<IPython.core.display.Latex object>

Matrix([
[3, -5],
[1, -1]])

In [ ]:
a_np_val,a_np_vec = np.linalg.eig(ma)
a_np_val

array([ 3., -2.,  1.])

In [ ]:
a_sy_val = np.array(list(A.eigenvals().keys()))
a_sy_val

array([3, 1, -2], dtype=object)

In [ ]:
a_np_vec

matrix([[ 0.40824829,  0.57735027,  0.23570226],
        [ 0.81649658, -0.57735027, -0.94280904],
        [ 0.40824829, -0.57735027, -0.23570226]])

In [ ]:
(np.linalg.inv(a_np_vec) * ma * a_np_vec).round()

matrix([[ 3., -0., -0.],
        [ 0., -2., -0.],
        [ 0., -0.,  1.]])

In [ ]:
sy_veca = A.eigenvects()
sy_veca

[(-2,
  1,
  [Matrix([
   [-1],
   [ 1],
   [ 1]])]),
 (1,
  1,
  [Matrix([
   [-1],
   [ 4],
   [ 1]])]),
 (3,
  1,
  [Matrix([
   [1],
   [2],
   [1]])])]

In [ ]:
v0 = sy_veca[0][2][0]
v1 = (sy_veca)[1][2][0]
v2 = (sy_veca)[2][2][0]
a_sy_vec = v0.row_join(v1)
a_sy_vec = a_sy_vec.row_join(v2)

In [ ]:
a_sy_vec.inv()*A*a_sy_vec

Matrix([
[-2, 0, 0],
[ 0, 1, 0],
[ 0, 0, 3]])

In [ ]:
def diagonalizar_np(A):
  a_np_val,a_np_vec = np.linalg.eig(A)
  return (np.linalg.inv(a_np_vec) * A * a_np_vec).round()


In [ ]:
sy.Matrix(diagonalizar_np(mb))

Matrix([
[1.0 + 1.0*I,           0],
[          0, 1.0 - 1.0*I]])

In [ ]:
def diagonalizar_sy(A):
  A = sy.Matrix(A)
  dim = sy.shape(A)
  if dim[0] == dim[1]:
    sy_veca = A.eigenvects()
    salida = sy_veca[0][2][0]
    for m in range(dim[1]):
      salida = salida.row_join3(sy_veca[i+1][2][0])
    return salida.inv()*A*salida
  else:
    raise TypeError("No es una matriz cuadrada")

In [ ]:
#diagonalizar_sy(mb)

In [ ]:
sy.Matrix(diagonalizar_np(ma))

Matrix([
[3.0,    0,   0],
[  0, -2.0,   0],
[  0,    0, 1.0]])

In [ ]:
A

Matrix([
[1, -1,  4],
[3,  2, -1],
[2,  1, -1]])

In [ ]:
A.charpoly()

PurePoly(lambda**3 - 2*lambda**2 - 5*lambda + 6, lambda, domain='ZZ')

In [ ]:
np.poly(ma)

array([ 1., -2., -5.,  6.])

In [ ]:
t_ = sy.Symbol("t")
It = (np.diag(np.ones(np.shape(A)[0],dtype=int))*t_)
sy.Matrix(It)

Matrix([
[t, 0, 0],
[0, t, 0],
[0, 0, t]])

In [ ]:
A-It

Matrix([
[1 - t,    -1,      4],
[    3, 2 - t,     -1],
[    2,     1, -t - 1]])

In [ ]:
carac = ma-It

matrix([[1 - t, -1, 4],
        [3, 2 - t, -1],
        [2, 1, -t - 1]], dtype=object)

In [ ]:
A[0:,0:]

Matrix([
[1, -1,  4],
[3,  2, -1],
[2,  1, -1]])

In [ ]:
np.prod(mb.diagonal())

-3

In [ ]:
np.prod(mb.diagonal()) - np.prod(np.fliplr(mb).diagonal())

2

In [ ]:
def det(A):
  dim = np.shape(A)
  det = 0
  detf = 0
  factores = []
  if dim[0] == dim[1]:
    if dim[0] == 2:
      det = np.prod(A.diagonal())- np.prod(np.fliplr(A).diagonal())
    else:
      for n in range(dim[0]):
        B = A[n+1:,n+1:]
        factores.append(A[n:,:1])
        if np.shape(B)[0]==2:
          det = np.prod(B.diagonal())- np.prod(np.fliplr(B).diagonal())
          detf += factores


  else:
    raise TypeError("No es una matriz cuadrada")
  return det

In [ ]:
def det2(A):
  dim = np.shape(A)
  if dim[0]==dim[1]==2:
    return np.prod(A.diagonal())- np.prod(np.fliplr(A).diagonal())
  else:
    raise TypeError("Necesito una matrix 2x2")

In [ ]:
prueba = sy.diag(t_,t_)
det2(prueba)

t**2

In [ ]:
A

Matrix([
[1, -1,  4],
[3,  2, -1],
[2,  1, -1]])

In [ ]:
A[0:1,1:2]

Matrix([[-1]])

In [ ]:
def intercambioc(A,i,j):
  A = A.copy()
  b = A[:,i:i+1].copy()
  A[:,i:i+1] = A[:,j:j+1]
  A[:,j:j+1] = b
  return A.copy()

In [ ]:
A

Matrix([
[1, -1,  4],
[3,  2, -1],
[2,  1, -1]])

In [ ]:
intercambioc(A,1,0)

Matrix([
[-1, 1,  4],
[ 2, 3, -1],
[ 1, 2, -1]])

In [ ]:
A

Matrix([
[1, -1,  4],
[3,  2, -1],
[2,  1, -1]])

In [ ]:
def detp(A):
  dim = np.shape(A)
  det = 0
  factores = []
  if dim[0] == dim[1]:
    dim = dim[0]
    if dim == 2:
      return det2(A)
    else:
      for n in range(dim):
        for m in range(dim):
          A = intercambioc(A,n,0)
          B = A[1:,1:].copy()
          if np.shape(B)[0]==2:
            det += ((-1)**(n+m)) * A[0][0] * det2(B)
          else:
            print("hola")

    return det

            # Falta (-1)^n


  else:
    raise TypeError("No es una matriz cuadrada")
  return det

In [ ]:
def submatriz(A):
  return A[1:,1:].copy()

In [ ]:
submatriz(A)

Matrix([
[2, -1],
[1, -1]])

In [ ]:
def det(A):
  dim = np.shape(A)
  det = 0
  factores = []
  if dim[0] == dim[1]:
    dim = dim[0]
    if dim == 2:
      return det2(A)
    else:
      for n in range(dim):
        C = intercambioc(A,n,0)
        B = submatriz(C)
        if np.shape(B)[0]==2:
          display(sy.Matrix(B))
          for m in range(dim):
            det += ((-1)**(n+m+1)) * C[0:1,0:1] * det2(B)

        else:
          print("hola")

    return det

            # Falta (-1)^n


  else:
    raise TypeError("No es una matriz cuadrada")
  return det

In [ ]:
ma

matrix([[ 1, -1,  4],
        [ 3,  2, -1],
        [ 2,  1, -1]])

In [ ]:
ma[1:,1:]

matrix([[ 2, -1],
        [ 1, -1]])

In [ ]:
np.shape(mb)[0] ==2

True

In [ ]:
A.det()

-6

In [ ]:
A

Matrix([
[1, -1,  4],
[3,  2, -1],
[2,  1, -1]])

In [ ]:
det(ma)

Matrix([
[2, -1],
[1, -1]])

Matrix([
[3, -1],
[2, -1]])

Matrix([
[2, 3],
[1, 2]])

matrix([[-2]])

In [ ]:
mb[1:,1:]

matrix([[-1]])

In [ ]:
def polchar(A,t):
  dim = np.shape(A)
  I = np.diag(np.ones(dim[0]))
  m = A-t*I
  return np.linalg.det(m)

In [ ]:
def reduccion(A):
  dim = np.shape(A)
  for m in range(dim[0]):
    for i in range(dim[1]):
      if m != i:
        if A[i][m] != 0 and A[m][m] != 0:
          A[i] = (-1)*(A[i][m]/A[m][m])*A[m]+A[i]
      #print(A[i])
    if A[m][m]!= 0 :
      A[m] = A[m]/A[m][m]
    #if A[m] == np.zeros(dim[1]):
     # A[m:m+1,dim[1]-1:dim[1]] = sy.Symbol("∞")
  return A
