In [153]:
#@title Librerias
import numpy as np
import matplotlib.pyplot as plt
import numpy.linalg as la
import scipy.linalg as sla
from sympy import Matrix

# **Método de Gauss-Jordan**

El método de Gauss-Jordan es una extensión del método de eliminación gaussiana, usado para resolver sistemas de ecuaciones lineales, calcular inversas de matrices, o reducir matrices a su forma escalonada reducida. A diferencia de la eliminación gaussiana, este método elimina no solo los elementos por debajo de la diagonal principal, sino también los elementos por encima de ella, transformando la matriz en una **matriz identidad ampliada**.

---

## **Teoría**

Dado un sistema de ecuaciones lineales $A\mathbf{x} = \mathbf{b}$, donde:

$$
A =
\begin{bmatrix}
a_{11} & a_{12} & \cdots & a_{1n} \\
a_{21} & a_{22} & \cdots & a_{2n} \\
\vdots & \vdots & \ddots & \vdots \\
a_{n1} & a_{n2} & \cdots & a_{nn}
\end{bmatrix}, \quad
\mathbf{b} =
\begin{bmatrix}
b_1 \\
b_2 \\
\vdots \\
b_n
\end{bmatrix},
$$

formamos la **matriz aumentada**:

$$
[A | \mathbf{b}] =
\begin{bmatrix}
a_{11} & a_{12} & \cdots & a_{1n} & b_1 \\
a_{21} & a_{22} & \cdots & a_{2n} & b_2 \\
\vdots & \vdots & \ddots & \vdots & \vdots \\
a_{n1} & a_{n2} & \cdots & a_{nn} & b_n
\end{bmatrix}.
$$

El método de Gauss-Jordan transforma esta matriz aumentada en su forma escalonada reducida:

$$
[I | \mathbf{x}] =
\begin{bmatrix}
1 & 0 & \cdots & 0 & x_1 \\
0 & 1 & \cdots & 0 & x_2 \\
\vdots & \vdots & \ddots & \vdots & \vdots \\
0 & 0 & \cdots & 1 & x_n
\end{bmatrix}.
$$

De esta forma, el vector solución $\mathbf{x}$ puede leerse directamente.

---

### **Pasos del método**

1. **Seleccionar un pivote**: El pivote es un elemento no nulo en la diagonal de la matriz. Si el pivote es cero, intercambiar filas para que el pivote no sea nulo.
2. **Normalizar el pivote**: Dividir toda la fila del pivote por el valor del pivote para que este se convierta en $1$.
3. **Eliminar elementos en la columna del pivote**: Restar múltiplos de la fila pivote de todas las demás filas para hacer ceros en esa columna.
4. **Repetir para cada columna** hasta obtener la forma escalonada reducida.

---

## **Ejemplo**

Resolver el sistema de ecuaciones:


\begin{aligned}
2x + y - z &= 8, \\
-3x - y + 2z &= -11, \\
-2x + y + 2z &= -3.
\end{aligned}

---

### **Paso 1: Formar la matriz aumentada**

$$
[A | \mathbf{b}] =
\begin{bmatrix}
2 & 1 & -1 & 8 \\
-3 & -1 & 2 & -11 \\
-2 & 1 & 2 & -3
\end{bmatrix}.
$$

---

### **Paso 2: Eliminar elementos debajo del pivote $a_{11}$**

1. El pivote inicial es $a_{11} = 2$. Dividimos la primera fila por $2$ para normalizar:

$$
\begin{bmatrix}
1 & 0.5 & -0.5 & 4 \\
-3 & -1 & 2 & -11 \\
-2 & 1 & 2 & -3
\end{bmatrix}.
$$

2. Eliminamos los elementos debajo del pivote en la columna 1:

   - Fila 2: $F_2 \rightarrow F_2 + 3F_1$.
   - Fila 3: $F_3 \rightarrow F_3 + 2F_1$.

$$
\begin{bmatrix}
1 & 0.5 & -0.5 & 4 \\
0 & 0.5 & 0.5 & 1 \\
0 & 2 & 1 & 5
\end{bmatrix}.
$$

---

### **Paso 3: Eliminar elementos encima y debajo del pivote $a_{22}$**

1. El pivote ahora es $a_{22} = 0.5$. Dividimos la segunda fila por $0.5$ para normalizar:

$$
\begin{bmatrix}
1 & 0.5 & -0.5 & 4 \\
0 & 1 & 1 & 2 \\
0 & 2 & 1 & 5
\end{bmatrix}.
$$

2. Eliminamos los elementos encima y debajo del pivote en la columna 2:

   - Fila 1: $F_1 \rightarrow F_1 - 0.5F_2$.
   - Fila 3: $F_3 \rightarrow F_3 - 2F_2$.

$$
\begin{bmatrix}
1 & 0 & -1 & 3 \\
0 & 1 & 1 & 2 \\
0 & 0 & -1 & 1
\end{bmatrix}.
$$

---

### **Paso 4: Eliminar elementos encima del pivote $a_{33}$**

1. El pivote ahora es $a_{33} = -1$. Dividimos la tercera fila por $-1$ para normalizar:

$$
\begin{bmatrix}
1 & 0 & -1 & 3 \\
0 & 1 & 1 & 2 \\
0 & 0 & 1 & -1
\end{bmatrix}.
$$

2. Eliminamos los elementos encima del pivote en la columna 3:

   - Fila 1: $F_1 \rightarrow F_1 + F_3$.
   - Fila 2: $F_2 \rightarrow F_2 - F_3$.

$$
\begin{bmatrix}
1 & 0 & 0 & 2 \\
0 & 1 & 0 & 3 \\
0 & 0 & 1 & -1
\end{bmatrix}.
$$

---

### **Resultado**

La matriz reducida corresponde a:

$$
[I | \mathbf{x}] =
\begin{bmatrix}
1 & 0 & 0 & 2 \\
0 & 1 & 0 & 3 \\
0 & 0 & 1 & -1
\end{bmatrix}.
$$

Por lo tanto, la solución es:

$$
\mathbf{x} =
\begin{bmatrix}
2 \\
3 \\
-1
\end{bmatrix}.
$$

---



In [154]:
A = np.array([[2, 1, -1], [-3, -1, 2], [-2, 1, 2]], dtype = float)
b = np.array([8, -11, -3], dtype = float)

A_augmented = np.c_[A,b]

factor = A[0,0]
A_augmented[0] = A_augmented[0]/factor

factor2 = A_augmented[1,0]
A_augmented[1] -= factor2*A_augmented[0]

factor3 = A_augmented[2,0]
A_augmented[2] -=  factor3*A_augmented[0]
A_augmented

In [155]:
#@title Gauss Jordan
def gauss_jordan(A, b):
    """
    Resuelve el sistema de ecuaciones Ax = b utilizando el método de Gauss-Jordan.

    Parámetros:
    - A: Matriz de coeficientes (numpy array de tamaño n x n).
    - b: Vector de términos independientes (numpy array de tamaño n).

    Retorna:
    - x: Solución del sistema (numpy array de tamaño n).
    """
    n = len(b)
    # Asegurarse de que las matrices son de tipo flotante
    A = np.array(A, dtype=float)
    b = np.array(b, dtype=float)
    # Crear la matriz aumentada usando np.c_
    aug_matrix = np.c_[A, b]

    # El proceso de eliminación de Gauss-Jordan
    for i in range(n):
        # Paso 1: Hacer el pivote igual a 1, dividiendo la fila i por el pivote
        pivot = aug_matrix[i, i]
        if np.abs(pivot) < 1e-12:
            raise ValueError("El pivote es cero o casi cero, el sistema no tiene solución única o es singular.")

        aug_matrix[i] = aug_matrix[i] / pivot

        # Paso 2: Hacer ceros en todos los demás elementos de la columna i
        for j in range(n):
            if j != i:
                factor = aug_matrix[j, i]
                aug_matrix[j] -= factor * aug_matrix[i]

    # La solución está en la última columna de la matriz aumentada
    x = aug_matrix[:, -1]
    return x


In [156]:
A = np.array([[2, 1, -1], [-3, -1, 2], [-2, 1, 2]])
b = np.array([8, -11, -3])

x = gauss_jordan(A, b)
print("Solución del sistema:")
print(x)


Solución del sistema:
[ 2.  3. -1.]


In [157]:
# Comprobación
la.solve(A, b)

array([ 2.,  3., -1.])

In [160]:
# Matriz aumentada sympy
A_aug = Matrix([
    [2, 1, -1, 8],
    [-3, -1, 2, -11],
    [-2, 1, 2, -3]
])

# Reducir a forma escalonada reducida
rref, pivots = A_aug.rref()
display(rref)


Matrix([
[1, 0, 0,  2],
[0, 1, 0,  3],
[0, 0, 1, -1]])

# **Factorización LU**

La factorización LU es un método utilizado en álgebra lineal para descomponer una matriz cuadrada $A$ en el producto de dos matrices: una matriz triangular inferior $L$ (Lower) y una matriz triangular superior $U$ (Upper), tal que:

$$
A = LU
$$

Donde:

- **$L$** es una matriz triangular inferior con elementos diagonales iguales a $1$ (en general, pero no necesariamente).
- **$U$** es una matriz triangular superior.

Esta factorización se utiliza frecuentemente para resolver sistemas de ecuaciones lineales, calcular determinantes o encontrar inversas de matrices.

---

Dado un sistema de ecuaciones lineales de la forma:

$$
A\mathbf{x} = \mathbf{b},
$$

la factorización LU permite reescribir el sistema como:

$$
LU\mathbf{x} = \mathbf{b}.
$$

Definiendo $\mathbf{y}$ como un vector intermedio, tenemos:

1. Resolver primero el sistema triangular inferior:
   $$
   L\mathbf{y} = \mathbf{b}.
   $$

2. Resolver después el sistema triangular superior:
   $$
   U\mathbf{x} = \mathbf{y}.
   $$

De esta forma, el proceso de resolución del sistema es más eficiente, ya que la resolución de sistemas triangulares es computacionalmente más sencilla.

---

## **Condiciones para la Factorización LU**

1. La matriz $A$ debe ser cuadrada.
2. $A$ debe ser no singular (es decir, $\det(A) \neq 0$).
3. En algunos casos, puede ser necesario realizar una **permutación de filas** para evitar dividir por cero. Esto lleva a una factorización llamada **PA = LU**, donde $P$ es una matriz de permutación.

---

### **Algoritmo de factorización LU**

Dado $A \in \mathbb{R}^{n \times n}$:

1. Inicializar $L = I_n$ (matriz identidad) y $U = A$.
2. Para cada paso $k = 1, 2, \dots, n-1$:
   - Calcular los multiplicadores $l_{ik} = u_{ik} / u_{kk}$ para $i > k$.
   - Actualizar las filas de $U$ usando:
$$ u_{ij}  \leftarrow u_{ij} - l_{ik}u_{kj}, \quad \forall j \geq k.$$
   - Almacenar $l_{ik}$ en $L$.

3. Al finalizar, $L$ contendrá los multiplicadores y $U$ será la matriz triangular superior resultante.
---

## **Ejemplo**

Dada la matriz:

$$
A =
\begin{bmatrix}
2 & 3 & 1 \\
4 & 7 & 3 \\
6 & 18 & 5
\end{bmatrix},
$$

queremos encontrar $L$ y $U$ tal que $A = LU$.

### **Paso 1: Forma de las matrices**

- $L$ será:
  $$
  L =
  \begin{bmatrix}
  1 & 0 & 0 \\
  l_{21} & 1 & 0 \\
  l_{31} & l_{32} & 1
  \end{bmatrix}.
  $$

- $U$ será:
  $$
  U =
  \begin{bmatrix}
  u_{11} & u_{12} & u_{13} \\
  0 & u_{22} & u_{23} \\
  0 & 0 & u_{33}
  \end{bmatrix}.
  $$

### **Paso 2: Proceso de eliminación**

1. El primer elemento pivote es $u_{11} = 2$. Calculamos $l_{21}$ y $l_{31}$ dividiendo los elementos de la primera columna entre $u_{11}$:
   $$
   l_{21} = \frac{4}{2} = 2, \quad l_{31} = \frac{6}{2} = 3.
   $$

2. Sustituimos estos valores y eliminamos las entradas por debajo de $u_{11}$ en la matriz $A$.

3. Para la segunda columna, $u_{22}$ se calcula como el pivote de la submatriz restante. Continuamos el proceso hasta completar las matrices $L$ y $U$.

### **Resultado**

Después del procedimiento, obtenemos:

$$
L =
\begin{bmatrix}
1 & 0 & 0 \\
2 & 1 & 0 \\
3 & 9 & 1
\end{bmatrix},
\quad
U =
\begin{bmatrix}
2 & 3 & 1 \\
0 & 1 & 1 \\
0 & 0 & -7
\end{bmatrix}.
$$

Verificamos que $LU = A$:

$$
\begin{bmatrix}
1 & 0 & 0 \\
2 & 1 & 0 \\
3 & 9 & 1
\end{bmatrix}
\begin{bmatrix}
2 & 3 & 1 \\
0 & 1 & 1 \\
0 & 0 & -7
\end{bmatrix}
=
\begin{bmatrix}
2 & 3 & 1 \\
4 & 7 & 3 \\
6 & 18 & 5
\end{bmatrix}.
$$




In [162]:
#@title Factorización LU
def factorizacion_lu(A):
    A = A.astype(float)  # Aseguramos que los cálculos sean en punto flotante
    n = len(A)
    L = np.eye(n)  # Matriz identidad
    U = np.copy(A)

    for k in range(n - 1):
        if U[k, k] == 0:
            raise ValueError("El método no funciona si hay ceros en la diagonal de U sin pivoteo.")
        for j in range(k + 1, n):
            L[j, k] = U[j, k] / U[k, k]
            U[j, k:] = U[j, k:] - L[j, k] * U[k, k:]

    return L, U

In [163]:
A = np.array([[2, 3, 1], [4, 7, 3], [6, 18, 5]])
L, U = factorizacion_lu(A)

print("Matriz L:")
print(L)
print("\nMatriz U:")
print(U)

print("\nVerificación: LU = A")
print(np.dot(L, U))


Matriz L:
[[1. 0. 0.]
 [2. 1. 0.]
 [3. 9. 1.]]

Matriz U:
[[ 2.  3.  1.]
 [ 0.  1.  1.]
 [ 0.  0. -7.]]

Verificación: LU = A
[[ 2.  3.  1.]
 [ 4.  7.  3.]
 [ 6. 18.  5.]]


In [164]:
import scipy.linalg as sla

In [165]:
A = np.array([[2, 3, 1],
              [4, 7, 3],
              [6, 18, 5]], dtype=float)



P, L , U = sla.lu(A)

print("L:")
print(L)
print("\nU:")
print(U)
print("\nP:")
print(P)

L:
[[1.         0.         0.        ]
 [0.66666667 1.         0.        ]
 [0.33333333 0.6        1.        ]]

U:
[[ 6.         18.          5.        ]
 [ 0.         -5.         -0.33333333]
 [ 0.          0.         -0.46666667]]

P:
[[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]]


In [167]:
# Comparación
np.isclose(np.dot(L,U) , np.dot(P,A))


array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

# Matriz de Permutación en la Factorización LU con Pivoteo Parcial

La **matriz de permutación** es una herramienta utilizada en el proceso de factorización LU con pivoteo parcial. Esta matriz permite reordenar las filas de una matriz para garantizar que el pivote (elemento de la diagonal principal) sea el mayor en valor absoluto en cada paso del proceso. Esto mejora la estabilidad numérica y evita divisiones por números pequeños o cero.

## Representación General

En la factorización LU con pivoteo parcial, una matriz $ A $ se descompone como:

$$
PA = LU,
$$

donde:
- $ P $: Matriz de permutación (permuta filas de $ A $).
- $ L $: Matriz triangular inferior.
- $ U $: Matriz triangular superior.

---

## Construcción de la Matriz de Permutación

1. **Inicializar $ P $:**
   La matriz $ P $ comienza como la matriz identidad de tamaño $ n \times n $:
   $$
   P = I = \begin{pmatrix}
   1 & 0 & 0 \\
   0 & 1 & 0 \\
   0 & 0 & 1
   \end{pmatrix}.
   $$

2. **Pivoteo parcial:**
   Durante la eliminación Gaussiana, identifica el elemento con mayor valor absoluto en la columna actual (dentro de las filas restantes). Si el mayor pivote no está en la fila actual, intercambia las filas correspondientes en $ A $ y en $ P $.

3. **Actualizar $ P $:**
   Por cada intercambio de filas en $ A $, actualiza $ P $ para reflejar la misma permutación.

---

## Ejemplo Práctico

Sea la matriz $ A $:

$$
A = \begin{pmatrix}
0 & 2 & 3 \\
4 & 5 & 6 \\
7 & 8 & 9
\end{pmatrix}.
$$

### **Paso 1: Inicializar $ P $**
Inicialmente, $ P $ es la matriz identidad:

$$
P = \begin{pmatrix}
1 & 0 & 0 \\
0 & 1 & 0 \\
0 & 0 & 1
\end{pmatrix}.
$$

### **Paso 2: Pivoteo en la primera columna**

El mayor elemento en valor absoluto de la primera columna es $ 7 $ (fila 3). Intercambiamos la fila 1 con la fila 3 en $ A $, y actualizamos $ P $:

$$
P = \begin{pmatrix}
0 & 0 & 1 \\
0 & 1 & 0 \\
1 & 0 & 0
\end{pmatrix}.
$$

La nueva matriz $ PA $ es:

$$
PA = \begin{pmatrix}
7 & 8 & 9 \\
4 & 5 & 6 \\
0 & 2 & 3
\end{pmatrix}.
$$

### **Paso 3: Pivoteo en la segunda columna**

En la segunda columna, el mayor elemento en valor absoluto es $ 5 $ (fila 2). No se requiere un intercambio adicional, por lo que $ P $ permanece igual.

---

## Resultado Final

La matriz de permutación $ P $ resultante es:

$$
P = \begin{pmatrix}
0 & 0 & 1 \\
0 & 1 & 0 \\
1 & 0 & 0
\end{pmatrix}.
$$

Esto significa que las filas de la matriz original $ A $ se han reordenado en el siguiente orden: fila 3, fila 2 y fila 1. Esta reordenación garantiza que los pivotes sean los mayores en valor absoluto en cada paso del proceso.

---

## Propiedades de la Matriz de Permutación

1. **Ortogonalidad:**
   La matriz $ P $ es ortogonal, es decir:
   $$
   P^T P = I.
   $$

2. **Determinante:**
   El determinante de $ P $ es siempre $ \pm 1 $, dependiendo del número de intercambios de filas realizados.

3. **Uso en Sistemas:**
   Una vez calculada $ P $, se utiliza para modificar $ A $ como $ PA $ y luego proceder con la factorización $ LU $.

---

## Ventajas del Pivoteo con $ P $

1. **Mayor estabilidad numérica:**
   Garantiza que los pivotes sean lo suficientemente grandes, reduciendo errores de redondeo.

2. **Simplicidad computacional:**
   La matriz $ P $ es fácil de construir y no aumenta significativamente el costo computacional del método.

3. **Aplicaciones prácticas:**
   Es esencial para resolver sistemas lineales de manera confiable, calcular determinantes o inversas con métodos numéricos robustos.



In [168]:
A  = np.array([
    [0, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

P, L, U = sla.lu(A, permute_l = False)

print("Matriz P:")
print(P)
print("\nMatriz L:")
print(L)
print("\nMatriz U:")
print(U)

Matriz P:
[[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]

Matriz L:
[[1.         0.         0.        ]
 [0.         1.         0.        ]
 [0.57142857 0.21428571 1.        ]]

Matriz U:
[[7.         8.         9.        ]
 [0.         2.         3.        ]
 [0.         0.         0.21428571]]


# Factorización LU: Aplicaciones en Determinantes e Inversas


### Cálculo del determinante
El determinante de $ A $ se calcula eficientemente con:

$$
\det(A) = \det(L) \cdot \det(U).
$$

Dado que $ \det(L) = 1 $, esto simplifica a:

$$
\det(A) = \prod_{i=1}^n u_{ii},
$$

es decir, el producto de los elementos diagonales de $ U $.

### 2. Inversa de una matriz
La inversa de una matriz $ A $ se calcula resolviendo:

$$
A A^{-1} = I.
$$

Si $ A = LU $, esto se convierte en dos pasos:
1. Resolver $ LZ = I $ (donde $ Z = U A^{-1} $).
2. Resolver $ U A^{-1} = Z $.

Ambos sistemas triangulares son computacionalmente eficientes ($ O(n^2) $).

---

### Ejemplo: Matriz $ A $
Dada la matriz:

$$
A =
\begin{bmatrix}
2 & 3 & 1 \\
4 & 7 & 3 \\
6 & 18 & 5
\end{bmatrix},
$$

#### Factorización LU:
$$
L =
\begin{bmatrix}
1 & 0 & 0 \\
2 & 1 & 0 \\
3 & 9 & 1
\end{bmatrix},
\quad
U =
\begin{bmatrix}
2 & 3 & 1 \\
0 & 1 & 1 \\
0 & 0 & -7
\end{bmatrix}.
$$

#### Determinante:
El determinante de $ A $ es:

$$
\det(A) = \prod_{i=1}^n u_{ii} = 2 \cdot (1) \cdot (-7) = -14.
$$



In [169]:
def determinante(A):
    L, U = factorizacion_lu(A)
    det = np.prod(np.diag(U))
    return det

In [175]:
A = np.array([
    [2, 3, 1],
    [4, 7, 3],
    [6, 18, 5]
], dtype=float)

det_A = determinante(A)
det_A_ = la.det(A)

np.isclose(det_A, det_A_)

True

La inversa de $ A $ se obtiene resolviendo el sistema matricial:

$$
A A^{-1} = I,
$$

donde $ I $ es la matriz identidad. Si $ A = LU $, se puede reescribir como:

$$
LU A^{-1} = I.
$$

Esto implica que debemos resolver dos sistemas de ecuaciones:

1. Resolver $ LZ = I $ para $ Z $, donde $ Z = U A^{-1} $.
2. Resolver $ U A^{-1} = Z $ para $ A^{-1} $.

### **Resolución paso a paso**

1. **Resolver $ LZ = I $**:
   Aquí se resuelven $ n $ sistemas triangulares inferiores, uno para cada columna de la matriz identidad. La solución $ Z $ es la matriz intermedia.

2. **Resolver $ U A^{-1} = Z $**:
   Aquí se resuelven $ n $ sistemas triangulares superiores para encontrar las columnas de $ A^{-1} $, utilizando los resultados de $ Z $.

Ambos pasos son eficientes computacionalmente ($ O(n^2) $) y mucho más rápidos que calcular la inversa directamente mediante métodos como cofactors.

---



In [112]:
# Actividad

# Métodos Iterativos: Jacobi y Gauss-Seidel

Los **métodos de Jacobi** y **Gauss-Seidel** son técnicas iterativas para resolver sistemas de ecuaciones lineales de la forma:

$$
Ax = b,
$$

donde:
- $ A $ es una matriz cuadrada de tamaño $ n \times n $,
- $ x $ es el vector incógnita,
- $ b $ es el vector de términos independientes.

---

## **Método de Jacobi**

El método de Jacobi reescribe el sistema $ Ax = b $ descomponiendo la matriz $ A $ como:

$$
A = D + L + U,
$$

donde:
- $ D $: Matriz diagonal de $ A $,
- $ L $: Matriz triangular inferior sin la diagonal,
- $ U $: Matriz triangular superior sin la diagonal.

El sistema se reorganiza como:

$$
x = D^{-1}(b - (L + U)x).
$$

Esto se implementa iterativamente como:

$$
x_i^{(k+1)} = \frac{1}{a_{ii}} \left(b_i - \sum_{j \neq i} a_{ij} x_j^{(k)}\right),
$$

donde $ a_{ii} $ son los elementos diagonales de $ A $.

---




In [131]:
#@title Jacobi
def jacobi(A, b, tol=1e-10, max_iter=1000):
    # Inicializar el vector de solución con ceros
    x = np.zeros_like(b)

    # Descomponer A en D, L y U
    D = np.diag(np.diag(A))  # Matriz diagonal
    L = np.tril(A, -1)       # Matriz triangular inferior (sin diagonal)
    U = np.triu(A, 1)        # Matriz triangular superior (sin diagonal)

    # Iteración de Jacobi
    for k in range(max_iter):
        x_new = np.copy(x)

        for i in range(len(A)):
            # La fórmula de Jacobi
            sum_terms = np.dot(A[i, :], x) - A[i, i] * x[i]
            x_new[i] = (b[i] - sum_terms) / A[i, i]

        # Comprobar la convergencia
        if np.linalg.norm(x_new - x, ord=np.inf) < tol:
            print(f"Converged after {k+1} iterations")
            return x_new

        x = x_new

    print("Max iterations reached")
    return x

In [178]:
A = np.array([
    [4, -1, 0, 0],
    [-1, 4, -1, 0],
    [0, -1, 4, -1],
    [0, 0, -1, 3]
], dtype=float)

b = np.array([15, 10, 10, 10], dtype=float)

# Resolver el sistema usando Jacobi
sol = jacobi(A, b)
print("La solución es:", sol)

Converged after 30 iterations
La solución es: [5. 5. 5. 5.]


In [179]:
la.solve(A, b)

array([5., 5., 5., 5.])

## **Método de Gauss-Seidel**

El método de Gauss-Seidel mejora a Jacobi al actualizar los valores de $ x $ en cada iteración tan pronto como están disponibles. En lugar de usar únicamente valores de la iteración anterior ($ k $), usa los valores recién calculados ($ k+1 $).

El sistema $ Ax = b $ se descompone como:

$$
(L + D)x = b - Ux,
$$

y se reescribe iterativamente como:

$$
x_i^{(k+1)} = \frac{1}{a_{ii}} \left(b_i - \sum_{j < i} a_{ij} x_j^{(k+1)} - \sum_{j > i} a_{ij} x_j^{(k)}\right).
$$

Aquí:
- Se usan los valores actualizados $ x_j^{(k+1)} $ para $ j < i $.
- Se usan los valores anteriores $ x_j^{(k)} $ para $ j > i $.

---

## **Ejemplo Práctico: Gauss-Seidel**

Resolver el sistema:

$$
\begin{aligned}
4x_1 - x_2 + x_3 &= 7, \\
-2x_1 + 6x_2 + x_3 &= 9, \\
x_1 + x_2 + 5x_3 &= -6.
\end{aligned}
$$

### Paso 1: Matriz $ A $ y vector $ b $

La matriz $ A $ y el vector $ b $ son:

$$
A = \begin{pmatrix}
4 & -1 & 1 \\
-2 & 6 & 1 \\
1 & 1 & 5
\end{pmatrix}, \quad
b = \begin{pmatrix}
7 \\ 9 \\ -6
\end{pmatrix}.
$$

### Paso 2: Inicialización

Comenzamos con una suposición inicial, $ x^{(0)} = \begin{pmatrix} 0 & 0 & 0 \end{pmatrix}^T $.

### Paso 3: Iteraciones usando Gauss-Seidel

Utilizamos las siguientes fórmulas:

1. Para $ x_1 $:
   $$
   x_1^{(k+1)} = \frac{1}{4} \left(7 + x_2^{(k)} - x_3^{(k)}\right).
   $$
2. Para $ x_2 $:
   $$
   x_2^{(k+1)} = \frac{1}{6} \left(9 + 2x_1^{(k+1)} - x_3^{(k)}\right).
   $$
3. Para $ x_3 $:
   $$
   x_3^{(k+1)} = \frac{1}{5} \left(-6 - x_1^{(k+1)} - x_2^{(k+1)}\right).
   $$

**Iteración 1:**
Con $ x^{(0)} = \begin{pmatrix} 0 & 0 & 0 \end{pmatrix}^T $:
1. $ x_1^{(1)} = \frac{1}{4}(7 + 0 - 0) = 1.75 $,
2. $ x_2^{(1)} = \frac{1}{6}(9 + 2(1.75) - 0) = 2 $,
3. $ x_3^{(1)} = \frac{1}{5}(-6 - 1.75 - 2) = -1.55 $.

Entonces, $ x^{(1)} = \begin{pmatrix} 1.75 & 2 & -1.55 \end{pmatrix}^T $.

**Iteración 2:**
Con $ x^{(1)} $:
1. $ x_1^{(2)} = \frac{1}{4}(7 + 2 - (-1.55)) = 1.885 $,
2. $ x_2^{(2)} = \frac{1}{6}(9 + 2(1.885) - (-1.55)) = 2.218 $,
3. $ x_3^{(2)} = \frac{1}{5}(-6 - 1.885 - 2.218) = -1.6206 $.

Entonces, $ x^{(2)} = \begin{pmatrix} 1.885 & 2.218 & -1.6206 \end{pmatrix}^T $.

### Paso 4: Iterar hasta converger

Repetimos las iteraciones hasta que la norma de la diferencia entre dos iteraciones consecutivas sea menor a una tolerancia:

$$
\|x^{(k+1)} - x^{(k)}\| < \text{tolerancia}.
$$

---

## **Diferencias entre Jacobi y Gauss-Seidel**

| **Aspecto**           | **Jacobi**                                           | **Gauss-Seidel**                                      |
|------------------------|-----------------------------------------------------|-----------------------------------------------------|
| **Cálculo de $ x^{(k+1)} $** | Usa valores de $ x^{(k)} $ para todos los componentes.  | Usa los valores más recientes disponibles.          |
| **Convergencia**       | Más lento, pero más simple de implementar.          | Converge más rápido en la mayoría de los casos.     |
| **Dependencia**        | Totalmente paralelizable (no hay dependencia entre los cálculos). | Dependencias entre cálculos debido a las actualizaciones inmediatas. |

---

## **Criterios de Convergencia**

Ambos métodos convergen si:
1. $ A $ es diagonalmente dominante:
   $$
   |a_{ii}| > \sum_{j \neq i} |a_{ij}|, \quad \forall i.
   $$
2. $ A $ es **simétrica definida positiva**.

---

In [180]:
#@title Gauss - Seidel
def gauss_seidel(A, b, tol=1e-10, max_iter=1000):
    # Inicializar el vector de solución con ceros
    x = np.zeros_like(b)

    # Iteración de Gauss-Seidel
    for k in range(max_iter):
        x_new = np.copy(x)

        for i in range(len(A)):
            # La fórmula de Gauss-Seidel
            sum_terms = np.dot(A[i, :], x_new) - A[i, i] * x_new[i]
            x_new[i] = (b[i] - sum_terms) / A[i, i]

        # Comprobar la convergencia
        if np.linalg.norm(x_new - x, ord=np.inf) < tol:
            print(f"Converged after {k+1} iterations")
            return x_new

        x = x_new

    print("Max iterations reached")
    return x

In [181]:
A = np.array([
    [4, -1, 0, 0],
    [-1, 4, -1, 0],
    [0, -1, 4, -1],
    [0, 0, -1, 3]
], dtype=float)

b = np.array([15, 10, 10, 10], dtype=float)

# Resolver el sistema usando Jacobi
sol = gauss_seidel(A, b)
print("La solución es:", sol)

Converged after 17 iterations
La solución es: [5. 5. 5. 5.]
