In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as la

# Actividad 08: Algebra Lineal y Matrices

---
### Profesor: Juan Marcos Marín
### Nombre: Carolina Pabón Rúa
*Métodos computacionales 2024-II*

---

#1

Escriba una función que calcule el producto escalar y vectorial para dos vectores, compare sus resultados con `np.dot` y `np.cross`.

In [ ]:
import numpy as np

def producto_escalar_vectorial(v1, v2):
    """
    Calcula el producto escalar y el producto vectorial de dos vectores.
    Compara los resultados con np.dot y np.cross.

    Parámetros:
    v1, v2: listas o arrays de longitud 3

    Retorna:
    Un diccionario con los resultados.
    """
    # Producto escalar manual
    prod_escalar_manual = sum(a * b for a, b in zip(v1, v2))
    prod_escalar_numpy = np.dot(v1, v2)

    # Producto vectorial manual
    prod_vectorial_manual = [
        v1[1] * v2[2] - v1[2] * v2[1],
        v1[2] * v2[0] - v1[0] * v2[2],
        v1[0] * v2[1] - v1[1] * v2[0]
    ]
    prod_vectorial_numpy = np.cross(v1, v2)

    return {
        "Producto escalar manual": prod_escalar_manual,
        "Producto escalar numpy": prod_escalar_numpy,
        "Producto vectorial manual": prod_vectorial_manual,
        "Producto vectorial numpy": prod_vectorial_numpy.tolist()
    }

# Ejemplo de uso
v1 = [1, 2, 3]
v2 = [4, 5, 6]
resultado = producto_escalar_vectorial(v1, v2)

print("Ejemplo de producto escalar:")
print(f"Manual: {resultado['Producto escalar manual']}, Numpy: {resultado['Producto escalar numpy']}")

print("\nEjemplo de producto vectorial:")
print(f"Manual: {resultado['Producto vectorial manual']}, Numpy: {resultado['Producto vectorial numpy']}")

Ejemplo de producto escalar:
Manual: 32, Numpy: 32

Ejemplo de producto vectorial:
Manual: [-3, 6, -3], Numpy: [-3, 6, -3]


#2

Crear una función llamada `mulmat()` donde a partir de dos matrices $A$ y $B$ encuentre su multplicación. También realiza una función que calcule la transpuesta y otra el determinante de una matriz $3\times 3$. Compare sus resultado con `@`, `np.dot`, `transpose` y `la.det`.

In [ ]:
import numpy as np

def mulmat(A, B):
    """Multiplica dos matrices A y B."""
    if len(A[0]) != len(B):
        raise ValueError("El número de columnas de A debe ser igual al número de filas de B")

    filas_A, cols_B = len(A), len(B[0])
    resultado = [[sum(A[i][k] * B[k][j] for k in range(len(B))) for j in range(cols_B)] for i in range(filas_A)]
    return resultado

def transpuesta(A):
    """Calcula la transpuesta de una matriz A."""
    return [[A[j][i] for j in range(len(A))] for i in range(len(A[0]))]

def determinante_3x3(A):
    """Calcula el determinante de una matriz 3x3."""
    if len(A) != 3 or len(A[0]) != 3:
        raise ValueError("La matriz debe ser de 3x3")

    return (A[0][0] * (A[1][1] * A[2][2] - A[1][2] * A[2][1]) -
            A[0][1] * (A[1][0] * A[2][2] - A[1][2] * A[2][0]) +
            A[0][2] * (A[1][0] * A[2][1] - A[1][1] * A[2][0]))

# Pruebas con NumPy
A = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
B = [[9, 8, 7], [6, 5, 4], [3, 2, 1]]

# Multiplicación de matrices
print("Multiplicación propia:", mulmat(A, B))
print("Multiplicación con @:", np.array(A) @ np.array(B))
print("Multiplicación con np.dot:", np.dot(A, B))

# Transpuesta
print("Transpuesta propia:", transpuesta(A))
print("Transpuesta con np.transpose:", np.transpose(A))

# Determinante
print("Determinante propio:", determinante_3x3(A))
print("Determinante con np.linalg.det:", np.linalg.det(A))


Multiplicación propia: [[30, 24, 18], [84, 69, 54], [138, 114, 90]]
Multiplicación con @: [[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]
Multiplicación con np.dot: [[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]
Transpuesta propia: [[1, 4, 7], [2, 5, 8], [3, 6, 9]]
Transpuesta con np.transpose: [[1 4 7]
 [2 5 8]
 [3 6 9]]
Determinante propio: 0
Determinante con np.linalg.det: 0.0


#3
Escriba tres matrices aleatorias $A$, $B$ y $C$ de $3\times 3$, y demuestre las siguientes relaciones

- $ \mathbf{A}\mathbf{B} \neq \mathbf{B}\mathbf{A} $, en general.
- $ (\mathbf{A}\mathbf{B})\mathbf{C} = \mathbf{A}(\mathbf{B}\mathbf{C}) $.
- $ \mathbf{A}(\mathbf{B} + \mathbf{C}) = \mathbf{A}\mathbf{B} + \mathbf{A}\mathbf{C} $.
- $ (\mathbf{A} + \mathbf{B})\mathbf{C} = \mathbf{A}\mathbf{C} + \mathbf{B}\mathbf{C} $.
- $ (\mathbf{A}\mathbf{B})^\top = \mathbf{B}^\top \mathbf{A}^\top $.
- $ \det(\mathbf{A}\mathbf{B}) = \det(\mathbf{A}) \det(\mathbf{B}) $.
- $ (\mathbf{A}^\top)^\top = \mathbf{A} $.
- $ (c\mathbf{A})^\top = c\mathbf{A}^\top $.
- $ (\mathbf{A} + \mathbf{B})^\top = \mathbf{A}^\top + \mathbf{B}^\top $.



In [ ]:

np.random.seed(42)

A_ = np.random.randint(1, 10, (3, 3))
B_ = np.random.randint(1, 10, (3, 3))
C_ = np.random.randint(1, 10, (3, 3))

print("Matriz A:\n", A)
print("Matriz B:\n", B)
print("Matriz C:\n", C)


Matriz A:
 [[7 4 8]
 [5 7 3]
 [7 8 5]]
Matriz B:
 [[4 8 8]
 [3 6 5]
 [2 8 6]]
Matriz C:
 [[2 5 1]
 [6 9 1]
 [3 7 4]]


In [ ]:
# AB Distinto BA
x0 = np.dot(A_,B_)
y0 = np.dot(B_,A_)
print(np.array_equal(x0,y0))

False


In [ ]:
#(AB)C = A(BC)
x = np.dot(A_,B_)
y = np.dot(B_,C_)

x1 = np.dot(x,C_)
x2 = np.dot(A_,y)
print(np.array_equal(x1,x2))

True


In [ ]:
# A (B+C)= AB + AC
sum1 = np.add(B_,C_)
x1 = np.dot(A_,sum1)
y1= np.dot(A_,B_)
y2 = np.dot(A_,C_)
y3 = y1 + y2
print(np.array_equal(x1,y3))

True


In [ ]:
# (A+B)C= AC + BC
sum = np.add(A_,B_)
x3 = np.dot(sum,C_)
y4= np.dot(A_,C_)
y0 = np.dot(B_,C_)
y3 = y0 + y4
print(np.array_equal(x3,y3))

True


In [ ]:
xt = np.transpose(np.dot(A_,B_))
xta = np.transpose(A_)
xtb = np.transpose(B_)
z = np.dot(xtb,xta)
print(np.array_equal(xt,z))

True


In [ ]:
# Det(AB)= Det(A)*Det(B)
det = np.linalg.det(np.dot(A_,B_))
deta = np.linalg.det(A_)
detb = np.linalg.det(B_)
det1 = deta*detb
print(det)
print(det1)
print(np.array_equal(det,det1))

22735.999999999945
22735.99999999999
False


In [ ]:
T = np.transpose(np.transpose(A_))
print(np.array_equal(T,A_))

True


In [ ]:
c = 3
T1 = np.transpose(np.dot(c,A_))
T2 = c * np.transpose(A_)
print(np.array_equal(T1,T2))

True


In [ ]:
w = np.transpose(np.add(A_,B_))
w1 = np.transpose(A_)
w2 = np.transpose(B_)
sum0 = np.add(w1,w2)
print(np.array_equal(w,sum0))

True


#4

El **Teorema de Laplace** es un método para calcular el determinante de una matriz cuadrada, particularmente útil para matrices de orden mayor a 2. Este teorema se basa en la expansión del determinante por los elementos de una fila o una columna cualquiera.



$$
\det(A) = \sum_{j=1}^n (-1)^{1+j} a_{1j} M_{1j}
$$

donde:
- $a_{1j}$ es el elemento de la primera fila y columna $j$.
- $M_{1j}$ es el menor asociado al elemento $a_{1j}$, es decir, el determinante de la submatriz de $3 \times 3$ que se obtiene al eliminar la fila 1 y la columna $j$.
- $(-1)^{1+j}$ es el signo correspondiente al cofactor del elemento $a_{1j}$.

Podemos realizar una función recursiva para el cálculo del determinante, sabiendo que el valor del determinante de una matriz de orden uno es el único elemento de esa matriz, y el de una matriz de orden superior a uno es la suma de cada uno de los elementos de una fila o columna por los Adjuntos a ese elemento, como en la función recursiva se emplea la misma función definida el cálculo lo haremos por Menor complementario, un ejemplo desarrollado por la primera fila sería:

$$
   \det (A_{j,j}) =
   \left \{
   \begin{array}{llcl}
      si & j = 1 & \to & a_{1,1} \\
                                 \\
      si & j > 1 & \to & \displaystyle \sum_{k=1}^j \; (-1)^{(1+k)} \cdot a_{1,k} \cdot \det( \alpha_{1,k})
   \end{array}
   \right .
$$

Realice una función que encuentre el determinante de una matriz usando la recursividad aqui planteada, explique explicitamente su código

In [ ]:
def laplace(A):
    n = len(A)
    if n == 1:
        return A[0, 0]
    if n == 2:
        return np.linalg.det(A)
    det = 0
    for j in range(n):
        M_1j = np.array([fila[:j].tolist() + fila[j+1:].tolist() for fila in A[1:]])
        det += (-1) ** j * A[0, j] * laplace(M_1j)

    return det


resultado = laplace(A_)
print("El determinante es:", resultado)


El determinante es: -11.000000000000064


#5

El método de Jacobi reescribe el sistema $ Ax = b $ descomponiendo la matriz $ A $ como:

$$
A = D + L + U,
$$

donde:
- $ D $: Matriz diagonal de $ A $,
- $ L $: Matriz triangular inferior sin la diagonal,
- $ U $: Matriz triangular superior sin la diagonal.

El sistema se reorganiza como:

$$
x = D^{-1}(b - (L + U)x).
$$

Esto se implementa iterativamente como:

$$
x_i^{(k+1)} = \frac{1}{a_{ii}} \left(b_i - \sum_{j \neq i} a_{ij} x_j^{(k)}\right),
$$

donde $ a_{ii} $ son los elementos diagonales de $ A $.

* Escriba una función explicita que realice de manera iterativa este método con una tol = 1e-7 y un máximo de 100 iteraciones. Defina una documentación clara que explique los métodos usados, lasa entradas y salidas.

* Para una matriz aleatoria 5$\times$ 5, encuentre la solución usando su función y determine el error con respecto a `solve` y el método de inversa de matriz.

In [ ]:
import numpy as np

def jacobi(A, b, tol=1e-7, max_iter=100):
    n = A.shape[0]
    x = np.zeros(n)
    D = np.diag(A)
    R = A - np.diagflat(D)

    for k in range(max_iter):
        x_new = (b - np.dot(R, x)) / D

        if np.linalg.norm(x_new - x, ord=np.inf) < tol:
            return x_new, k+1
        x = x_new

    return x, max_iter

np.random.seed(42)
A = np.random.rand(5, 5)
A += 5 * np.eye(5)
b = np.random.rand(5)

x_jacobi, iteraciones = jacobi(A, b)
x_solve = np.linalg.solve(A, b)
x_inv = np.dot(np.linalg.inv(A), b)

error_jacobi_solve = np.linalg.norm(x_jacobi - x_solve)
error_inv_solve = np.linalg.norm(x_inv - x_solve)

print(f"Solución con Jacobi en {iteraciones} iteraciones: {x_jacobi}")
print(f"Error entre Jacobi y solve: {error_jacobi_solve}")
print(f"Error entre inversa y solve: {error_inv_solve}")


Solución con Jacobi en 14 iteraciones: [ 0.12231351  0.0123086   0.08266623  0.09713883 -0.0164666 ]
Error entre Jacobi y solve: 1.5858846951560476e-08
Error entre inversa y solve: 2.000580707114743e-17


#6

Verifique que cualquier matriz hermitiana de 2 × 2 $ L $ puede escribirse como una suma de cuatro términos:

$$ L = a\sigma_x + b\sigma_y + c\sigma_z + dI $$

donde $ a $, $ b $, $ c $ y $ d $ son números reales.

Las cuatro matrices de Pauli son:

$$ \sigma_x = \begin{pmatrix} 0 & 1 \\ 1 & 0 \end{pmatrix}, \quad \sigma_y = \begin{pmatrix} 0 & -i \\ i & 0 \end{pmatrix}, \quad \sigma_z = \begin{pmatrix} 1 & 0 \\ 0 & -1 \end{pmatrix}, \quad I = \begin{pmatrix} 1 & 0 \\ 0 & 1 \end{pmatrix} $$




In [ ]:
import numpy as np

def descomponer_hermitiana(L):
    sigma_x = np.array([[0, 1], [1, 0]])
    sigma_y = np.array([[0, -1j], [1j, 0]])
    sigma_z = np.array([[1, 0], [0, -1]])
    I = np.eye(2)

    a = 0.5 * np.trace(L @ sigma_x)
    b = 0.5 * np.trace(L @ sigma_y)
    c = 0.5 * np.trace(L @ sigma_z)
    d = 0.5 * np.trace(L @ I)

    return a, b, c, d

np.random.seed(42)
L = np.random.rand(2,2) + 1j * np.random.rand(2,2)
L = (L + L.conj().T) / 2

a, b, c, d = descomponer_hermitiana(L)

L_reconstruida = a * np.array([[0, 1], [1, 0]]) + \
                 b * np.array([[0, -1j], [1j, 0]]) + \
                 c * np.array([[1, 0], [0, -1]]) + \
                 d * np.eye(2)

error = np.linalg.norm(L - L_reconstruida)

print(f"Coeficientes: a={a}, b={b}, c={c}, d={d}")
print(f"Error de reconstrucción: {error}")


Coeficientes: a=(0.8413541241106606+0j), b=(-0.04895545408400159+0j), c=(-0.11205918267483705+0j), d=(0.48659930152219955+0j)
Error de reconstrucción: 0.0
