In [1]:
import numpy as np

In [2]:
#Matriz aleatoria M:
M=np.matrix([[2,1,-1,5],[4,1,1,1],[6,2,1,4]])
type(M)
M

matrix([[ 2,  1, -1,  5],
        [ 4,  1,  1,  1],
        [ 6,  2,  1,  4]])

In [3]:
#defino operaciones elementales de Matrices:

# Intercambio en la matriz M, la fila n, por la fila m:
def Intercam(M ,n, m):
  if  m and n < (np.shape(M)[0]):
    B = M.copy()
    B[n] = M[m]
    B[m] = M[n]
    return B
  else:
    print("defnir bien indice de filas")

# Multiplico en la matriz M, la fila i por el numero flotante n:
def Mulescal(M,i,n):
  M = M.astype(float)
  B = M.copy()
  B[i] = M[i]* n
  return B

#Sumo dos filas de la matriz M en este caso, i, j y la suma la mando a una fila k:
def Sumfil(M,i,j,k):
  B = M.copy()
  B[k] = M[i] + M[j]
  return B


In [4]:
#Por medio de  las funciones definidas, reduzco la matriz a su forma Gauss Jordan:
a,b = np.shape(M)

if M[0,0] != 0 and M[0,0] != 1:
  a1=M[0,0]
  B = Mulescal(M,0,1/a1)

  C = B.copy
  b= B[1,0]

  C = Mulescal(B,0,-b)

  B[1] = Sumfil(C, 0, 1,1)[1]

  C = B.copy
  a3 = B[2,0]

  C = Mulescal(B,2,-(1/a3))
  B[2] = Sumfil(C,0,2,2)[2]

  C = B.copy
  a = B[2,1]
  C = Mulescal(B,1,a)
  B[2] = Sumfil(C,1,2,2)[2]

  C = B.copy
  a = B[2,2]
  C = Mulescal(B,2,(1/a))
  B[2] = C[2]

  #Determinando si hay numero negativos en los pivotes:
  for i in range(len(B)):
    if B[i,i] == -1:
      C = B.copy()
      a = B[i,i]
      C = Mulescal(B,i,(a))
      B[i] = C[i]

  print(B)



[[ 1.   0.5 -0.5  2.5]
 [ 0.   1.  -3.   9. ]
 [ 0.   0.   1.  -2. ]]


In [5]:
#Para método Gauss-Jordan, primero defino una función que nos de ceros debajo de los pivotes principales;
#La cual será utilizada luego de obtener 1 en la diagonal con el ciclo realizado:

def ceros(B,j,col):
  a,b = np.shape(B)
  for i in range(j,a):
    if B[i,col] != 0:
      A = B.copy()
      escl2 = -(A[i,col])
      C = Mulescal(A,col, escl2)
      A[i] = Sumfil(C,col,i,i)[i]
      B=A
  return(B)

#definimos la función gaussj, la cual se utiliza para reducir la matriz:
def gaussj(M):
  a,b = np.shape(M)

  #ciclo para tener unos en la diagonal para reeducir:
  for i in range(a):
    if M[i,i] != 0 and M[i,i] != 1:  #Determina si la diagonal es diferente de 0 y 1.
      M = M.astype(float)
      B = M.copy()
      escl = M[i,i]
      C = Mulescal(B,i,(1/escl))   #Utilizamos la función Multiplicar por escalar.
      B[i]  = C[i]                 #Reemplazamos las filas de las matrices.
      A = ceros(B,i+1,i)

      M = A                        #reemplaza el valor de la matriz


  return(ceros(A,i,i-1))           #Debido a la falta de un ciclo, retornamos la última matriz diagonal, encontrando ceros.



In [8]:
#Probando la función:
print('Función inicial: ')
print(M)
print('')
print('Con la función creada tenemos: ')
print(gaussj(M))

Función inicial: 
[[ 2  1 -1  5]
 [ 4  1  1  1]
 [ 6  2  1  4]]

Con la función creada tenemos: 
[[ 1.   0.5 -0.5  2.5]
 [ 0.   1.  -3.   9. ]
 [ 0.   0.   1.  -2. ]]


In [9]:
#Probando con una aleatoria:
N = np.random.randint(0,20,(7,8))
print('La matriz aleatoria es: ')
print(N)
print('')
print('Utilizando gaussj tenemos: ')
print(gaussj(N))

La matriz aleatoria es: 
[[ 4  3 14  9  1 10  3  2]
 [15 16  2  9 16  5 10  5]
 [ 2  2  3 13 11 15  7 16]
 [19 19  1 14 11 14  1 16]
 [ 4 13 10  6  6  8 10  0]
 [18 11  3 17  5 18 13 12]
 [ 7  5  0  3  6 19 17  9]]

Utilizando gaussj tenemos: 
[[ 1.00000000e+00  7.50000000e-01  3.50000000e+00  2.25000000e+00
   2.50000000e-01  2.50000000e+00  7.50000000e-01  5.00000000e-01]
 [ 0.00000000e+00  1.00000000e+00 -1.06315789e+01 -5.21052632e+00
   2.57894737e+00 -6.84210526e+00 -2.63157895e-01 -5.26315789e-01]
 [ 0.00000000e+00  0.00000000e+00  1.00000000e+00  8.44000000e+00
   7.00000000e+00  1.02000000e+01  4.28000000e+00  1.16000000e+01]
 [ 0.00000000e+00  0.00000000e+00 -1.44890444e-17  1.00000000e+00
   8.07504078e-01  1.23980424e+00  4.25774878e-01  1.49265905e+00]
 [-0.00000000e+00 -0.00000000e+00 -3.03819946e-17 -0.00000000e+00
   1.00000000e+00 -4.10230049e-01  1.02742160e+00 -4.04369854e-01]
 [-0.00000000e+00 -0.00000000e+00  1.56581275e-14 -0.00000000e+00
  -0.00000000e+00  1.0000