In [1]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as la

# Actividad 08: Algebra Lineal y Matrices

---
### Profesor: Juan Marcos Marín
### Nombre: Ross Anthony Miranda D'Angelo
*Métodos computacionales 2024-II*

---

#1

Escriba una función que calcule el producto escalar y vectorial para dos vectores, compare sus resultados con `np.dot` y `np.cross`.

In [2]:
def productos_vectores(v1, v2):
    # Producto escalar manual
    escalar_manual = sum(a * b for a, b in zip(v1, v2))
    escalar_np = np.dot(v1, v2)

    # Producto vectorial manual (solo para vectores 3D)
    vectorial_manual = [
        v1[1] * v2[2] - v1[2] * v2[1],
        v1[2] * v2[0] - v1[0] * v2[2],
        v1[0] * v2[1] - v1[1] * v2[0]
    ] if len(v1) == 3 and len(v2) == 3 else "Solo para vectores 3D"

    vectorial_np = np.cross(v1, v2) if len(v1) == 3 and len(v2) == 3 else "Solo para vectores 3D"

    return {
        "Producto escalar manual": escalar_manual,
        "Producto escalar np.dot": escalar_np,
        "Producto vectorial manual": vectorial_manual,
        "Producto vectorial np.cross": vectorial_np
    }

# Ej
v1 = [1, 2, 3]
v2 = [4, 5, 6]
resultados = productos_vectores(v1, v2)

for key, value in resultados.items():
    print(f"{key}: {value}")


Producto escalar manual: 32
Producto escalar np.dot: 32
Producto vectorial manual: [-3, 6, -3]
Producto vectorial np.cross: [-3  6 -3]


In [3]:
def productos_vectores(v1, v2):
    # Producto escalar para cualquier dimensión
    escalar_manual = sum(a * b for a, b in zip(v1, v2))
    escalar_np = np.dot(v1, v2)

    # Producto vectorial (solo definido para dimensiones 2 y 3)
    if len(v1) == len(v2) and len(v1) in [2, 3]:
        vectorial_np = np.cross(v1, v2)
        if len(v1) == 2:
            # Producto vectorial en 2D se representa como un escalar (z)
            vectorial_manual = v1[0] * v2[1] - v1[1] * v2[0]
        else:
            # Producto vectorial en 3D
            vectorial_manual = [
                v1[1] * v2[2] - v1[2] * v2[1],
                v1[2] * v2[0] - v1[0] * v2[2],
                v1[0] * v2[1] - v1[1] * v2[0]
            ]
    else:
        vectorial_manual = "No definido"
        vectorial_np = "No definido para +3D"

    return {
        "Producto escalar manual": escalar_manual,
        "Producto escalar np.dot": escalar_np,
        "Producto vectorial manual": vectorial_manual,
        "Producto vectorial np.cross": vectorial_np
    }

# Ej
v1 = [1, 2, 3, 4, 5]  # Hay que ir probando
v2 = [4, 5, 6, 7, 8]
resultados = productos_vectores(v1, v2)

for key, value in resultados.items():
    print(f"{key}: {value}")


Producto escalar manual: 100
Producto escalar np.dot: 100
Producto vectorial manual: No definido
Producto vectorial np.cross: No definido para +3D


#2

Crear una función llamada `mulmat()` donde a partir de dos matrices $A$ y $B$ encuentre su multplicación. También realiza una función que calcule la transpuesta y otra el determinante de una matriz $3\times 3$. Compare sus resultado con `@`, `np.dot`, `transpose` y `la.det`.

In [4]:

from pprint import pprint #por fines esteticos

# Función mult mat
def mulmat(A, B):
    filas_A, cols_A = len(A), len(A[0])
    filas_B, cols_B = len(B), len(B[0])

    if cols_A != filas_B:
        raise ValueError("Las dimensiones de las matrices no permiten la multiplicación.")

    # Multi. MANUAL
    resultado_manual = [[sum(A[i][k] * B[k][j] for k in range(cols_A)) for j in range(cols_B)] for i in range(filas_A)]

    # Usando ahora numpy
    resultado_np_dot = np.dot(A, B).tolist()
    resultado_arroba = (np.array(A) @ np.array(B)).tolist()

    return {
        "Multiplicación manual": resultado_manual,
        "Multiplicación np.dot": resultado_np_dot,
        "Multiplicación @": resultado_arroba
    }

# Función transpuesta
def transpuesta(M):
    transpuesta_manual = [[M[j][i] for j in range(len(M))] for i in range(len(M[0]))]
    transpuesta_np = np.transpose(M).tolist()

    return {
        "Transpuesta manual": transpuesta_manual,
        "Transpuesta np.transpose": transpuesta_np
    }

# Función det de una matriz 3x3
def determinante_3x3(M):
    if len(M) != 3 or len(M[0]) != 3:
        raise ValueError("La matriz debe ser de 3x3 para calcular el determinante.")

    #(regla de Sarrus)
    det_manual = (M[0][0] * M[1][1] * M[2][2] + M[0][1] * M[1][2] * M[2][0] + M[0][2] * M[1][0] * M[2][1]) - \
                 (M[0][2] * M[1][1] * M[2][0] + M[0][0] * M[1][2] * M[2][1] + M[0][1] * M[1][0] * M[2][2])

    # Usando numpy
    det_np = float(np.linalg.det(M))  # Convertimos a float para mayor claridad

    return {
        "Determinante manual": det_manual,
        "Determinante np.linalg.det": det_np
    }

# Ej...
A = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
B = [[9, 8, 7], [6, 5, 4], [3, 2, 1]]

print("Resultado de la multiplicación de matrices:")
pprint(mulmat(A, B))

print("\nResultado de la transpuesta:")
pprint(transpuesta(A))

print("\nResultado del determinante:")
pprint(determinante_3x3(A))


Resultado de la multiplicación de matrices:
{'Multiplicación @': [[30, 24, 18], [84, 69, 54], [138, 114, 90]],
 'Multiplicación manual': [[30, 24, 18], [84, 69, 54], [138, 114, 90]],
 'Multiplicación np.dot': [[30, 24, 18], [84, 69, 54], [138, 114, 90]]}

Resultado de la transpuesta:
{'Transpuesta manual': [[1, 4, 7], [2, 5, 8], [3, 6, 9]],
 'Transpuesta np.transpose': [[1, 4, 7], [2, 5, 8], [3, 6, 9]]}

Resultado del determinante:
{'Determinante manual': 0, 'Determinante np.linalg.det': 0.0}


#3
Escriba tres matrices aleatorias $A$, $B$ y $C$ de $3\times 3$, y demuestre las siguientes relaciones

- $ \mathbf{A}\mathbf{B} \neq \mathbf{B}\mathbf{A} $, en general.
- $ (\mathbf{A}\mathbf{B})\mathbf{C} = \mathbf{A}(\mathbf{B}\mathbf{C}) $.
- $ \mathbf{A}(\mathbf{B} + \mathbf{C}) = \mathbf{A}\mathbf{B} + \mathbf{A}\mathbf{C} $.
- $ (\mathbf{A} + \mathbf{B})\mathbf{C} = \mathbf{A}\mathbf{C} + \mathbf{B}\mathbf{C} $.
- $ (\mathbf{A}\mathbf{B})^\top = \mathbf{B}^\top \mathbf{A}^\top $.
- $ \det(\mathbf{A}\mathbf{B}) = \det(\mathbf{A}) \det(\mathbf{B}) $.
- $ (\mathbf{A}^\top)^\top = \mathbf{A} $.
- $ (c\mathbf{A})^\top = c\mathbf{A}^\top $.
- $ (\mathbf{A} + \mathbf{B})^\top = \mathbf{A}^\top + \mathbf{B}^\top $.



In [10]:
#matrices aleatorias de 3x3
np.random.seed(42)  # Fijar semilla para reproducibilidad
A = np.random.randint(-10, 10, (3, 3))
B = np.random.randint(-10, 10, (3, 3))
C = np.random.randint(-10, 10, (3, 3))
c = 5  # Escalar arbitrario, puede ser cambiado, y recomiendo ir probando por favor

# Verificar propiedades PUNTO POR PUNTO
print("Matrices generadas:")
print("A:\n", A)
print("B:\n", B)
print("C:\n", C)

# 1. AB ≠ BA, en general.
print("\nAB ≠ BA, en general:")
print("AB:\n", A @ B)
print("BA:\n", B @ A)

# 2. (AB)C = A(BC)
print("\n(AB)C == A(BC):", np.allclose((A @ B) @ C, A @ (B @ C)))

# 3. A(B + C) = AB + AC
print("\nA(B + C) == AB + AC:", np.allclose(A @ (B + C), (A @ B) + (A @ C)))

# 4. (A + B)C = AC + BC
print("\n(A + B)C == AC + BC:", np.allclose((A + B) @ C, (A @ C) + (B @ C)))

# 5. (AB)^T = B^T A^T
print("\n(AB)^T == B^T A^T:", np.allclose((A @ B).T, B.T @ A.T))

# 6. det(AB) = det(A) det(B)
print("\ndet(AB) == det(A) * det(B):", np.isclose(np.linalg.det(A @ B), np.linalg.det(A) * np.linalg.det(B)))

# 7. (A^T)^T = A
print("\n(A^T)^T == A:", np.allclose(A.T.T, A))

# 8. (cA)^T = c A^T
print("\n(cA)^T == c A^T:", np.allclose((c * A).T, c * A.T))

# 9. (A + B)^T = A^T + B^T
print("\n(A + B)^T == A^T + B^T:", np.allclose((A + B).T, A.T + B.T))


Matrices generadas:
A:
 [[-4  9  4]
 [ 0 -3 -4]
 [ 8  0  0]]
B:
 [[ -7  -3  -8]
 [ -9   1  -5]
 [ -9 -10   1]]
C:
 [[ 1  6 -1]
 [ 5  4  4]
 [ 8  1  9]]

AB ≠ BA, en general:
AB:
 [[-89 -19  -9]
 [ 63  37  11]
 [-56 -24 -64]]
BA:
 [[-36 -54 -16]
 [ -4 -84 -40]
 [ 44 -51   4]]

(AB)C == A(BC): True

A(B + C) == AB + AC: True

(A + B)C == AC + BC: True

(AB)^T == B^T A^T: True

det(AB) == det(A) * det(B): True

(A^T)^T == A: True

(cA)^T == c A^T: True

(A + B)^T == A^T + B^T: True


#4

El **Teorema de Laplace** es un método para calcular el determinante de una matriz cuadrada, particularmente útil para matrices de orden mayor a 2. Este teorema se basa en la expansión del determinante por los elementos de una fila o una columna cualquiera.



$$
\det(A) = \sum_{j=1}^n (-1)^{1+j} a_{1j} M_{1j}
$$

donde:
- $a_{1j}$ es el elemento de la primera fila y columna $j$.
- $M_{1j}$ es el menor asociado al elemento $a_{1j}$, es decir, el determinante de la submatriz de $3 \times 3$ que se obtiene al eliminar la fila 1 y la columna $j$.
- $(-1)^{1+j}$ es el signo correspondiente al cofactor del elemento $a_{1j}$.

Podemos realizar una función recursiva para el cálculo del determinante, sabiendo que el valor del determinante de una matriz de orden uno es el único elemento de esa matriz, y el de una matriz de orden superior a uno es la suma de cada uno de los elementos de una fila o columna por los Adjuntos a ese elemento, como en la función recursiva se emplea la misma función definida el cálculo lo haremos por Menor complementario, un ejemplo desarrollado por la primera fila sería:

$$
   \det (A_{j,j}) =
   \left \{
   \begin{array}{llcl}
      si & j = 1 & \to & a_{1,1} \\
                                 \\
      si & j > 1 & \to & \displaystyle \sum_{k=1}^j \; (-1)^{(1+k)} \cdot a_{1,k} \cdot \det( \alpha_{1,k})
   \end{array}
   \right .
$$

Realice una función que encuentre el determinante de una matriz usando la recursividad aqui planteada, explique explicitamente su código

In [6]:
import numpy as np

def determinante_laplace(A):
    # Caso 1: si la matriz es 1x1, el determinante es el único elemento que hay
    if A.shape == (1, 1):
        return A[0, 0]

    # Caso 2: determinante de una matriz 2x2
    if A.shape == (2, 2):
        return A[0, 0] * A[1, 1] - A[0, 1] * A[1, 0]

    #Ahora algo general

    # Expansión de Laplace por la primera fila
    det = 0
    n = A.shape[0]
    for j in range(n):
        # Menor asociado a A[0, j]: se elimina la fila 0 y columna j
        menor = np.delete(np.delete(A, 0, axis=0), j, axis=1)
        cofactor = (-1) ** (j) * A[0, j] * determinante_laplace(menor)
        det += cofactor

    return det

# Ejemplo de uso
A = np.array([[3, 0, -1],
              [2, -3, 2],
              [1, 4, 5]])

print("Determinante de A:", determinante_laplace(A))


Determinante de A: -80


Se elige la primera fila para la expansión de Laplace.
Se calcula cada menor eliminando la fila 0 y la columna correspondiente.
Se aplica recursividad hasta llegar a
1×1.
Se suma cada cofactor ponderado con
(−1)
^[1+j]
 .


#5

El método de Jacobi reescribe el sistema $ Ax = b $ descomponiendo la matriz $ A $ como:

$$
A = D + L + U,
$$

donde:
- $ D $: Matriz diagonal de $ A $,
- $ L $: Matriz triangular inferior sin la diagonal,
- $ U $: Matriz triangular superior sin la diagonal.

El sistema se reorganiza como:

$$
x = D^{-1}(b - (L + U)x).
$$

Esto se implementa iterativamente como:

$$
x_i^{(k+1)} = \frac{1}{a_{ii}} \left(b_i - \sum_{j \neq i} a_{ij} x_j^{(k)}\right),
$$

donde $ a_{ii} $ son los elementos diagonales de $ A $.

* Escriba una función explicita que realice de manera iterativa este método con una tol = 1e-7 y un máximo de 100 iteraciones. Defina una documentación clara que explique los métodos usados, lasa entradas y salidas.

* Para una matriz aleatoria 5$\times$ 5, encuentre la solución usando su función y determine el error con respecto a `solve` y el método de inversa de matriz.

In [7]:
def jacobi(A, b, tol=1e-7, max_iter=100):
    """
    Resuelve Ax = b usando Jacobi.

    Parámetros:
    - A: Matriz de coeficientes (debe ser cuadrada y diagonalmente dominante).
    - b: Vector de términos independientes.
    - tol: Tolerancia para la convergencia.
    - max_iter: Número máximo de iteraciones.

    Retorna:
    - x: Aproximación de la solución del sistema.
    - iteraciones: Número de iteraciones realizadas.
    """
    n = len(A)
    x = np.zeros(n)  # Aproximación inicial (vector de ceros)
    x_nuevo = np.copy(x)

    for k in range(max_iter):
        for i in range(n):
            suma = sum(A[i, j] * x[j] for j in range(n) if j != i)
            x_nuevo[i] = (b[i] - suma) / A[i, i]

        # Verificar criterio de convergencia
        if np.linalg.norm(x_nuevo - x, ord=np.inf) < tol:
            return x_nuevo, k + 1  # Retorna solución y número de iteraciones

        x = np.copy(x_nuevo)

    return x, max_iter  # Retorna la mejor aproximación si no converge

# Generación de una matriz aleatoria 5x5 diagonalmente dominante
np.random.seed(42)
A = np.random.randint(1, 10, (5, 5)).astype(float)
np.fill_diagonal(A, np.sum(np.abs(A), axis=1) + 1)  # Asegura dominancia diagonal

b = np.random.randint(1, 10, 5).astype(float)

# Jacobi
x_jacobi, iteraciones = jacobi(A, b)
print("Solución con Jacobi:", x_jacobi)
print("Iteraciones:", iteraciones)

# Comparación con métodos exactos*
x_solve = np.linalg.solve(A, b)  # Solución exacta con NumPy
x_inv = np.dot(np.linalg.inv(A), b)  # Solución usando la inversa

# Cálculo del error
error_solve = np.linalg.norm(x_jacobi - x_solve, ord=np.inf)
error_inv = np.linalg.norm(x_jacobi - x_inv, ord=np.inf)

print("\n Sol. solve:", x_solve)
print(" Sol. inversa:", x_inv)

print("\n Error con solve:", error_solve)
print("Error con inversa:", error_inv)


Solución con Jacobi: [0.12779292 0.04479416 0.22242231 0.01818415 0.12302184]
Iteraciones: 69

 Sol. solve: [0.12779288 0.04479412 0.22242227 0.01818411 0.1230218 ]
 Sol. inversa: [0.12779288 0.04479412 0.22242227 0.01818411 0.1230218 ]

 Error con solve: 3.963644674975786e-08
Error con inversa: 3.963644672200228e-08


#6

Verifique que cualquier matriz hermitiana de 2 × 2 $ L $ puede escribirse como una suma de cuatro términos:

$$ L = a\sigma_x + b\sigma_y + c\sigma_z + dI $$

donde $ a $, $ b $, $ c $ y $ d $ son números reales.

Las cuatro matrices de Pauli son:

$$ \sigma_x = \begin{pmatrix} 0 & 1 \\ 1 & 0 \end{pmatrix}, \quad \sigma_y = \begin{pmatrix} 0 & -i \\ i & 0 \end{pmatrix}, \quad \sigma_z = \begin{pmatrix} 1 & 0 \\ 0 & -1 \end{pmatrix}, \quad I = \begin{pmatrix} 1 & 0 \\ 0 & 1 \end{pmatrix} $$




In [8]:
# mat de Pauli y la identidad
sigma_x = np.array([[0, 1], [1, 0]], dtype=complex)
sigma_y = np.array([[0, -1j], [1j, 0]], dtype=complex)
sigma_z = np.array([[1, 0], [0, -1]], dtype=complex)
I = np.array([[1, 0], [0, 1]], dtype=complex)

# Def matriz hermitiana general
a, b, c, d = 2, -1, 3, 4  # Coeficientes reales
L = a * sigma_x + b * sigma_y + c * sigma_z + d * I

print("Matriz L generada:")
print(L)

# Comprobamos que es hermitiana ya que seria (L = L^H)
es_hermitiana = np.allclose(L, L.conj().T)
print("\n¿L es hermitiana?", es_hermitiana)

# Verificamos que cualquier matriz hermitiana se puede escribir en esta forma
# Separamos los coeficientes a partir de L
a_calc = 0.5 * np.trace(L @ sigma_x)
b_calc = 0.5 * np.trace(L @ sigma_y)
c_calc = 0.5 * np.trace(L @ sigma_z)
d_calc = 0.5 * np.trace(L @ I)

print("\nCoeficientes calculados:")
print(f"a = {a_calc}, b = {b_calc}, c = {c_calc}, d = {d_calc}")

# Reconstruimos L a partir de los coeficientes y verificamos si es igual a la original
L_reconstruida = a_calc * sigma_x + b_calc * sigma_y + c_calc * sigma_z + d_calc * I
es_correcta = np.allclose(L, L_reconstruida)

print("\n¿La matriz reconstruida es igual a L?", es_correcta)


Matriz L generada:
[[7.+0.j 2.+1.j]
 [2.-1.j 1.+0.j]]

¿L es hermitiana? True

Coeficientes calculados:
a = (2+0j), b = (-1+0j), c = (3+0j), d = (4+0j)

¿La matriz reconstruida es igual a L? True
