<a href="https://colab.research.google.com/github/Elizajr/CursoMetodosComputacionales/blob/main/Reducci%C3%B3n_gauss_Jordan.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import sympy as sy
import pylab as plt
from numpy import linalg

In [ ]:
ejemplo = np.matrix([[2,1, 1],
                     [4,1, 1],
                     [6,2, 1]])
resultado = np.array([5,1,4]).reshape((3,1))
resultado

array([[5],
       [1],
       [4]])

In [ ]:
np.linalg.solve(ejemplo,resultado)

array([[-2.],
       [ 7.],
       [ 2.]])

In [ ]:
-2*ejemplo[:1,:]

matrix([[-4, -2, -2]])

In [ ]:
reducida = np.zeros((3,4))
reducida[:,:3] = ejemplo
reducida[:,3:] = resultado
reducida

array([[2., 1., 1., 5.],
       [4., 1., 1., 1.],
       [6., 2., 1., 4.]])

In [ ]:
reducida

array([[ 2.,  1.,  1.,  5.],
       [ 0., -1., -1., -9.],
       [ 0.,  0., -1., -2.]])

In [ ]:
reducida[1]=-2*reducida[0]+reducida[1]
# 2 ya que 4/2=2 *-1 para restarla


In [ ]:
# 6/2 = 3
reducida[2] = -3*reducida[0]+reducida[2]

In [ ]:
# -1/-1 = 1
reducida[2] = -1*reducida[1]+reducida[2]

In [ ]:
# Como a_{3,3} = 1 ya tenemos una solución

In [ ]:
# Operaciones elementales de fila
A = []
for i in range(3):
  for m in range(3):
    r = "a_{"+str(i+1)+str(m+1)+"}"
    A.append(sy.Symbol(r))
  A.append(sy.Symbol("r_{"+str(i+1)+"}"))


In [ ]:
A = np.array(A).reshape(3,4)
B = sy.Matrix(A)
B

Matrix([
[a_{11}, a_{12}, a_{13}, r_{1}],
[a_{21}, a_{22}, a_{23}, r_{2}],
[a_{31}, a_{32}, a_{33}, r_{3}]])

In [ ]:
B[0:1,0:]

Matrix([[a_{11}, a_{12}, a_{13}, r_{1}]])

In [ ]:
A[1]

array([a_{21}, a_{22}, a_{23}, r_{2}], dtype=object)

In [ ]:
B[1:2,:]

Matrix([[a_{21}, a_{22}, a_{23}, r_{2}]])

In [ ]:
#(-B[1:2,:1]/B[:1,:1])*B[0:1,0:]+B[1:2,:]

In [ ]:
A[1]=(-A[1][0]/A[0][0])*A[0]+A[1]

In [ ]:
A[2] = (-A[2][0]/A[0][0])*A[0]+A[2]

In [ ]:
A[2] = (-A[2][1]/A[1][1])*A[1]+A[2]

In [ ]:
sy.Matrix(A)

Matrix([
[a_{11},                        a_{12},                                                                                                                           a_{13},                                                                                                                        r_{1}],
[     0, a_{22} - a_{12}*a_{21}/a_{11},                                                                                                    a_{23} - a_{13}*a_{21}/a_{11},                                                                                                  r_{2} - a_{21}*r_{1}/a_{11}],
[     0,                             0, a_{33} + (a_{23} - a_{13}*a_{21}/a_{11})*(-a_{32} + a_{12}*a_{31}/a_{11})/(a_{22} - a_{12}*a_{21}/a_{11}) - a_{13}*a_{31}/a_{11}, r_{3} + (-a_{32} + a_{12}*a_{31}/a_{11})*(r_{2} - a_{21}*r_{1}/a_{11})/(a_{22} - a_{12}*a_{21}/a_{11}) - a_{31}*r_{1}/a_{11}]])

In [ ]:
np.shape(A)

(3, 4)

# Mi función <3

In [ ]:
def reduccion(A):
  dim = np.shape(A)
  for m in range(dim[0]):
    for i in range(dim[1]-1):
      if m != i:
        if A[i][m] != 0 and A[m][m] != 0:
          A[i] = (-A[i][m]/A[m][m])*A[m]+A[i]
      #print(A[i])
    if A[m][m]!= 0 :
      A[m] = A[m]/A[m][m]
  return A[:,dim[1]-1:]


In [ ]:
sy.Matrix(reduccion(A))

Matrix([
[1, 0, 0, (-a_{12}*(r_{2} - a_{21}*r_{1}/a_{11})/(a_{22} - a_{12}*a_{21}/a_{11}) + r_{1} + (a_{12}*(a_{23} - a_{13}*a_{21}/a_{11})/(a_{22} - a_{12}*a_{21}/a_{11}) - a_{13})*(r_{3} + (-a_{32} + a_{12}*a_{31}/a_{11})*(r_{2} - a_{21}*r_{1}/a_{11})/(a_{22} - a_{12}*a_{21}/a_{11}) - a_{31}*r_{1}/a_{11})/(a_{33} + (a_{23} - a_{13}*a_{21}/a_{11})*(-a_{32} + a_{12}*a_{31}/a_{11})/(a_{22} - a_{12}*a_{21}/a_{11}) - a_{13}*a_{31}/a_{11}))/a_{11}],
[0, 1, 0,                                                                           (r_{2} + (-a_{23} + a_{13}*a_{21}/a_{11})*(r_{3} + (-a_{32} + a_{12}*a_{31}/a_{11})*(r_{2} - a_{21}*r_{1}/a_{11})/(a_{22} - a_{12}*a_{21}/a_{11}) - a_{31}*r_{1}/a_{11})/(a_{33} + (a_{23} - a_{13}*a_{21}/a_{11})*(-a_{32} + a_{12}*a_{31}/a_{11})/(a_{22} - a_{12}*a_{21}/a_{11}) - a_{13}*a_{31}/a_{11}) - a_{21}*r_{1}/a_{11})/(a_{22} - a_{12}*a_{21}/a_{11})],
[0, 0, 1,                                                                                                    

In [ ]:
sy.Matrix(reduccion(reducida))
# Falta que los cosos sean 1

Matrix([
[-2.0],
[ 7.0],
[ 2.0]])

In [ ]:
sy.Matrix(A)

Matrix([
[1, 0, 0, (-a_{12}*(r_{2} - a_{21}*r_{1}/a_{11})/(a_{22} - a_{12}*a_{21}/a_{11}) + r_{1} + (a_{12}*(a_{23} - a_{13}*a_{21}/a_{11})/(a_{22} - a_{12}*a_{21}/a_{11}) - a_{13})*(r_{3} + (-a_{32} + a_{12}*a_{31}/a_{11})*(r_{2} - a_{21}*r_{1}/a_{11})/(a_{22} - a_{12}*a_{21}/a_{11}) - a_{31}*r_{1}/a_{11})/(a_{33} + (a_{23} - a_{13}*a_{21}/a_{11})*(-a_{32} + a_{12}*a_{31}/a_{11})/(a_{22} - a_{12}*a_{21}/a_{11}) - a_{13}*a_{31}/a_{11}))/a_{11}],
[0, 1, 0,                                                                           (r_{2} + (-a_{23} + a_{13}*a_{21}/a_{11})*(r_{3} + (-a_{32} + a_{12}*a_{31}/a_{11})*(r_{2} - a_{21}*r_{1}/a_{11})/(a_{22} - a_{12}*a_{21}/a_{11}) - a_{31}*r_{1}/a_{11})/(a_{33} + (a_{23} - a_{13}*a_{21}/a_{11})*(-a_{32} + a_{12}*a_{31}/a_{11})/(a_{22} - a_{12}*a_{21}/a_{11}) - a_{13}*a_{31}/a_{11}) - a_{21}*r_{1}/a_{11})/(a_{22} - a_{12}*a_{21}/a_{11})],
[0, 0, 1,                                                                                                    

In [ ]:
sy.Matrix(reduccion(A))

Matrix([
[(-a_{12}*(r_{2} - a_{21}*r_{1}/a_{11})/(a_{22} - a_{12}*a_{21}/a_{11}) + r_{1} + (a_{12}*(a_{23} - a_{13}*a_{21}/a_{11})/(a_{22} - a_{12}*a_{21}/a_{11}) - a_{13})*(r_{3} + (-a_{32} + a_{12}*a_{31}/a_{11})*(r_{2} - a_{21}*r_{1}/a_{11})/(a_{22} - a_{12}*a_{21}/a_{11}) - a_{31}*r_{1}/a_{11})/(a_{33} + (a_{23} - a_{13}*a_{21}/a_{11})*(-a_{32} + a_{12}*a_{31}/a_{11})/(a_{22} - a_{12}*a_{21}/a_{11}) - a_{13}*a_{31}/a_{11}))/a_{11}],
[                                                                          (r_{2} + (-a_{23} + a_{13}*a_{21}/a_{11})*(r_{3} + (-a_{32} + a_{12}*a_{31}/a_{11})*(r_{2} - a_{21}*r_{1}/a_{11})/(a_{22} - a_{12}*a_{21}/a_{11}) - a_{31}*r_{1}/a_{11})/(a_{33} + (a_{23} - a_{13}*a_{21}/a_{11})*(-a_{32} + a_{12}*a_{31}/a_{11})/(a_{22} - a_{12}*a_{21}/a_{11}) - a_{13}*a_{31}/a_{11}) - a_{21}*r_{1}/a_{11})/(a_{22} - a_{12}*a_{21}/a_{11})],
[                                                                                                                              

In [ ]:
prueba = []
for i in range(4):
  for m in range(4):
    r = "a_{"+str(i+1)+str(m+1)+"}"
    prueba.append(sy.Symbol(r))
  prueba.append(sy.Symbol("r_{"+str(i+1)+"}"))
prueba = np.array(prueba).reshape(4,5)

In [ ]:
sy.Matrix(prueba)

Matrix([
[a_{11}, a_{12}, a_{13}, a_{14}, r_{1}],
[a_{21}, a_{22}, a_{23}, a_{24}, r_{2}],
[a_{31}, a_{32}, a_{33}, a_{34}, r_{3}],
[a_{41}, a_{42}, a_{43}, a_{44}, r_{4}]])

In [ ]:
sy.Matrix(reduccion(prueba))

Matrix([
[(a_{12}*(a_{23} - a_{13}*a_{21}/a_{11})/(a_{11}*(a_{22} - a_{12}*a_{21}/a_{11})) - a_{13}/a_{11})*(r_{3} + (-a_{32} + a_{12}*a_{31}/a_{11})*(r_{2} - a_{21}*r_{1}/a_{11})/(a_{22} - a_{12}*a_{21}/a_{11}) - a_{31}*r_{1}/a_{11})/(a_{33} + (a_{23} - a_{13}*a_{21}/a_{11})*(-a_{32} + a_{12}*a_{31}/a_{11})/(a_{22} - a_{12}*a_{21}/a_{11}) - a_{13}*a_{31}/a_{11}) + (-(a_{12}*(a_{23} - a_{13}*a_{21}/a_{11})/(a_{11}*(a_{22} - a_{12}*a_{21}/a_{11})) - a_{13}/a_{11})*(a_{34} + (a_{24} - a_{14}*a_{21}/a_{11})*(-a_{32} + a_{12}*a_{31}/a_{11})/(a_{22} - a_{12}*a_{21}/a_{11}) - a_{14}*a_{31}/a_{11})/(a_{33} + (a_{23} - a_{13}*a_{21}/a_{11})*(-a_{32} + a_{12}*a_{31}/a_{11})/(a_{22} - a_{12}*a_{21}/a_{11}) - a_{13}*a_{31}/a_{11}) + a_{12}*(a_{24} - a_{14}*a_{21}/a_{11})/(a_{11}*(a_{22} - a_{12}*a_{21}/a_{11})) - a_{14}/a_{11})*(r_{4} + (-a_{43} - (a_{23} - a_{13}*a_{21}/a_{11})*(-a_{42} + a_{12}*a_{41}/a_{11})/(a_{22} - a_{12}*a_{21}/a_{11}) + a_{13}*a_{41}/a_{11})*(r_{3} + (-a_{32} + a_{12}*a_{

In [ ]:
prueba2 = np.random.randint(20,size=(4,5))
sy.Matrix(reduccion(prueba2))

Matrix([
[ 1],
[ 0],
[-1],
[ 2]])