In [3]:
import numpy as np
import matplotlib.pyplot as plt

### Vamos a diseñar un programa que multiplique matrices

In [4]:
#@title Realizaremos la multiplicación manual de 2 matrices de dimensión 2 × 2

matriz_1 = np.array([[1, 2], [3, 4]])
matriz_2 = np.array([[1, 2], [3, 4]])

#verificar que si se pueden multiplicar

dim_1 = np.shape(matriz_1)
dim_2 = np.shape(matriz_2)
print(dim_1, dim_2)

if dim_1[1] == dim_2[0]:
  print(f"la matriz será de {dim_1[0], dim_2[1]}")
else:
  print("las matrices no pueden ser multiplicadas")


(2, 2) (2, 2)
la matriz será de (2, 2)


In [5]:
#@title Vamos a construir el código vectorizado, utilizando arreglos numéricos

#creamos una matriz de zeros para modificarla
matriz_multiplicada = np.zeros((dim_1[0], dim_2[1]))
matriz_multiplicada

array([[0., 0.],
       [0., 0.]])

In [6]:
#@title Realizamos las operaciones manualmente para generalizarlo después

matriz_multiplicada[0][0] = matriz_1[0][0] * matriz_2[0][0] + matriz_1[0][1] * matriz_2[1][0]
matriz_multiplicada[0][1] = matriz_1[0][0] * matriz_2[0][1] + matriz_1[0][1] * matriz_2[1][1]
matriz_multiplicada[1][0] = matriz_1[1][0] * matriz_2[0][0] + matriz_1[1][1] * matriz_2[1][0]
matriz_multiplicada[1][1] = matriz_1[1][0] * matriz_2[0][1] + matriz_1[1][1] * matriz_2[1][1]

In [7]:
matriz_multiplicada

array([[ 7., 10.],
       [15., 22.]])

In [8]:
np.matmul(matriz_1, matriz_2)                                                   #verificamos que la multiplicación es correcta

array([[ 7, 10],
       [15, 22]])

In [26]:
matriz_1[0]

array([1, 2])

In [19]:
matriz_2[:,0]

array([1, 3])

In [31]:
from numpy.matrixlib.defmatrix import matrix
#@title Ahora vamos a generalizar el código

def multiplicacion_matrices(A, B):
  elemento = 0
  for i in range(0, dim_1[0]):
    for k in range(0, dim_2[1]):
      a  = A[i]
      print(a)
      b = B[:,k]
      print(b)
      matriz_multiplicada = a * b
      print(matriz_multiplicada)
      elemento = elemento + matriz_multiplicada
      print(elemento)

  return elemento

multiplicacion_matrices(matriz_1, matriz_2)

[1 2]
[1 3]
[1 6]
[1 6]
[1 2]
[2 4]
[2 8]
[ 3 14]
[3 4]
[1 3]
[ 3 12]
[ 6 26]
[3 4]
[2 4]
[ 6 16]
[12 42]


array([12, 42])