In [185]:
import numpy as np
import sympy as sp
from numpy import linalg

In [186]:
#@title Encontraremos la solución de esta matriz por medio de eliminación gaussiana
A = np.matrix([[2, 1, -1, 5], [4, 1, 1, 1], [6, 2, 1, 4]]).astype(float)
A

matrix([[ 2.,  1., -1.,  5.],
        [ 4.,  1.,  1.,  1.],
        [ 6.,  2.,  1.,  4.]])

In [187]:
np.shape(A)

(3, 4)

In [188]:
type(A)

numpy.matrix

In [189]:
sp.Matrix(A)

Matrix([
[2.0, 1.0, -1.0, 5.0],
[4.0, 1.0,  1.0, 1.0],
[6.0, 2.0,  1.0, 4.0]])

In [190]:
#@title Realizaremos un programa que nos permita realizar eliminación gaussiana a la matriz A

#definimos primero las operaciones elementales de fila

def multiplicacion_por_escalar(a, A, i):
  B = A.copy()
  B[i] = a * A[i]
  return B

B = multiplicacion_por_escalar(-2, A, 0)
sp.Matrix(B)

Matrix([
[-4.0, -2.0, 2.0, -10.0],
[ 4.0,  1.0, 1.0,   1.0],
[ 6.0,  2.0, 1.0,   4.0]])

In [191]:
def intercambio_de_filas(A, i, j):
  C = A.copy()
  C[i] = A[j]
  C[j] = A[i]
  return C

C = intercambio_de_filas(B, 1, 0)
sp.Matrix(C)


Matrix([
[ 4.0,  1.0, 1.0,   1.0],
[-4.0, -2.0, 2.0, -10.0],
[ 6.0,  2.0, 1.0,   4.0]])

In [192]:
def suma_de_filas(A, i, j, k): #matriz, i + j, a la que va
  D = A.copy()
  D[k] = A[i] + A[j]
  return D

D = suma_de_filas(C, 0, 1, 1)
sp.Matrix(D)

Matrix([
[4.0,  1.0, 1.0,  1.0],
[  0, -1.0, 3.0, -9.0],
[6.0,  2.0, 1.0,  4.0]])

In [193]:
MATRIZ = multiplicacion_por_escalar(1/3, D, 1)
MATRIZ1 = suma_de_filas(MATRIZ, 1, 0, 0)
MATRIZ2 = multiplicacion_por_escalar(1/4, MATRIZ1, 0)
MATRIZ3 = multiplicacion_por_escalar(-6, MATRIZ2, 0)
MATRIZ4 = suma_de_filas(MATRIZ3, 0, 2, 2)
MATRIZ5 = multiplicacion_por_escalar(2, MATRIZ4, 1)
MATRIZ6 = suma_de_filas(MATRIZ5, 1, 2, 2)
MATRIZ7 = multiplicacion_por_escalar(-1/6, MATRIZ6, 0)
MATRIZ8 = multiplicacion_por_escalar(-1/2, MATRIZ7, 1)
sp.Matrix(MATRIZ8)

Matrix([
[1.0, 0.166666666666667,  0.5, -0.5],
[  0, 0.333333333333333, -1.0,  3.0],
[  0, 0.333333333333333,    0,  1.0]])

In [220]:
#@title  Ahora vamos a generalizar el problema para una matriz $3 × 3$

#definimos una matriz arbitraria 3 × 3, con el vector solución

G = np.matrix([[2, 2, 3, 1], [-1, 2, 1, 2], [4, -1, 1, 3]]).astype(float)
G

matrix([[ 2.,  2.,  3.,  1.],
        [-1.,  2.,  1.,  2.],
        [ 4., -1.,  1.,  3.]])

In [221]:
sp.Matrix(G)

Matrix([
[ 2.0,  2.0, 3.0, 1.0],
[-1.0,  2.0, 1.0, 2.0],
[ 4.0, -1.0, 1.0, 3.0]])

In [222]:
np.shape(G)

(3, 4)

In [223]:
G[0]/G[0, 0]

matrix([[1. , 1. , 1.5, 0.5]])

In [224]:
if (G[0,0] == 0):
  G = intercambio_de_filas(G, 0, 1)
if (G[0,0] != 1):
  print(G[0,0], "soy el primer termino")
  G[0] = G[0] / G[0,0]
  print(G[0], "otro")

2.0 soy el primer termino
[[1.  1.  1.5 0.5]] otro


In [225]:
sp.Matrix(G)

Matrix([
[ 1.0,  1.0, 1.5, 0.5],
[-1.0,  2.0, 1.0, 2.0],
[ 4.0, -1.0, 1.0, 3.0]])