In [1]:
import numpy as np
import matplotlib.pyplot as plt
import scipy as sc
import scipy.linalg as la

## Funciones fundamentales del notenook:

In [41]:
def matriz_aleatoria(m,n):
    M = np.array([[np.random.randint(1,10) for i in range(m)] for j in range(n)])
    return M

# Actividad 08: Algebra Lineal y Matrices

---
### Profesor: Juan Marcos Marín
### Nombre: Gabriel Rodríguez Suárez
*Métodos computacionales 2024-II*

---

# 1

Escriba una función que calcule el producto escalar y vectorial para dos vectores, compare sus resultados con `np.dot` y `np.cross`.

## **Producto punto**

In [3]:
def dot(v,u):
  if len(v) == len(u):
    suma = 0
    n = len(u)
    for i in range(n):
      suma += v[i]*u[i]
    return suma
  else:
    print('Asegúrate de ingresar vectores de igual dimensión.')

In [4]:
v = np.array([2,2,3])
u = np.array([3,4,5])

punto1 = dot(v,u)
print(f'Por función creada: {punto1}')

punto2 = np.dot(u,v)
print(f'Por función de numpy: {punto2}')

Por función creada: 29
Por función de numpy: 29


## **Producto cruz**

In [5]:
def cruz(v,u):
    if len(u) == 3 and len(v) == 3:
        prod_cruz = np.array([(v[1]*u[2]-v[2]*u[1]), - (v[0]*u[2] - v[2]*u[0]), (v[0]*u[1] - v[1]*u[0])])
        return prod_cruz
    else:
        print('Tus elementos deben ser vectores y si lo son deben ser únicamente de 3 elementos.')

In [6]:
a = np.array([1,2,3])
b = np.array([4,1,2])
cruz1 = cruz(a,b)
print(f'Producto cruz por función: {cruz1}')

cruz2 = np.cross(a,b)
print(f'Producto cruz por numpy: {cruz2}')

Producto cruz por función: [ 1 10 -7]
Producto cruz por numpy: [ 1 10 -7]


# 2

Crear una función llamada `mulmat()` donde a partir de dos matrices $A$ y $B$ encuentre su multplicación. También realiza una función que calcule la transpuesta y otra el determinante de una matriz $3\times 3$. Compare sus resultado con `@`, `np.dot`, `transpose` y `la.det`.

## Función del producto matricial:

In [7]:
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
B = np.array([[1,4,3],[4,5,2],[0,8,9],[2,2,2]])
np.shape(A) == np.shape(B)
np.zeros((np.shape(A)[0], np.shape(B)[0]))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [8]:
def multmat(A,B):
    m, n1 = np.shape(A)[0], np.shape(A)[1]
    n2, p = np.shape(B)[0], np.shape(B)[1]
    print(m,n1,n2,p)
    if n1 == n2:
        C = np.zeros((m,p))
        for i in range(m):
            for j in range(p):
                c = 0
                for k in range(n2):
                    c += A[i,k]*B[k,j]
                    C[i,j] = c
        return C

In [9]:
A = np.array([[1,2,3],[4,5,6]])
B = np.array([[1,4,3],[4,2,4],[0,8,9]])


#print(np.shape(A))
#print(np.shape(B))
#print(A,B)

print(multmat(A,B))
print(A@B)

2 3 3 3
[[ 9. 32. 38.]
 [24. 74. 86.]]
[[ 9 32 38]
 [24 74 86]]


## Función de matriz transpuesta:

In [10]:
def transpuesta(A):
    m, n = np.shape(A)[0], np.shape(A)[1]
    C = np.zeros((n,m))
    for i in range(m):
        for j in range(n):
            C[j,i] = A[i,j]
    return C

In [11]:
A = matriz_aleatoria(3,3)
print(A)

print('Transpuesta por función:')
trans1 = transpuesta(A)
print(trans1)

print('Transpuesta por numpy:')
trans2 = np.transpose(A)
print(trans2)

NameError: name 'matriz_aleatoria' is not defined

## Determinante 3x3:

In [ ]:
def det_2(A):
    if np.shape(A) == (2,2):
        det_A = A[0,0]*A[1,1] - A[1,0]*A[0,1]
    return det_A

In [ ]:
A = np.array([[5,2],[3,4]])
det_2(A)

np.int64(14)

In [ ]:
def det_3(A):
    if np.shape(A) == (3,3):
        det_A = A[0,0]*(A[1,1]*A[2,2] - A[2,1]*A[1,2]) - A[0,1]*(A[1,0]*A[2,2] - A[2,0]*A[1,2]) + A[0,2]*(A[1,0]*A[2,1] - A[2,0]*A[1,1,])
        return det_A
    else:
        print('Asegúrate que tu matriz sea 3 x 3')

In [ ]:
A = matriz_aleatoria(3,3)

print(det_3(A))
print(la.det(A))

-117
-117.00000000000001


# 3
Escriba tres matrices aleatorias $A$, $B$ y $C$ de $3\times 3$, y demuestre las siguientes relaciones

- $ \mathbf{A}\mathbf{B} \neq \mathbf{B}\mathbf{A} $, en general.
- $ (\mathbf{A}\mathbf{B})\mathbf{C} = \mathbf{A}(\mathbf{B}\mathbf{C}) $.
- $ \mathbf{A}(\mathbf{B} + \mathbf{C}) = \mathbf{A}\mathbf{B} + \mathbf{A}\mathbf{C} $.
- $ (\mathbf{A} + \mathbf{B})\mathbf{C} = \mathbf{A}\mathbf{C} + \mathbf{B}\mathbf{C} $.
- $ (\mathbf{A}\mathbf{B})^\top = \mathbf{B}^\top \mathbf{A}^\top $.
- $ \det(\mathbf{A}\mathbf{B}) = \det(\mathbf{A}) \det(\mathbf{B}) $.
- $ (\mathbf{A}^\top)^\top = \mathbf{A} $.
- $ (c\mathbf{A})^\top = c\mathbf{A}^\top $.
- $ (\mathbf{A} + \mathbf{B})^\top = \mathbf{A}^\top + \mathbf{B}^\top $.



In [12]:
n = 3
A = np.array([[np.random.randint(1,10) for i in range(n)] for j in range(n)])
B = np.array([[np.random.randint(1,10) for i in range(n)] for j in range(n)])
C = np.array([[np.random.randint(1,10) for i in range(n)] for j in range(n)])

print('Matriz A:')
print(A)
print('Matriz B:')
print(B)
print('Matriz C:')
print(C)

Matriz A:
[[8 9 6]
 [1 6 7]
 [3 3 2]]
Matriz B:
[[1 8 3]
 [6 4 6]
 [9 1 7]]
Matriz C:
[[3 9 3]
 [4 9 6]
 [4 9 9]]


- $ \mathbf{A}\mathbf{B} \neq \mathbf{B}\mathbf{A} $

In [13]:
M = np.dot(A,B)
N = np.dot(B,A)

print('Comparación de los dos productos matriciales:')
print(M == N)

Comparación de los dos productos matriciales:
[[False False False]
 [False False False]
 [False False False]]


- $ (\mathbf{A}\mathbf{B})\mathbf{C} = \mathbf{A}(\mathbf{B}\mathbf{C}) $

In [14]:
M = (A@B)@C
N = A@(B@C)

print(np.isclose(M,N))

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


- $ \mathbf{A}(\mathbf{B} + \mathbf{C}) = \mathbf{A}\mathbf{B} + \mathbf{A}\mathbf{C} $

In [15]:
M = A @ (B + C) 
N = A@B + A@C

print('A(B+C):')
print(M)

print('AB + AC:')
print(N)

print('Comparación:')
print(np.isclose(M,N))

A(B+C):
[[200 313 252]
 [155 165 190]
 [ 68 110  86]]
AB + AC:
[[200 313 252]
 [155 165 190]
 [ 68 110  86]]
Comparación:
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


- $ (\mathbf{A} + \mathbf{B})\mathbf{C} = \mathbf{A}\mathbf{C} + \mathbf{B}\mathbf{C} $

In [16]:
M = (A+B) @ C
N = A@C + B@C

print('(A+B)C:')
print(M)

print('(A+B)C:')
print(N)

print('Comparación:')
print(np.isclose(M,N))

(A+B)C:
[[131 315 210]
 [113 270 198]
 [ 88 225 141]]
(A+B)C:
[[131 315 210]
 [113 270 198]
 [ 88 225 141]]
Comparación:
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


- $ (\mathbf{A}\mathbf{B})^\top = \mathbf{B}^\top \mathbf{A}^\top $

In [17]:
A_T = A.T
B_T = B.T
M = (A@B).T
N = B_T @ A_T

print('A transpuesta:')
print(A_T)
print('B transpuesta:')
print(B_T)

print('AB transpuesta:')
print(M)

print('A transpuesta por B transpuesta:')
print(N)

print('Comparación:')
print(np.isclose(M,N))

A transpuesta:
[[8 1 3]
 [9 6 3]
 [6 7 2]]
B transpuesta:
[[1 6 9]
 [8 4 1]
 [3 6 7]]
AB transpuesta:
[[116 100  39]
 [106  39  38]
 [120  88  41]]
A transpuesta por B transpuesta:
[[116 100  39]
 [106  39  38]
 [120  88  41]]
Comparación:
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


- $ \det(\mathbf{A}\mathbf{B}) = \det(\mathbf{A}) \det(\mathbf{B}) $

In [18]:
det_AB = la.det(A@B)
det_A = la.det(A)
det_B = la.det(B)

print('Determinante de AB:')
print(det_AB)

print('Determinante de A:')
print(det_A)

print('Determinante de B:')
print(det_B)

print('Determinante de A por determinante de B:')
print(det_A*det_B)

print('Comparación:')
print(np.isclose(det_AB, det_A*det_B))

Determinante de AB:
252.00000000001552
Determinante de A:
9.000000000000004
Determinante de B:
28.000000000000014
Determinante de A por determinante de B:
252.00000000000023
Comparación:
True


- $ (\mathbf{A}^\top)^\top = \mathbf{A} $

In [19]:
A_T = A.T

print('Matriz A:')
print(A)

print('Matriz A transpuesta:')
print(A_T)

print('Matriz A tranpuesta, transpuesta:')
print(A_T.T)

print('Comparación:')
print(np.isclose(A, A_T.T))

Matriz A:
[[8 9 6]
 [1 6 7]
 [3 3 2]]
Matriz A transpuesta:
[[8 1 3]
 [9 6 3]
 [6 7 2]]
Matriz A tranpuesta, transpuesta:
[[8 9 6]
 [1 6 7]
 [3 3 2]]
Comparación:
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


- $ (c\mathbf{A})^\top = c\mathbf{A}^\top $

In [20]:
cte = np.random.randint(1,10)

cA_T = (cte*A).T

print(cA_T)

c_A_T = cte*(A.T)

print(c_A_T)

[[16  2  6]
 [18 12  6]
 [12 14  4]]
[[16  2  6]
 [18 12  6]
 [12 14  4]]


- $ (\mathbf{A} + \mathbf{B})^\top = \mathbf{A}^\top + \mathbf{B}^\top $

In [21]:
A_T = A.T
B_T = B.T

A_B_T = (A+B).T

print(np.isclose(A_T + B_T, A_B_T))

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


# 4

El **Teorema de Laplace** es un método para calcular el determinante de una matriz cuadrada, particularmente útil para matrices de orden mayor a 2. Este teorema se basa en la expansión del determinante por los elementos de una fila o una columna cualquiera.



$$
\det(A) = \sum_{j=1}^n (-1)^{1+j} a_{1j} M_{1j}
$$

donde:
- $a_{1j}$ es el elemento de la primera fila y columna $j$.
- $M_{1j}$ es el menor asociado al elemento $a_{1j}$, es decir, el determinante de la submatriz de $3 \times 3$ que se obtiene al eliminar la fila 1 y la columna $j$.
- $(-1)^{1+j}$ es el signo correspondiente al cofactor del elemento $a_{1j}$.

Podemos realizar una función recursiva para el cálculo del determinante, sabiendo que el valor del determinante de una matriz de orden uno es el único elemento de esa matriz, y el de una matriz de orden superior a uno es la suma de cada uno de los elementos de una fila o columna por los Adjuntos a ese elemento, como en la función recursiva se emplea la misma función definida el cálculo lo haremos por Menor complementario, un ejemplo desarrollado por la primera fila sería:

$$
   \det (A_{j,j}) =
   \left \{
   \begin{array}{llcl}
      si & j = 1 & \to & a_{1,1} \\
                                 \\
      si & j > 1 & \to & \displaystyle \sum_{k=1}^j \; (-1)^{(1+k)} \cdot a_{1,k} \cdot \det( \alpha_{1,k})
   \end{array}
   \right .
$$

Realice una función que encuentre el determinante de una matriz usando la recursividad aqui planteada, explique explicitamente su código

In [65]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

k = 0  # Columna a eliminar.
menor = np.delete(np.delete(A, 0, axis=0), k, axis=1)

print(menor)

[[5 6]
 [8 9]]


In [75]:
def Laplace_det(A):
    '''
    Esta función calcula el determinante de una matriz por medio del teorema de Laplace:

    Entradas:
    A: matriz (array) de tamaño nxn.

    Salidas:
    det: Determinante calculado de la matriz.
    '''
    n = np.shape(A)[0]
    m = np.shape(A)[1]
    if n != m:
        return 'Ingresa una matriz de iguales dimensiones.'
    if m == 2 and n == 2: #Para determinantes 2x2
        det = A[0,0]*A[1,1] - A[1,0]*A[0,1]
        return det    

    det = 0
    for k in range(n):
        menor = np.delete(np.delete(A, 0 , axis=0), k, axis=1) #Elimino las columnas y filas que no tienen que ver con el menor asociado.
        cofactor = (-1)**k * A[0,k] * Laplace_det(menor) #Aquí como el menor es de tamaño 2x2 recursivamente volverá a la función donde usará el caso 2.
        det += float(cofactor) #Se le van sumando los resultados al determinante.
    return det

In [76]:
A= np.array([[2,1,6],[3,7,8],[9,2,6]])
B = matriz_aleatoria(6,6)
print(B)

print('Por Scipy:')
print(la.det(B))
print('Por función programada:')
Laplace_det(B)

[[3 4 5 7 4 8]
 [9 1 4 9 6 7]
 [3 4 8 8 1 6]
 [4 3 6 9 5 5]
 [3 5 6 3 8 1]
 [3 2 4 4 6 1]]
Por Scipy:
-3760.000000000001
Por función programada:


-3760.0

# 5

El método de Jacobi reescribe el sistema $ Ax = b $ descomponiendo la matriz $ A $ como:

$$
A = D + L + U,
$$

donde:
- $ D $: Matriz diagonal de $ A $,
- $ L $: Matriz triangular inferior sin la diagonal,
- $ U $: Matriz triangular superior sin la diagonal.

El sistema se reorganiza como:

$$
x = D^{-1}(b - (L + U)x).
$$

Esto se implementa iterativamente como:

$$
x_i^{(k+1)} = \frac{1}{a_{ii}} \left(b_i - \sum_{j \neq i} a_{ij} x_j^{(k)}\right),
$$

donde $ a_{ii} $ son los elementos diagonales de $ A $.

* Escriba una función explicita que realice de manera iterativa este método con una tol = 1e-7 y un máximo de 100 iteraciones. Defina una documentación clara que explique los métodos usados, lasa entradas y salidas.

* Para una matriz aleatoria 5$\times$ 5, encuentre la solución usando su función y determine el error con respecto a `solve` y el método de inversa de matriz.

## Usando valores:

In [8]:
def matriz_aleatoria(m,n):
    M = np.array([[np.random.randint(1,10) for i in range(m)] for j in range(n)])
    return M

A5 = matriz_aleatoria(5,5)
#np.shape(A)
A5

array([[3, 3, 7, 2, 1],
       [2, 9, 6, 8, 9],
       [1, 3, 7, 4, 1],
       [3, 5, 7, 8, 4],
       [4, 3, 8, 1, 8]])

In [9]:
def Jacobi(A, b, tol = 1e-7, max_iter = 100):
    '''Función de solución de sistemas de ecuaciones lineales:

    MÉTODO DE JACOBI

    Entradas:
    A: Matriz que representa el sistema de ecuaciones lineales nxn.
    b: Vector que representa los términos independientes de las ecuaciones.
    tol = 1e-07 (Predeterminado) Mínimo valor con el que el programa calculará los resultados.
    max_iter = 100 (Predeterminado)  Máximo número de veces que el sistema repetirá los procesos.
    
    Procesos:
    Crear un array de ceros del tamaño de b, puesto que el vector solución x será de la misma dimensión que el vector
    b. Luego, se definirá un rango de iteración que coincide con el número de filas que tiene la matriz cuadrada ingresada.

    Se crea un ciclo for, con iterador k, quien se repite hasta el máximo número de iteraciones, el segundo ciclo itera
    sobre el rango definido por las filas de la matriz A ingresada, aquí dentro se define la variable suma, que guardará el valor
    de los valores x_i que se calculen en el proceso del siguiente cilo. Por último el tercer ciclo irá sumando los elementos según
    la fórmula del método de Jacobi: sum(A[i,j]*x[j]), sí se cumple la condición de que i != j. Cuando se ha calculado la suma total
    de los elementos, se vuelve dentro del segundo ciclo (j) y se calcula el resto de la fórmula. Este valor de x_i se guarda en
    memoria y el programa sale de los ciclos a comparar si de todos los valores que ha calculado, el más grande que exista en el
    vector x_nuevo, su valor absoluto, sea menor que el valor definido de la tolerancia.

    Si esta anterior condición se cumple el programa te retornará el valor que más se acercó al límite de tolerancia, además de un
    mensaje de cuántas iteraciones le costó repetir el cálculo.

    De lo contrario te retornará que el límite de repeticiones fue superado y además te mostrará el valor en pantalla que más
    se acercó al límite de tolerancia.

    Salidas:
    - Si converge: Vector con la soluciones y un mensaje de que hubo convergencia en menos de 100 iteraciones.
    - Si NO converge: Vector con las soluciones encontradas hasta 100 iteraciones y un mensaje de que no hubo
    convergencia.
    '''
    x = np.zeros_like(b, dtype=float)
    n = np.shape(A)[0]

    for k in range(max_iter):
        x_nuevo = np.copy(x)
        for i in range(n):
            suma = 0
            for j in range(n):
                if j != i:
                    suma += A[i,j]*x[j]
            x_nuevo[i] = (b[i] - suma)/A[i,i]
        if np.max(np.abs(x_nuevo - x)) < tol:
            print(f'Converge luego de {k+1} iteraciones.')
            return x_nuevo
        x = x_nuevo
    print(f'Luego de {max_iter} iteraciones no hay convergencia.')
    return(x)

Probando el método de Jacobi:

In [10]:
A = np.array([[4,-1,1], [-2,6,1], [1,1,5]])
b = np.array([7,9,-6])

print(A)
print('Usando la función Jacobi:')
print(Jacobi(A,b))

print('Usando linalg.solve:')
print(la.solve(A,b))

[[ 4 -1  1]
 [-2  6  1]
 [ 1  1  5]]
Usando la función Jacobi:
Converge luego de 23 iteraciones.
[ 3.08247415  2.92783497 -2.40206179]
Usando linalg.solve:
[ 3.08247423  2.92783505 -2.40206186]


In [11]:
b5 = np.array([1,4,2,5,9])
print(Jacobi(A5,b5))

print(la.solve(A5,b5))

Luego de 100 iteraciones no hay convergencia.
[-5.13595174e+34 -3.66991419e+34 -2.03942249e+34 -3.29491066e+34
 -2.83862996e+34]
[ 0.10934183 -1.55838641  0.42498231  0.60934183  1.15357396]


Probando el método de matriz inversa:

In [12]:
A_inverse = la.inv(A)
sol = A_inverse@b
sol

array([ 3.08247423,  2.92783505, -2.40206186])

## Usando matrices:

In [62]:
def Jacobi_matriz(A, b, tol=1e-7, max_iter=100):
    D = np.diag(np.diag(A))
    U = np.triu(A) - D
    L = np.tril(A) - D
    x = np.zeros_like(b, dtype=float)
    for k in range(max_iter):
        D_inv = la.inv(D)
        x_new = D_inv @ (b - (L+U)@x)
        if np.max(np.abs(x_new - x)) < tol:
            print(f'Converge luego de {k+1} iteraciones.')
            return x_new
        x = x_new 
    print(f'No hubo convergencia luego de {k+1} iteraciones.')
    return x_new

In [63]:
A = np.array([[4,-1,1], [-2,6,1], [1,1,5]])
b = np.array([7,9,-6])

print(A)
print('Usando la función Jacobi:')
print(Jacobi_matriz(A,b))

print('Usando linalg.solve:')
print(la.solve(A,b))

[[ 4 -1  1]
 [-2  6  1]
 [ 1  1  5]]
Usando la función Jacobi:
Converge luego de 23 iteraciones.
[ 3.08247415  2.92783497 -2.40206179]
Usando linalg.solve:
[ 3.08247423  2.92783505 -2.40206186]


In [64]:
def matriz_aleatoria(m,n):
    M = np.array([[np.random.randint(1,10) for i in range(m)] for j in range(n)], dtype=float)
    return M

A5 = matriz_aleatoria(5,5)
#np.shape(A)
A5

array([[7., 8., 4., 6., 4.],
       [5., 7., 2., 5., 9.],
       [4., 9., 9., 1., 4.],
       [5., 4., 3., 4., 2.],
       [9., 9., 3., 5., 9.]])

In [65]:
n = np.random.randint(1,20)
b = n*np.random.rand(5)
print(b)

sol_jacobi = Jacobi_matriz(A5,b)
print('Solución por Jacobi:')
print(sol_jacobi)

sol_solve = la.solve(A5,b)
print('Solución por scipy.linlag.solve:')
print(sol_solve)

[11.9533998   7.79667022  0.77706326 13.72046286 12.34089931]
No hubo convergencia luego de 100 iteraciones.
Solución por Jacobi:
[-5.54348691e+46 -5.41229449e+46 -3.67231951e+46 -5.98525491e+46
 -5.23853829e+46]
Solución por scipy.linlag.solve:
[ 2.396279   -3.53516273  2.02943855  2.11990591  0.65588974]


## Conclusiones:

- El método de Jacobi parece ser efectivo para matrices de tamaño 3x3, mientras que matrices de tamaño 5x5 el método tiende a fallar en el límite de convergencia, pues luego del límite de 100 iteraciones el método obtiene valores muy alejados a los que arroja el método de solución usando la librería de Scipy.

- Lo anterior me lleva a concluir que el método que utiliza Scipy es diferente del método de Jacobi, pues arroja resultados más precisos y acertados.

- Si aumento el número de iteraciones así como la toleracia la puedo reducir, los valores tienden a alejarse más de los esperados.

- También, no se debe descartar, puede haber algún detalle que omita en el código que lleve a este error.

# 6

Verifique que cualquier matriz hermitiana de 2 × 2 $ L $ puede escribirse como una suma de cuatro términos:

$$ L = a\sigma_x + b\sigma_y + c\sigma_z + dI $$

donde $ a $, $ b $, $ c $ y $ d $ son números reales.

Las cuatro matrices de Pauli son:

$$ \sigma_x = \begin{pmatrix} 0 & 1 \\ 1 & 0 \end{pmatrix}, \quad \sigma_y = \begin{pmatrix} 0 & -i \\ i & 0 \end{pmatrix}, \quad \sigma_z = \begin{pmatrix} 1 & 0 \\ 0 & -1 \end{pmatrix}, \quad I = \begin{pmatrix} 1 & 0 \\ 0 & 1 \end{pmatrix} $$




In [27]:
def hermitiana(a,b,c,d):
    s_x = np.array([[0,1],[1,0]])
    s_y = np.array([[0, -1j],[1j,0]])
    s_z = np.array([[1,0],[0,-1]])
    I = np.eye(2)
    L = a*s_x + b*s_y + c*s_z + d*I
    return L

In [28]:
H = hermitiana(1e10,3.4,-4e-2,1)
H_dag = (H.T).conjugate()

print('Matriz H:')
print(H)

print('H*:')
print(H_dag)

booleano = np.array_equal(H, H_dag)
print(f'La matrices son iguales: {booleano}')

Matriz H:
[[9.60e-01+0.j  1.00e+10-3.4j]
 [1.00e+10+3.4j 1.04e+00+0.j ]]
H*:
[[9.60e-01-0.j  1.00e+10-3.4j]
 [1.00e+10+3.4j 1.04e+00-0.j ]]
La matrices son iguales: True
