In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as la

# Actividad 08: Algebra Lineal y Matrices

---
### Profesor: Juan Marcos Marín
### Nombre: Edgar Junior Córdoba Gamboa
*Métodos computacionales 2024-II*

---

#1

Escriba una función que calcule el producto escalar y vectorial para dos vectores, compare sus resultados con `np.dot` y `np.cross`.

In [ ]:
v1 = np.array([2,3,7])
v2 = np.array([6,5,4])
def esca(v1,v2):
  resultado = 0
  for i in range(len(v1)):
    resultado += v1[i]*v2[i]
  return resultado

def vector(v1,v2):
  if len(v1) == 3 and len(v2) == 3:
    result = [0,0,0]
    result[0] = v1[1]*v2[2]-v1[2]*v2[1]
    result[1] = v1[2]*v2[0]-v1[0]*v2[2]
    result[2] = v1[0]*v2[1]-v1[1]*v2[0]
    return result
  else:
    raise ValueError("No esta definido")

print('Producto vectorial:',vector(v1,v2))
print('Producto Punto : ', esca(v1,v2))


Producto vectorial: [-23, 34, -8]
Producto Punto :  55


In [ ]:
np.dot(v1,v2)

55

In [ ]:
np.cross(v1,v2)

array([-23,  34,  -8])

#2

Crear una función llamada `mulmat()` donde a partir de dos matrices $A$ y $B$ encuentre su multplicación. También realiza una función que calcule la transpuesta y otra el determinante de una matriz $3\times 3$. Compare sus resultado con `@`, `np.dot`, `transpose` y `la.det`.

In [ ]:
A = np.array([1,4,8,3,6,9,6,12,18]).reshape(3,3)
B = np.array([1,5,14,3,4,12,3,6,18]).reshape(3,3)
def mulmat(A, B):
    if len(A[0]) != len(B):
        raise ValueError('Número de columnas de A debe coincidir con filas de B')

    filas = len(A)
    columnas = len(B[0])
    resultado = [[0 for _ in range(columnas)] for _ in range(filas)]

    for i in range(filas):
        for j in range(columnas):
            for k in range(len(B)):
                resultado[i][j] += A[i][k] * B[k][j]
    return resultado

# Transpuesta
def transpuesta(matrix):
    return [[matrix[j][i] for j in range(len(matrix))]
            for i in range(len(matrix[0]))]

# Determinate 3x3
def determinante(matrix):
    if len(matrix) != 3 or any(len(row) != 3 for row in matrix):
        raise ValueError('La matriz debe ser 3x3')

    a, b, c = matrix[0]
    d, e, f = matrix[1]
    g, h, i = matrix[2]

    return a*(e*i - f*h) - b*(d*i - f*g) + c*(d*h - e*g)

In [ ]:
# Producto Matrices
print('Producto Matrices: ',np.array(mulmat(A, B)))
print('Producto Numpy: ',np.dot(A, B))

Producto Matrices:  [[ 37  69 206]
 [ 48  93 276]
 [ 96 186 552]]
Producto Numpy:  [[ 37  69 206]
 [ 48  93 276]
 [ 96 186 552]]


In [ ]:
# Transpuesta y Determinante para la Matriz A
print('Transpuesta: ',np.array(transpuesta(A)))
print('Transpuesta Numpy: ',np.transpose(A))
print('Determinante: ', determinante(A))
print('Determinante Numpy: ', np.linalg.det(A))

Transpuesta:  [[ 1  3  6]
 [ 4  6 12]
 [ 8  9 18]]
Transpuesta Numpy:  [[ 1  3  6]
 [ 4  6 12]
 [ 8  9 18]]
Determinante:  0
Determinante Numpy:  0.0


In [ ]:
# Transpuesta y Determinante para la matriz B
print('Transpuesta: ',np.array(transpuesta(B)))
print('Transpuesta Numpy: ',np.transpose(B))
print('Determinante: ', determinante(B))
print('Determinante Numpy: ', np.linalg.det(B))

Transpuesta:  [[ 1  3  3]
 [ 5  4  6]
 [14 12 18]]
Transpuesta Numpy:  [[ 1  3  3]
 [ 5  4  6]
 [14 12 18]]
Determinante:  -6
Determinante Numpy:  -6.000000000000016


#3
Escriba tres matrices aleatorias $A$, $B$ y $C$ de $3\times 3$, y demuestre las siguientes relaciones

- $ \mathbf{A}\mathbf{B} \neq \mathbf{B}\mathbf{A} $, en general.
- $ (\mathbf{A}\mathbf{B})\mathbf{C} = \mathbf{A}(\mathbf{B}\mathbf{C}) $.
- $ \mathbf{A}(\mathbf{B} + \mathbf{C}) = \mathbf{A}\mathbf{B} + \mathbf{A}\mathbf{C} $.
- $ (\mathbf{A} + \mathbf{B})\mathbf{C} = \mathbf{A}\mathbf{C} + \mathbf{B}\mathbf{C} $.
- $ (\mathbf{A}\mathbf{B})^\top = \mathbf{B}^\top \mathbf{A}^\top $.
- $ \det(\mathbf{A}\mathbf{B}) = \det(\mathbf{A}) \det(\mathbf{B}) $.
- $ (\mathbf{A}^\top)^\top = \mathbf{A} $.
- $ (c\mathbf{A})^\top = c\mathbf{A}^\top $.
- $ (\mathbf{A} + \mathbf{B})^\top = \mathbf{A}^\top + \mathbf{B}^\top $.



In [ ]:
# Punto 3
A_ = np.array([3,5,1,6,8,12,7,4,2]).reshape(3,3)
B_ = np.array([1,7,4,9,3,2,7,6,2]).reshape(3,3)
C_ = np.array([4,10,2,9,16,16,6,2,2]).reshape(3,3)

In [ ]:
# AB Distinto BA
x0 = np.dot(A_,B_)
y0 = np.dot(B_,A_)
print(np.array_equal(x0,y0))

False


In [ ]:
#(AB)C = A(BC)
x = np.dot(A_,B_)
y = np.dot(B_,C_)

x1 = np.dot(x,C_)
x2 = np.dot(A_,y)
print(np.array_equal(x1,x2))

True


In [ ]:
# A (B+C)= AB + AC
sum1 = np.add(B_,C_)
x1 = np.dot(A_,sum1)
y1= np.dot(A_,B_)
y2 = np.dot(A_,C_)
y3 = y1 + y2
print(np.array_equal(x1,y3))

True


In [ ]:
# (A+B)C= AC + BC
sum = np.add(A_,B_)
x3 = np.dot(sum,C_)
y4= np.dot(A_,C_)
y0 = np.dot(B_,C_)
y3 = y0 + y4
print(np.array_equal(x3,y3))

True


In [ ]:
xt = np.transpose(np.dot(A_,B_))
xta = np.transpose(A_)
xtb = np.transpose(B_)
z = np.dot(xtb,xta)
print(np.array_equal(xt,z))

True


In [ ]:
# Det(AB)= Det(A)*Det(B)
det = np.linalg.det(np.dot(A_,B_))
deta = np.linalg.det(A_)
detb = np.linalg.det(B_)
det1 = deta*detb
print(det)
print(det1)
print(np.array_equal(det,det1))

22735.999999999945
22735.99999999999
False


In [ ]:
T = np.transpose(np.transpose(A_))
print(np.array_equal(T,A_))

True


In [ ]:
c = 3
T1 = np.transpose(np.dot(c,A_))
T2 = c * np.transpose(A_)
print(np.array_equal(T1,T2))

True


In [ ]:
w = np.transpose(np.add(A_,B_))
w1 = np.transpose(A_)
w2 = np.transpose(B_)
sum0 = np.add(w1,w2)
print(np.array_equal(w,sum0))

True


#4

El **Teorema de Laplace** es un método para calcular el determinante de una matriz cuadrada, particularmente útil para matrices de orden mayor a 2. Este teorema se basa en la expansión del determinante por los elementos de una fila o una columna cualquiera.



$$
\det(A) = \sum_{j=1}^n (-1)^{1+j} a_{1j} M_{1j}
$$

donde:
- $a_{1j}$ es el elemento de la primera fila y columna $j$.
- $M_{1j}$ es el menor asociado al elemento $a_{1j}$, es decir, el determinante de la submatriz de $3 \times 3$ que se obtiene al eliminar la fila 1 y la columna $j$.
- $(-1)^{1+j}$ es el signo correspondiente al cofactor del elemento $a_{1j}$.

Podemos realizar una función recursiva para el cálculo del determinante, sabiendo que el valor del determinante de una matriz de orden uno es el único elemento de esa matriz, y el de una matriz de orden superior a uno es la suma de cada uno de los elementos de una fila o columna por los Adjuntos a ese elemento, como en la función recursiva se emplea la misma función definida el cálculo lo haremos por Menor complementario, un ejemplo desarrollado por la primera fila sería:

$$
   \det (A_{j,j}) =
   \left \{
   \begin{array}{llcl}
      si & j = 1 & \to & a_{1,1} \\
                                 \\
      si & j > 1 & \to & \displaystyle \sum_{k=1}^j \; (-1)^{(1+k)} \cdot a_{1,k} \cdot \det( \alpha_{1,k})
   \end{array}
   \right .
$$

Realice una función que encuentre el determinante de una matriz usando la recursividad aqui planteada, explique explicitamente su código

In [ ]:
def laplace(A):
    n = len(A)  # Tamaño de la matriz
    # Si la matriz es de 1x1 devolvemos la matriz original
    if n == 1:
        return A[0, 0]
    # Si la matriz es de 2x2, usamos el determinante
    if n == 2:
        return np.linalg.det(A)
    # Caso general: expansión por la primera fila
    det = 0
    for j in range(n):
        # Construcción del menor M_1j eliminando la fila 0 y la columna j
        M_1j = np.array([fila[:j].tolist() + fila[j+1:].tolist() for fila in A[1:]])

        # Aplicación de la fórmula de Laplace
        det += (-1) ** j * A[0, j] * laplace(M_1j)

    return det

A = np.array([[3, 5, 1, 6, 8, 12, 7, 4, 2]]).reshape(3,3)
resultado = laplace(A)
print("El determinante es:", resultado)


El determinante es: 232.00000000000006


#5

El método de Jacobi reescribe el sistema $ Ax = b $ descomponiendo la matriz $ A $ como:

$$
A = D + L + U,
$$

donde:
- $ D $: Matriz diagonal de $ A $,
- $ L $: Matriz triangular inferior sin la diagonal,
- $ U $: Matriz triangular superior sin la diagonal.

El sistema se reorganiza como:

$$
x = D^{-1}(b - (L + U)x).
$$

Esto se implementa iterativamente como:

$$
x_i^{(k+1)} = \frac{1}{a_{ii}} \left(b_i - \sum_{j \neq i} a_{ij} x_j^{(k)}\right),
$$

donde $ a_{ii} $ son los elementos diagonales de $ A $.

* Escriba una función explicita que realice de manera iterativa este método con una tol = 1e-7 y un máximo de 100 iteraciones. Defina una documentación clara que explique los métodos usados, lasa entradas y salidas.

* Para una matriz aleatoria 5$\times$ 5, encuentre la solución usando su función y determine el error con respecto a `solve` y el método de inversa de matriz.

In [ ]:
def Jacobi_matriz(A,b, tol= 1e-7, max_iter=100):
  n = len(b)
  x = np.zeros_like(b, dtype= float)
  D = np.diag(np.diag(A)) # Matriz diagonal de A
  L = np.tril(A) - D # Matriz L
  U = np.triu(A) - D # Matriz D
  for k in range(max_iter):
    inversa = np.linalg.inv(D)
    x_new = inversa @ (b-(L+U)@x) # Actualizamos los valores de las variables

    if np.max(np.abs(x_new -x)) < tol:
      print(f'Converge con {k+1} iteraciones')
      return x_new
    x = x_new
  print('Paila No converge')
  return x

In [ ]:
A = np.array([2,3,5,7,4,9,6,1,7,5,12,14,8,1,6,2,7,6,9,4,4,3,2,1,7]).reshape(5,5)  # Matriz 5x5
b = np.array([4,6,8,3,5]) # Vector b

# Solución con el método de Jacobi
x_jacobi = Jacobi_matriz(A, b)

# Solución con solve
x_solve = np.linalg.solve(A, b)

# Solución con la inversa de la matriz
x_inv = np.linalg.inv(A) @ b

# Cálculo del error
error_jacobi = np.linalg.norm(x_jacobi - x_solve)
error_inv = np.linalg.norm(x_inv - x_solve)

print(f"Solución con Jacobi:\n{x_jacobi}")
print(f"Solución con solve :\n{x_solve}")
print(f"Solución con la inversa de la matriz:\n{x_inv}")
print(f"Error entre Jacobi y solve: {error_jacobi: .2e}")
print(f"Error entre inversa y solve: {error_inv: .2e}")

Paila No converge
Solución con Jacobi:
[-1.11689806e+60 -6.02621067e+59 -7.41851697e+59 -3.32591150e+59
 -2.87110728e+59]
Solución con solve :
[ 0.62286812 -0.36904476  0.41180239  0.03218833  0.39426695]
Solución con la inversa de la matriz:
[ 0.62286812 -0.36904476  0.41180239  0.03218833  0.39426695]
Error entre Jacobi y solve:  1.53e+60
Error entre inversa y solve:  7.12e-16


#6

Verifique que cualquier matriz hermitiana de 2 × 2 $ L $ puede escribirse como una suma de cuatro términos:

$$ L = a\sigma_x + b\sigma_y + c\sigma_z + dI $$

donde $ a $, $ b $, $ c $ y $ d $ son números reales.

Las cuatro matrices de Pauli son:

$$ \sigma_x = \begin{pmatrix} 0 & 1 \\ 1 & 0 \end{pmatrix}, \quad \sigma_y = \begin{pmatrix} 0 & -i \\ i & 0 \end{pmatrix}, \quad \sigma_z = \begin{pmatrix} 1 & 0 \\ 0 & -1 \end{pmatrix}, \quad I = \begin{pmatrix} 1 & 0 \\ 0 & 1 \end{pmatrix} $$


