In [53]:
import numpy as np
import sympy as sp
import scipy as sc

In [54]:
A= np.matrix([[2,1,-1,5],[4,1,1,1],[6,2,1,4]])
A

matrix([[ 2,  1, -1,  5],
        [ 4,  1,  1,  1],
        [ 6,  2,  1,  4]])

In [55]:
B=A[0]*3
B

matrix([[ 6,  3, -3, 15]])

In [56]:
def intercambio(M,i,j):
  B=M.copy()
  B[i]=M[j]
  B[j]=M[i]
  return B

In [57]:
def mul_escalar(M,i,x):
  B=M.copy()
  B[i]=x*M[i]
  return B

In [58]:
def suma(M,i,j,x):
  B=M.copy()
  B[j]= x*M[i]+M[j]
  return B

In [59]:
C=suma(A,0,1,-2)
C

matrix([[ 2,  1, -1,  5],
        [ 0, -1,  3, -9],
        [ 6,  2,  1,  4]])

In [60]:
C=suma(C,0,2,-3)
C

matrix([[  2,   1,  -1,   5],
        [  0,  -1,   3,  -9],
        [  0,  -1,   4, -11]])

In [61]:
C=mul_escalar(C,1,-1)
C

matrix([[  2,   1,  -1,   5],
        [  0,   1,  -3,   9],
        [  0,  -1,   4, -11]])

In [62]:
C=mul_escalar(C,2,-1)
C

matrix([[ 2,  1, -1,  5],
        [ 0,  1, -3,  9],
        [ 0,  1, -4, 11]])

In [63]:
C=suma(C,1,2,-1)
C

matrix([[ 2,  1, -1,  5],
        [ 0,  1, -3,  9],
        [ 0,  0, -1,  2]])

In [64]:
C=mul_escalar(C,2,-1)
C

matrix([[ 2,  1, -1,  5],
        [ 0,  1, -3,  9],
        [ 0,  0,  1, -2]])

In [65]:
C=suma(C,2,1,3)
C

matrix([[ 2,  1, -1,  5],
        [ 0,  1,  0,  3],
        [ 0,  0,  1, -2]])

In [66]:
C=suma(C,2,0,1)
C

matrix([[ 2,  1,  0,  3],
        [ 0,  1,  0,  3],
        [ 0,  0,  1, -2]])

In [67]:
C=suma(C,1,0,-1)
C

matrix([[ 2,  0,  0,  0],
        [ 0,  1,  0,  3],
        [ 0,  0,  1, -2]])

In [68]:
C=mul_escalar(C,0,1/2)
C

matrix([[ 1,  0,  0,  0],
        [ 0,  1,  0,  3],
        [ 0,  0,  1, -2]])