In [ ]:
#Librerías
import numpy as np
import scipy as sp
import sympy as sy
import copy

# Caso particular paso a paso

In [ ]:
A=np.array([[2,1,-1,5],[4,1,1,1],[6,2,1,4]])
b=np.matrix(A)

In [ ]:
sy.Matrix(b)

Matrix([
[2, 1, -1, 5],
[4, 1,  1, 1],
[6, 2,  1, 4]])

In [ ]:
#Primera fila
b[0]

matrix([[ 2,  1, -1,  5]])

In [ ]:
#Operación por escalar de la primera fila
2*b[0]

matrix([[ 4,  2, -2, 10]])

In [ ]:
#Almacena el resultado de suma
b_copia=b.copy()

In [ ]:
newR1=-2*b[0]+b[1]
b_copia[1]=newR1
b_copia

matrix([[ 2,  1, -1,  5],
        [ 0, -1,  3, -9],
        [ 6,  2,  1,  4]])

In [ ]:
newR2=-3*b[0]+b[2]
b_copia[2]=newR2
b_copia

matrix([[  2,   1,  -1,   5],
        [  0,  -1,   3,  -9],
        [  0,  -1,   4, -11]])

In [ ]:
copia2 = b_copia.copy()

In [ ]:
copia2

matrix([[  2,   1,  -1,   5],
        [  0,  -1,   3,  -9],
        [  0,  -1,   4, -11]])

In [ ]:
#Matriz triangular superior
r2new=-1*copia2[1]+copia2[2]
copia2[2]=r2new
copia2

matrix([[ 2,  1, -1,  5],
        [ 0, -1,  3, -9],
        [ 0,  0,  1, -2]])

Definiendo las funciones

In [ ]:
A=np.array([[2,1,-1,5],[4,1,1,1],[6,2,1,4]])
b=np.matrix(A)

In [ ]:
def mult_escalar(b,indice,alpha):
    b_escalar=b.copy()
    b_escalar[indice]=alpha*b[indice]
    return b_escalar

In [ ]:
def inter_filas(b,fila1,fila2):
    fila_temp=b.copy()
    fila_temp[fila1]=b[fila2]
    fila_temp[fila2]=b[fila1]
    return fila_temp

In [ ]:
def sum_filas(b,fila1,fila2,alpha):
    suma_f=b.copy()
    suma_f[fila1]=b[fila1]+alpha*b[fila2]
    return suma_f

In [ ]:
#Ensayo
#Iniciemos con la suma de filas
boe1=sum_filas(b,1,0,-2)
boe2=sum_filas(boe1,2,0,-3)
boe3=sum_filas(boe2,2,1,-1)
#Multiplicación por escalar
mf=mult_escalar(boe3,1,-1)
sy.Matrix(mf)
#print(mf)

Matrix([
[2, 1, -1,  5],
[0, 1, -3,  9],
[0, 0,  1, -2]])

Generalización del código

In [ ]:
def mult_escalar(b2,indice,alpha):
        b_escalar=b2.copy()
        b_escalar[indice]=alpha*b2[indice]
        return b_escalar

def inter_filas(b2,fila1,fila2):
    fila_temp=b2.copy()
    fila_temp[fila1]=b2[fila2]
    fila_temp[fila2]=b2[fila1]
    return fila_temp

def sum_filas(b2,fila1,fila2,alpha):
    suma_f=b2.copy()
    suma_f[fila1]=b2[fila1]+alpha*b2[fila2]
    return suma_f

Nota:  b2_reducida1=np.copy(b2).astype('float64') el .astype("float") fue una linea sugerida por chat gpt y fue de la única forma que me funcionó el código, vale la aclaración porque sola no hubiera llegado a esa conclusión para que el código cumpliera la función

In [ ]:
def reduccion(b2):
    triangular_inf=0
    triangular_sup=0

    for i in range(len(b2)):
        for j in range(i+1,len(b2[i])):
            if b2[i][j]!=0:
                triangular_sup=1
                break

    for i in range(len(b2)):
        for j in range(0,i):
            if b2[i][j]!=0:
                triangular_inf=2
                break

    if triangular_sup==1:
        f1,c1=b2.shape
        b2_reducida1=np.copy(b2).astype('float64')
        for i in range(f1):
            for j in range(i+1,f1):
                factor=b2_reducida1[j,i]/b2_reducida1[i,i]
                b2_reducida1[j,i:] -=factor*b2_reducida1[i,i:]
            b2_reducida1[i,:]/=b2_reducida1[i,i]
        return "La matriz es triangular superior",b2_reducida1

    elif triangular_inf==2:
        f2,c2=b2.shape
        b2_reducida2=np.copy(b2).astype('float64')
        for i in range(f2-1,0,-1):
            for j in range(i):
                factor=b2_reducida1[j,i]/b2_reducida1[i,i]
                b2_reducida1[j,i:] -=factor*b2_reducida1[i,i:]
            b2_reducida2[i,:]/=b2_reducida2[i,i]
        return "La matriz es triangular inferior",b2_reducida2

    else:
        return "La matriz no es ni triangular superior ni triangular inferior"

In [ ]:
b2=np.array([[2,1,-1,5],[4,1,1,1],[6,2,1,4]])
matriz=reduccion(b2)
matriz

('La matriz es triangular superior',
 array([[ 1. ,  0.5, -0.5,  2.5],
        [-0. ,  1. , -3. ,  9. ],
        [ 0. ,  0. ,  1. , -2. ]]))

In [ ]:
#Otra matriz
b3=np.array([[1,-1,1,2],[1,1,1,4],[2,2,-1,-4]])
matriz=reduccion(b3)
matriz

('La matriz es triangular superior',
 array([[ 1., -1.,  1.,  2.],
        [ 0.,  1.,  0.,  1.],
        [-0., -0.,  1.,  4.]]))

In [ ]:
b4=np.array([[1,-1,1,2],[1,1,1,4],[2,2,-1,-4]])
matriz=reduccion(b4)
matriz

('La matriz es triangular superior',
 array([[ 1., -1.,  1.,  2.],
        [ 0.,  1.,  0.,  1.],
        [-0., -0.,  1.,  4.]]))