In [2]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as la
import random

# Actividad 08: Algebra Lineal y Matrices

---
### Profesor: Juan Marcos Marín
### Nombre: Edwar Isaías Pacheco Rojas
### CC: 1017240283
*Métodos computacionales 2024-II*

---

#1

Escriba una función que calcule el producto escalar y vectorial para dos vectores, compare sus resultados con `np.dot` y `np.cross`.

## Solución 1)

In [3]:
# @title Función para el producto escalar entre vectores
def producto_escalar(a: np.ndarray, b: np.ndarray) -> float:

  """
  La función calcula el producto escalar entre dos vectores.

  Args:
    :a: Vector uno
    :b: Vector dos

  Returns:
    :float: Producto escalar entre los vectores a y b.
  """

  if len(a) != len(b):
    raise ValueError("Los vectores deben tener la misma longitud.")

  producto_escalar = 0
  for i in range(len(a)):
    producto_escalar += a[i] * b[i]

  return producto_escalar



In [4]:
# @title Función producto cruz
def producto_cruz(a: np.ndarray, b: np.ndarray) -> np.ndarray:

  """
  La función calcula el producto cruz entre dos vectores.

  Args:
    :a: Vector uno
    :b: Vector dos

  Returns:
    :np.ndarray: Producto cruz entre los vectores a y b.
  """

  if len(a) and len(b) != 3:
    raise ValueError("Los vectores deben tener dimensión tres.")

  return np.array([a[1] * b[2] - a[2] * b[1], a[2] * b[0] - a[0] * b[2], \
                   a[0] * b[1] - a[1] * b[0]])



In [5]:
# @title Vectores y valor de prueba para el producto punto
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(f'Producto punto por función: {producto_escalar(a, b)}\nProducto punto \
por Numpy: {np.dot(a, b)}')

Producto punto por función: 32
Producto punto por Numpy: 32


In [6]:
# @title Prueba del producto cruz
print(f'Producto cruz por función: {producto_cruz(a, b)}\nProducto cruz por \
Numpy: {np.cross(a, b)}')

Producto cruz por función: [-3  6 -3]
Producto cruz por Numpy: [-3  6 -3]


#2

Crear una función llamada `mulmat()` donde a partir de dos matrices $A$ y $B$ encuentre su multplicación. También realiza una función que calcule la transpuesta y otra el determinante de una matriz $3\times 3$. Compare sus resultado con `@`, `np.dot`, `transpose` y `la.det`.

## Solución 2)

In [7]:
# @title Multiplicación de matrices
def mulmat(a: np.ndarray, b: np.ndarray) -> np.ndarray:

  """
  La función calcula el producto de dos matrices.

  Args:
    :a: Matriz uno
    :b: Matriz dos

  Returns:
    :np.ndarray: Producto de las matrices a y b.
  """

  if a.shape[1] != b.shape[0]:
    raise ValueError("Las matrices no son compatibles para la multiplicación.")

  C = np.zeros((a.shape[0], b.shape[1]))

  for j in range(b.shape[1]):
    for i in range(a.shape[0]):
      C[i, j] = producto_escalar(a[i, :], b[:, j])

  return C



In [8]:
# @title Ejemplo para la multiplicación de matrices
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = A.T
print(f'Multiplicación por función: \n{mulmat(A, B)}\nMultiplicación por \
Numpy: \n{A @ B}')

Multiplicación por función: 
[[ 14.  32.  50.]
 [ 32.  77. 122.]
 [ 50. 122. 194.]]
Multiplicación por Numpy: 
[[ 14  32  50]
 [ 32  77 122]
 [ 50 122 194]]


In [9]:
# @title Función para la transpuesta de una función
def transpuesta(a: np.ndarray) -> np.ndarray:

  """
  La función calcula la transpuesta de una matriz.

  Args:
    :a: Matriz

  Returns:
    :np.ndarray: Transpuesta de la matriz a.
  """

  return np.array([[a[j, i] for j in range(a.shape[0])] \
                   for i in range(a.shape[1])])

In [10]:
# @title Ejercicio de comprobación para la transpuesta
print(f'Transpuesta por función: \n{transpuesta(A)}\nTranspuesta por \
Numpy: \n{A.T}')

Transpuesta por función: 
[[1 4 7]
 [2 5 8]
 [3 6 9]]
Transpuesta por Numpy: 
[[1 4 7]
 [2 5 8]
 [3 6 9]]


El determinante es un valor escalar asociado a una matriz cuadrada. Matemáticamente, para una matriz $A$ de orden $n \times n$, el determinante se denota como $\text{det}(A)$ o $|A|$ y se calcula de la siguiente manera:

1. **Para matrices $2 \times 2$**:
   Si $A$ es:
   $$
   A =
   \begin{bmatrix}
   a & b \\
   c & d
   \end{bmatrix},
   $$
   el determinante es:
   $$
   \text{det}(A) = ad - bc.
   $$

2. **Para matrices $n \times n$** (con $n > 2$):
   El determinante se calcula utilizando una **expansión por cofactores**. Para la matriz $A$:
   $$
   \text{det}(A) = \sum_{j=1}^n (-1)^{1+j} a_{1j} \cdot \text{det}(A_{1j}),
   $$
   donde $A_{1j}$ es la matriz obtenida al eliminar la primera fila y la $j$-ésima columna de $A$.

El cálculo se vuelve recursivo, reduciendo la matriz hasta llegar a matrices de tamaño $2 \times 2$.


In [31]:
# @title Determinante nxn
def determinante(a: np.ndarray) -> float:

  """
  La función calcula el determinante de una matriz.

  Args:
    :a: Matriz

  Returns:
    :float: Determinante de la matriz a.
  """

  m, n = a.shape
  if m != n:
    raise ValueError("La matriz no es cuadrada para calcular el determinante.")

  if m == 1:
    return a[0, 0]
  elif m == 2:
    return a[0, 0] * a[1, 1] - a[0, 1] * a[1, 0]
  else:
    det = 0
    for j in range(n):
      sub_a = np.delete(np.delete(a, 0, axis=0), j, axis=1)
      det += (-1)**j * a[0, j] * determinante(sub_a)
    return det

In [12]:
# @title Función determinante 3x3
def det_3x3(a: np.ndarray) -> float:

  """
  La función calcula el determinante de una matriz 3x3.

  Args:
    :a: Matriz 3x3

  Returns:
    :float: Determinante de la matriz 3x3.
  """

  return a[0, 0] * (a[1, 1] * a[2, 2] - a[1, 2] * a[2, 1]) - a[0, 1] * \
         (a[1, 0] * a[2, 2] - a[1, 2] * a[2, 0]) + a[0, 2] * \
         (a[1, 0] * a[2, 1] - a[1, 1] * a[2, 0])

In [13]:
# @title Ejemplo determinante 3x3
A = np.array([[1, 7, 3], [4, 10, 6], [1, 8, 9]])
print(f'Determinante por función: {det_3x3(A)}\nDeterminante por Numpy: \
{la.det(A)}')

Determinante por función: -102
Determinante por Numpy: -102.0


In [14]:
# @title Determimanante por función para A de nxn
A = np.array([[1, 7, 3], [4, 10, 6], [1, 8, 9]])
print(f'Determinante por función: {determinante(A)}\nDeterminante por Numpy: \
{la.det(A)}')

Determinante por función: -102
Determinante por Numpy: -102.0


#3
Escriba tres matrices aleatorias $A$, $B$ y $C$ de $3\times 3$, y demuestre las siguientes relaciones

- $ \mathbf{A}\mathbf{B} \neq \mathbf{B}\mathbf{A} $, en general.
- $ (\mathbf{A}\mathbf{B})\mathbf{C} = \mathbf{A}(\mathbf{B}\mathbf{C}) $.
- $ \mathbf{A}(\mathbf{B} + \mathbf{C}) = \mathbf{A}\mathbf{B} + \mathbf{A}\mathbf{C} $.
- $ (\mathbf{A} + \mathbf{B})\mathbf{C} = \mathbf{A}\mathbf{C} + \mathbf{B}\mathbf{C} $.
- $ (\mathbf{A}\mathbf{B})^\top = \mathbf{B}^\top \mathbf{A}^\top $.
- $ \det(\mathbf{A}\mathbf{B}) = \det(\mathbf{A}) \det(\mathbf{B}) $.
- $ (\mathbf{A}^\top)^\top = \mathbf{A} $.
- $ (c\mathbf{A})^\top = c\mathbf{A}^\top $.
- $ (\mathbf{A} + \mathbf{B})^\top = \mathbf{A}^\top + \mathbf{B}^\top $.



In [15]:
# @title Definición de matices
A = np.random.rand(3, 3)
B = np.random.rand(3, 3)
C = np.random.rand(3, 3)
for matriz in (A, B, C):
  print(matriz)

[[0.31179385 0.29255258 0.49309284]
 [0.64274193 0.11748032 0.14090935]
 [0.98878031 0.07962705 0.32279864]]
[[0.64451393 0.59545292 0.84622568]
 [0.36648343 0.34303627 0.84816906]
 [0.83070213 0.22969504 0.47113449]]
[[0.70752808 0.37484467 0.17356654]
 [0.97137523 0.99556731 0.20425962]
 [0.4885883  0.72487144 0.27967148]]


In [16]:
# @title matmul no conmuta
from sympy import Matrix, symbols, init_printing
print("Comprobemos que cada entrada es difente en el producto AB y BC:")
print(np.isclose(A @ B, B @ A))
print('Así, se comprueba que no necesariamente AB = BA')
print("Además, nótese que:")

# Renderizado del producto
init_printing()
C_1 = Matrix(A @ B)
C_2 = Matrix(B @ A)
display(C_1)
print()
display(C_2)
print()
print("El producto de matrices no conmuta.")

Comprobemos que cada entrada es difente en el producto AB y BC:
[[False False False]
 [False False False]
 [False False False]]
Así, se comprueba que no necesariamente AB = BA
Además, nótese que:


⎡0.717784422669715  0.399275685840643  0.744295050950495⎤
⎢                                                       ⎥
⎢0.574364415730849  0.455388749185196  0.709935151908711⎥
⎢                                                       ⎥
⎣0.934614191840669  0.690232334779772  1.05635005823021 ⎦

⎡1.42040932231251   0.325890662175069  0.674870590007799⎤
⎢                                                       ⎥
⎢1.17340393544961    0.2150528807514   0.50283519381522 ⎥
⎢                                                       ⎥
⎣0.872490959127559  0.30752374296387   0.594061027021207⎦


El producto de matrices no conmuta.


In [17]:
# @title El producto de matrices es asociativo
Q = A @ B
P = B @ C
print(np.isclose(Q @ C, A @ P))
print("El producto de matrices es asociativo.")

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
El producto de matrices es asociativo.


In [18]:
# @title El producto de matrices es distributivo
R = B + C
print(np.isclose(A @ R, A @ B + A @ C))
print("Se comprueba que el producto de matrices es distributivo.")

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
Se comprueba que el producto de matrices es distributivo.


In [19]:
# @title Transpuesta del producto
M_1 = (A @ B).T
M_2 = B.T @ A.T
print(f'(AB)⊤=B⊤A⊤ -> {np.isclose(M_1, M_2)}')

(AB)⊤=B⊤A⊤ -> [[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [20]:
# @title Determinante de un producto
det_1 = la.det(A @ B)
det_2 = la.det(A) * la.det(B)
print(f'det(AB)=det(A)det(B) is: {np.isclose(det_1, det_2)}')

det(AB)=det(A)det(B) is: True


In [21]:
# @title Transpuesta de la transpuesta
print(f'(A⊤)⊤=A --> {np.isclose((A.T).T, A)}')

(A⊤)⊤=A --> [[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [26]:
# @title Transpuesta de un producto de matriz por escalar
c = random.randint(1, 100)
M_3 = np.dot(A, c)
print(f'(cA).⊤=c(A.⊤). --> {np.isclose(M_3.T, np.dot(A.T, c))}')

(cA).⊤=c(A.⊤). --> [[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [27]:
# @title Transpuesta de la suma
S = A + B
print(f'(A+B)⊤=A⊤+B⊤ --> {np.isclose(S.T, A.T + B.T)}')

(A+B)⊤=A⊤+B⊤ --> [[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


#4

El **Teorema de Laplace** es un método para calcular el determinante de una matriz cuadrada, particularmente útil para matrices de orden mayor a 2. Este teorema se basa en la expansión del determinante por los elementos de una fila o una columna cualquiera.



$$
\det(A) = \sum_{j=1}^n (-1)^{1+j} a_{1j} M_{1j}
$$

donde:
- $a_{1j}$ es el elemento de la primera fila y columna $j$.
- $M_{1j}$ es el menor asociado al elemento $a_{1j}$, es decir, el determinante de la submatriz que se obtiene al eliminar la fila 1 y la columna $j$.
- $(-1)^{1+j}$ es el signo correspondiente al cofactor del elemento $a_{1j}$.

Podemos realizar una función recursiva para el cálculo del determinante, sabiendo que el valor del determinante de una matriz de orden uno es el único elemento de esa matriz, y el de una matriz de orden superior a uno es la suma de cada uno de los elementos de una fila o columna por los Adjuntos a ese elemento, como en la función recursiva se emplea la misma función definida el cálculo lo haremos por Menor complementario, un ejemplo desarrollado por la primera fila sería:

$$
   \det (A_{j,j}) =
   \left \{
   \begin{array}{llcl}
      si & j = 1 & \to & a_{1,1} \\
                                 \\
      si & j > 1 & \to & \displaystyle \sum_{k=1}^j \; (-1)^{(1+k)} \cdot a_{1,k} \cdot \det( \alpha_{1,k})
   \end{array}
   \right .
$$

Realice una función que encuentre el determinante de una matriz usando la recursividad aqui planteada, explique explicitamente su código

## Solución 4)

In [36]:
# @title Determinante por función recursiva.
def determinante_recursivo(matriz: list) -> float:

  """
  Calcula el determinante de una matriz cuadrada usando recursividad.

  Args:
    matriz: Una matriz cuadrada representada como una lista de listas.

  Returns:
    El determinante de la matriz.
  """

  n = len(matriz)  # Número de filas de la matriz

  # Caso base: matriz de 1x1
  if n == 1:
    return matriz[0][0]

  determinante = 0
  for j in range(n):
    # Submatriz obtenida al eliminar la primera fila y la columna 'j'
    submatriz = [fila[:j] + fila[j + 1:] for fila in matriz[1:]]

    # Llamada recursiva para calcular el determinante de la submatriz
    determinante += (-1)**(1 + j)*matriz[0][j]*determinante_recursivo(submatriz)

  return determinante

# Ejemplo de uso
A = np.array([[1, 7, 3], [4, 10, 6], [1, 8, 9]])
print(f'Determinante por función recursiva: \
{determinante_recursivo(A.tolist())}')
print(f'Determinante por numpy: {np.linalg.det(A)}')

Determinante por función recursiva: -102
Determinante por numpy: -102.00000000000004


#5

El método de Jacobi reescribe el sistema $ Ax = b $ descomponiendo la matriz $ A $ como:

$$
A = D + L + U,
$$

donde:
- $ D $: Matriz diagonal de $ A $,
- $ L $: Matriz triangular inferior sin la diagonal,
- $ U $: Matriz triangular superior sin la diagonal.

El sistema se reorganiza como:

$$
x = D^{-1}(b - (L + U)x).
$$

Esto se implementa iterativamente como:

$$
x_i^{(k+1)} = \frac{1}{a_{ii}} \left(b_i - \sum_{j \neq i} a_{ij} x_j^{(k)}\right),
$$

donde $ a_{ii} $ son los elementos diagonales de $ A $.

* Escriba una función explicita que realice de manera iterativa este método con una tol = 1e-7 y un máximo de 100 iteraciones. Defina una documentación clara que explique los métodos usados, lasa entradas y salidas.

* Para una matriz aleatoria 5$\times$ 5, encuentre la solución usando su función y determine el error con respecto a `solve` y el método de inversa de matriz.

In [50]:
# @title Solución por Jacobi
def jacobi_method(A, b, tol=1e-7, max_iter=100):

  """
  Resuelve el sistema Ax = b usando el método iterativo de Jacobi.

  Parámetros:
    A : ndarray
        Matriz cuadrada de coeficientes.
    b : ndarray
        Vector de términos independientes.
    tol : float, opcional
        Tolerancia para la convergencia (default 1e-7).
    max_iter : int, opcional
        Número máximo de iteraciones (default 100).

  Retorna:
    x : ndarray
      Aproximación de la solución del sistema Ax = b.
    k : int
      Número de iteraciones realizadas.
  """

  n = len(A)
  x = np.zeros(n)  # Vector inicial
  D = np.diag(A)   # Extraer la diagonal de A
  R = A - np.diagflat(D)  # R = L + U

  for k in range(max_iter):
    x_new = (b - np.dot(R, x)) / D  # Fórmula iterativa

    if np.linalg.norm(x_new - x, ord=np.inf) < tol:  # Criterio de parada
      return x_new, k + 1

    x = x_new  # Actualizar

  return x, max_iter  # Devolver el resultado tras max_iter iteraciones

# Generar una matriz aleatoria 5x5 y un vector b
np.random.seed(42)
A = np.random.rand(5, 5)
A += np.diag([5]*5)  # Asegurar que la diagonal sea dominante
b = np.random.rand(5)

# Resolver con Jacobi
x_jacobi, iterations = jacobi_method(A, b)

# Solución exacta con solve
x_solve = np.linalg.solve(A, b)

# Solución con la inversa de A
x_inv = np.dot(np.linalg.inv(A), b)

# Calcular errores
error_jacobi_solve = np.linalg.norm(x_jacobi - x_solve, ord=np.inf)
error_inv_solve = np.linalg.norm(x_inv - x_solve, ord=np.inf)

# Mostrar resultados
print(f"Solución Jacobi: {x_jacobi}, Iteraciones: {iterations}")
print(f"Solución solve: {x_solve}")
print(f"Solución inversa: {x_inv}")
print(f"Error Jacobi vs solve: {error_jacobi_solve}")
print(f"Error inversa vs solve: {error_inv_solve}")

Solución Jacobi: [ 0.12231351  0.0123086   0.08266623  0.09713883 -0.0164666 ], Iteraciones: 14
Solución solve: [ 0.12231352  0.0123086   0.08266624  0.09713884 -0.0164666 ]
Solución inversa: [ 0.12231352  0.0123086   0.08266624  0.09713884 -0.0164666 ]
Error Jacobi vs solve: 9.347602233922281e-09
Error inversa vs solve: 1.3877787807814457e-17


#6

Verifique que cualquier matriz hermitiana de 2 × 2 $ L $ puede escribirse como una suma de cuatro términos:

$$ L = a\sigma_x + b\sigma_y + c\sigma_z + dI $$

donde $ a $, $ b $, $ c $ y $ d $ son números reales.

Las cuatro matrices de Pauli son:

$$ \sigma_x = \begin{pmatrix} 0 & 1 \\ 1 & 0 \end{pmatrix}, \quad \sigma_y = \begin{pmatrix} 0 & -i \\ i & 0 \end{pmatrix}, \quad \sigma_z = \begin{pmatrix} 1 & 0 \\ 0 & -1 \end{pmatrix}, \quad I = \begin{pmatrix} 1 & 0 \\ 0 & 1 \end{pmatrix} $$




In [46]:
# @title Matrices hermitianas y su descomposición
sigma_x = np.array([[0, 1], [1, 0]])
sigma_y = np.array([[0, -1j], [1j, 0]])
sigma_z = np.array([[1, 0], [0, -1]])
I = np.array([[1, 0], [0, 1]])

def descomponer_matriz_hermitiana(L: np.ndarray) -> tuple:

  """
  Descompone una matriz hermitiana 2x2 como combinación lineal de las matrices de Pauli y la identidad.

  Args:
    L: Una matriz hermitiana 2x2 representada como un array NumPy.

  Returns:
    Una tupla (a, b, c, d) que representa los coeficientes de la descomposición.
    Devuelve None si la matriz no es hermitiana 2x2.
  """

  # Verificar si la matriz es 2x2 y hermitiana
  if L.shape != (2, 2) or not np.allclose(L, L.conj().T):
    return None

  # Coeficientes utilizando las propiedades de las matrices de Pauli
  a = np.real(0.5 * (L[0, 1] + L[1, 0]))
  b = np.real(0.5j * (L[0, 1] - L[1, 0]))
  c = 0.5 * (L[0, 0] - L[1, 1])
  d = 0.5 * (L[0, 0] + L[1, 1])

  return a, b, c, d


# Ejemplo de uso
L = np.array([[2, 1+1j], [1-1j, 3]]) # Matriz hermitiana de ejemplo

coeficientes = descomponer_matriz_hermitiana(L)

if coeficientes:
  a, b, c, d = coeficientes
  L_reconstruida = a * sigma_x + b * sigma_y + c * sigma_z + d * I
  print("Matriz original L:\n", L)
  print("\nCoeficientes (a, b, c, d):", coeficientes)
  print("\nMatriz reconstruida:\n", L_reconstruida)

  # Verificar si la reconstruccion es correcta
  print("\n¿Son iguales las matrices original y reconstruida?", \
        np.allclose(L, L_reconstruida))
else:
  print("La matriz ingresada no es hermitiana 2x2.")

Matriz original L:
 [[2.+0.j 1.+1.j]
 [1.-1.j 3.+0.j]]

Coeficientes (a, b, c, d): (1.0, -1.0, (-0.5+0j), (2.5+0j))

Matriz reconstruida:
 [[2.+0.j 1.+1.j]
 [1.-1.j 3.+0.j]]

¿Son iguales las matrices original y reconstruida? True
