In [ ]:
import numpy as np
import matplotlib.pyplot as plt
from scipy import linalg

In [ ]:
A=np.matrix([[2, 1, 1, 5],
             [4, 1, 1, 1],
             [6, 2, 1, 4],])

def mult(A, i,j, lamb):
  B = A.copy()
  B[i] = A[i]+lamb*B[j]
  return B
np.shape(A)

(3, 4)

In [ ]:
A=np.matrix([[2, 1, 1, 5],
             [4, 1, 1, 1],
             [6, 2, 1, 4]])

for i in range(0,np.shape(A)[1]-1):
  for p in range(0,np.shape(A)[0]-1):
    if i==0:

      if A[p+1,i]==0:

        A[p+1]=A[p+1]

      else:

        n=A[p+1,i]/A[0,i]
        A[p+1]=A[p+1]-n*A[i]

    if i==1:

      if A[p+1,i]==0:

        A[p+1]=A[p+1]

      else:

        n=A[p+1,i]/A[p,i]
        A[2]=A[2]-n*A[i]

print(A)

[[ 2  1  1  5]
 [ 0 -1 -1 -9]
 [ 0  0 -1 -2]]


In [ ]:
Y=A[1]-A[2]
Z=A[2]
X=A[0]+Y+Z
X,Y,Z

(matrix([[ 2,  0,  0, -4]]),
 matrix([[ 0, -1,  0, -7]]),
 matrix([[ 0,  0, -1, -2]]))

In [ ]:
A=np.matrix([[2, 1, 1, 5],
             [4, 1, 1, 1],
             [6, 2, 1, 4]])

for i in range(0,np.shape(A)[1]-1):
  for p in range(0,np.shape(A)[0]-1):
    n=A[p+1,i]/A[p,p]
    if A[p+1,i]==0:
      A[p+1]=A[p+1]
    else:
      print(n)
      A[p+1]=A[p+1]-n*A[p]

#print(A)

2.0
-6.0
-0.5
-inf
-inf


<ipython-input-45-45aa0fa4a706>:7: RuntimeWarning: divide by zero encountered in long_scalars
  n=A[p+1,i]/A[p,p]
<ipython-input-45-45aa0fa4a706>:12: RuntimeWarning: invalid value encountered in multiply
  A[p+1]=A[p+1]-n*A[p]
