1. Estudiar las operaciones basicas con matrices.
2. Suma de matrices
3. Resta de matrices
4. Multiplicacion por un escalar.
5. Determinar el determinante de una matriz
6. Determinar la inversa de una matriz
7. Diagonizacion de matrices


In [ ]:
#librerias
import numpy as np


In [ ]:
# Definicion de una matriz cuadra 2x2 con numeros aleatorios enteros


In [ ]:
c1 = np.array([1, 1])
c2 = np.array([3, 4])

In [ ]:
type(c1)

numpy.ndarray

In [ ]:
m = np.array([c1,c2])

In [ ]:
type(m)

numpy.ndarray

In [ ]:
M = np.asmatrix(m)

In [ ]:
m

array([[1, 1],
       [3, 4]])

In [ ]:
m[1]

array([3, 4])

In [ ]:
m[:,0]

array([1, 3])

In [ ]:
m[:,1]

array([1, 4])

In [ ]:
np.shape(m)

(2, 2)

In [ ]:
2*m

array([[2, 2],
       [6, 8]])

In [ ]:
m@m

array([[ 4,  5],
       [15, 19]])

In [ ]:
m

array([[1, 1],
       [3, 4]])

In [ ]:
np.linalg.det(m)

0.9999999999999998

In [ ]:
M.I

matrix([[ 4., -1.],
        [-3.,  1.]])

In [ ]:
np.linalg.inv(m)

array([[ 4., -1.],
       [-3.,  1.]])

In [ ]:
M = np.array([np.random.randint(0, 20, 2), np.random.randint(0, 20, 2)])

In [ ]:
M1 = np.asmatrix(M)

In [ ]:
M1

matrix([[ 3, 13],
        [14,  2]])

$det(M-\lambda I) = 0$

In [ ]:
import scipy.linalg as la

In [ ]:
autovalor, autovector = la.eig(M1)

In [ ]:
autovalor

array([ 16.+0.j, -11.+0.j])

In [ ]:
autovector

array([[ 0.70710678, -0.6804511 ],
       [ 0.70710678,  0.73279349]])

# ¿Cual es el polinomio caracteristico?
```

matrix([[ 6,  3],
        [14, 13]])

```

  $\lambda^2-19\lambda +36=0$

In [ ]:
f = lambda x: x**2-19*x+36
f(autovalor[1])

(366.0000000000001+0j)

In [ ]:
M = np.array([np.random.randint(0, 20, 3), np.random.randint(0, 20, 3),np.random.randint(0, 20, 3)])


M1 = np.asmatrix(M)

In [ ]:
autovalor, autovector = la.eig(M1)
autovalor


array([29.12650244+0.j, -1.52284252+0.j,  4.39634008+0.j])

In [ ]:
autovector

array([[-0.71224693, -0.25294622, -0.06307966],
       [-0.40892209,  0.83889572, -0.67762498],
       [-0.57051472, -0.48194624,  0.73269731]])

In [ ]:
# D = U.I@ E @ U


Se sabe que un sistema físico es gobernado por las ecuaciones,



$$
\begin{matrix}
x' &=& 2x&-y&+z, \\
y' &=&   &3y&-1z, \\
z' &=& 2x&+y&+3z,
\end{matrix}
$$

donde $x',y',z'$ son las derivadas, en forma vectorial esto se puede representar como $\mathbf{r}'=A\mathbf{r}$ que tiene solución analítica general, $\mathbf{r} = e^{At} \mathbf{r}(0)$.<br> 
a) Diagonalize $A$.<br> 

b) Use el hecho de que $f(A) = U f(D) U^{-1}$ para encontrar $x(t),y(t),z(t)$ en el intervalo de tiempo $[0,2]$.<br>.
c) Grafique $x(t),y(t),z(t)$ (use la condición inicial $\mathbf{r}(0)=(1,1,2))$.<br> 
d) Compare el resultado a la solución analítica,

$$
\begin{align}
2x & = x(0)(e^{2t}(1+e^{2t}-2t)) + y(0) (-2te^{2t}) + z(0)(e^{2t}(-1+e^{2t})), \\
2y & = x(0)(-e^{2t}(-1+e^{2t}-2t)) + y(0)(2(t+1)e^{2t}) + z(0)(-e^{2t}(-1+e^{2t})), \\
2z & = x(0)(e^{2t}(-1+e^{2t}+2t)) + y(0)(2te^{2t}) + z(0)(e^{2t}(1+e^{2t})).
\end{align}
$$

In [ ]:
x1 = np.array([2, -1, 1])
x2 = np.array([0, 3, -1])
x3 = np.array([2, 1, +3])

A = np.asmatrix([x1,x2,x3])

In [ ]:
type(A)

numpy.matrix

In [ ]:
E, U = la.eig(A) 

In [ ]:
E.round()

array([4.+0.j, 2.+0.j, 2.-0.j])

In [ ]:
U.round()

array([[-1.+0.j, -1.+0.j, -1.-0.j],
       [ 1.+0.j,  1.+0.j,  1.-0.j],
       [-1.+0.j,  1.-0.j,  1.+0.j]])

In [ ]:
U = np.asmatrix(U)

In [ ]:
U.round()

matrix([[-1.+0.j, -1.+0.j, -1.-0.j],
        [ 1.+0.j,  1.+0.j,  1.-0.j],
        [-1.+0.j,  1.-0.j,  1.+0.j]])

In [ ]:
D = U.I @ (A @U)

In [ ]:
D.round()

matrix([[ 4.-0.j, -0.+0.j, -0.+0.j],
        [-0.-0.j,  2.+0.j,  0.-0.j],
        [-0.+0.j,  0.+0.j,  2.-0.j]])

In [ ]:
E.round()

array([4.+0.j, 2.+0.j, 2.-0.j])

In [ ]:
np.diag(E, 0).round()

array([[4.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 2.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 2.-0.j]])

In [ ]:
f = lambda t: np.exp(-E*t) 
r0=np.array([1,1,2])
f(0)

array([1.-0.j, 1.-0.j, 1.+0.j])

In [ ]:
t = 0
Diagonal = np.diag(f(0), 0)
f_A = U@(Diagonal@U.I)
r = f_A@r0
f_A

matrix([[ 1.00000000e+00+1.48283206e-09j,
          1.14461084e-16+1.48283206e-09j,
          1.72379063e-17-2.85318003e-24j],
        [ 2.07014709e-16+7.18842778e-10j,
          1.00000000e+00+7.18842778e-10j,
          4.37175683e-17+1.21433760e-24j],
        [-8.94701088e-18-1.25681227e-09j,
          1.91565885e-16-1.25681227e-09j,
          1.00000000e+00+6.57710925e-25j]])

In [ ]:
t = 1
Diagonal = np.diag(f(1), 0)
f_A = U@(Diagonal@U.I)
r = f_A@r0


In [ ]:
#1. Evaluar la funcion la funcion en cada autovalor. 
#2. Construir una mtriz diagonal
#3. UF(D)U-1
#4. r(t) = (U F(D) U-1) r(0)


In [ ]:
np.diag(f(3), 0)

array([[6.14421235e-06-0.00000000e+00j, 0.00000000e+00+0.00000000e+00j,
        0.00000000e+00+0.00000000e+00j],
       [0.00000000e+00+0.00000000e+00j, 2.47875218e-03-1.25414672e-10j,
        0.00000000e+00+0.00000000e+00j],
       [0.00000000e+00+0.00000000e+00j, 0.00000000e+00+0.00000000e+00j,
        2.47875218e-03+1.25414672e-10j]])

 $\mathbf{r}'=A\mathbf{r}$


 $f(A) =U f(D) U^{-1}$


 e^{At} = U e^(D) U ^{-1}


2. Un proceso para encriptar un mensaje secreto es usar cierta matrix cuadrada cuyos elementos son enteros con elementos enteros en la inversa. Se recibe un mensaje, se asigna un número a cada letra Por ejemplo, A=1, B=2, C=3, ... etc y espacio=27), se arreglan los números en una matriz de izquierda a derecha en cada fila, donde el número de elementos en la fila es igual al tamano de la matriz de codigo, se multiplica esa matriz por la matriz de código por la derecha, se transcribe el mensaje en una cadena de números y se manda el mensaje. 

La persona que debe recibir el mensaje conoce la matriz de codigo. El o ellla arrelgan el mensaje encriptado en una matriz de izquierda a derecha en cada fila, en donde el numero de elementos en una fila conicide con el tamano de la matriz de codigo muplicada por la derecha, por el inverso de la matriz de código y puede leer mensaje decodificado.

Usted a recibido el siguiente mensaje que fue encriptado usando la matriz A. Decodifiquelo.

```
A = matrix([[ 1,  2, -3,  4,  5],
        [-2, -5,  8, -8, -9],
        [ 1,  2, -2,  7,  9],
        [ 1,  1,  0,  6, 12],
        [ 2,  4, -6,  8, 11]])
```

Mensaje

47,49,-19,257,487,10,-9,63,137,236, 79,142,-184,372,536,59,70,-40,332,588, 

la primera fila del mensaje es 47,49,-19,257,487

¿Cual es el mensaje?





```
abc=['A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z',' ']
num=['1','2','3','4','5','6','7','8','9','10','11','12','13','14','15','16','17','18','19','20','21','22','23','24','25','26','27']
```


3. Construir un programa que permita realizar la multiplicacion de dos matrices. El programa debe establecer si las matrices se pueden multiplicar.
