In [15]:
import numpy as np
import sympy as sp
import scipy as sc
import scipy.integrate as integrate

In [16]:
A = np.array([[1,1,1,2],
              [4,1,2,2],
              [5,1,4,8/3],
              ])

A = np.asmatrix(A)
A

matrix([[1.        , 1.        , 1.        , 2.        ],
        [4.        , 1.        , 2.        , 2.        ],
        [5.        , 1.        , 4.        , 2.66666667]])

In [17]:
## Multiplicar una fila por escalar

a = 5

opera = a*A[1]
print(opera)
B = np.copy(A)
print(B)
row = 1
B[row] = opera

B



[[20.  5. 10. 10.]]
[[1.         1.         1.         2.        ]
 [4.         1.         2.         2.        ]
 [5.         1.         4.         2.66666667]]


array([[ 1.        ,  1.        ,  1.        ,  2.        ],
       [20.        ,  5.        , 10.        , 10.        ],
       [ 5.        ,  1.        ,  4.        ,  2.66666667]])

In [18]:
## Intercambiar dos filas

C = np.copy(A)

row_org = 2
row_cambio = 1
C[row_cambio] = A[row_org]
A,C


(matrix([[1.        , 1.        , 1.        , 2.        ],
         [4.        , 1.        , 2.        , 2.        ],
         [5.        , 1.        , 4.        , 2.66666667]]),
 array([[1.        , 1.        , 1.        , 2.        ],
        [5.        , 1.        , 4.        , 2.66666667],
        [5.        , 1.        , 4.        , 2.66666667]]))

In [19]:
## Sumar dos filas multiplicadas por un escalar

D = np.copy(A)
row_sum1,row_sum2 = 0,1
D[row_sum1] = A[row_sum1] -5* A[row_sum2]
D

array([[-19.        ,  -4.        ,  -9.        ,  -8.        ],
       [  4.        ,   1.        ,   2.        ,   2.        ],
       [  5.        ,   1.        ,   4.        ,   2.66666667]])

In [20]:
## Generalizacion del anterior codigo

## Esta funcion recibe la matriz M, que se le va a operar R1 : a*R1 + b*R2
## Es decir, el segundo argumento de la funcion sera la fila donde se haran las operaciones, multiplicadas por cierto escalar.

def sum_filas_escalar(M,R1,R2,a,b):
  R1 = R1-1
  R2 = R2-1
  B = np.copy(M)
  B[R1] = a*M[R1]+b*M[R2]
  return B

A,sum_filas_escalar(A,1,2,1,-5)

(matrix([[1.        , 1.        , 1.        , 2.        ],
         [4.        , 1.        , 2.        , 2.        ],
         [5.        , 1.        , 4.        , 2.66666667]]),
 array([[-19.        ,  -4.        ,  -9.        ,  -8.        ],
        [  4.        ,   1.        ,   2.        ,   2.        ],
        [  5.        ,   1.        ,   4.        ,   2.66666667]]))

In [21]:
## Esta funcion multiplica la fila R1, de la matriz M, por un escalar a.
def mul_escalar(M,R1,a):
  R1 = R1-1
  B = np.copy(M)
  B[R1] = a*M[R1]
  return B

A,mul_escalar(A,2,a)


(matrix([[1.        , 1.        , 1.        , 2.        ],
         [4.        , 1.        , 2.        , 2.        ],
         [5.        , 1.        , 4.        , 2.66666667]]),
 array([[ 1.        ,  1.        ,  1.        ,  2.        ],
        [20.        ,  5.        , 10.        , 10.        ],
        [ 5.        ,  1.        ,  4.        ,  2.66666667]]))

In [22]:
## Esta funcion me intercambia dos filas de posicion.
## Es decir, la fila R1 la intercambia por la fila R2

def intercambio(M,R1,R2):
  R1 = R1-1
  R2 = R2-1
  B = np.copy(M)
  B[R1] = M[R2]
  B[R2] = M[R1]
  return B

A,intercambio(A,3,1)


(matrix([[1.        , 1.        , 1.        , 2.        ],
         [4.        , 1.        , 2.        , 2.        ],
         [5.        , 1.        , 4.        , 2.66666667]]),
 array([[5.        , 1.        , 4.        , 2.66666667],
        [4.        , 1.        , 2.        , 2.        ],
        [1.        , 1.        , 1.        , 2.        ]]))

In [23]:
## Vamos a realizar gauss jordan para la matriz dada A.


H = sum_filas_escalar(A,3,2,1,-1)
H = sum_filas_escalar(H,2,3,1,-1)
H = mul_escalar(H,3,0.5)
H = sum_filas_escalar(H,1,2,1,-1)
H = sum_filas_escalar(H,1,3,1,-1)
sp.Matrix(H)

Matrix([
[-2.5,   0,   0, 0.333333333333333],
[ 3.0, 1.0,   0,  1.33333333333333],
[ 0.5,   0, 1.0, 0.333333333333333]])

In [24]:
4/3

1.3333333333333333

In [25]:
A = np.array(A)


x = sp.Symbol("x")

A
resul = sp.solve(x*A[1][0]-A[0][0],x)

## Aqui vemos como resolver un sistema de ecuaciones

In [30]:
A1 = np.array([[5,3,-4,1],
              [2,5,-10,2],
              [5,2,9,3]

              ])


In [31]:

def gauss_jordan(M):
  x = sp.Symbol("x")
  B = np.copy(M)
  if M[0][0] !=0:
    if M[1][0] !=0:
      resul = sp.solve(x*M[0][0]-M[1][0],x)
      resul = float(resul[0])
      M = sum_filas_escalar(M,2,1,1,-resul)
    if M[2][0] !=0:
      resul = sp.solve(x*M[0][0]-M[2][0],x)
      resul = float(resul[0])
      M = sum_filas_escalar(M,3,1,1,-resul)
  if M[0][0] == 0 and M[1][0] !=0:
    M = intercambio(M,1,2)
    if M[2][0] !=0:
      resul = sp.solve(x*M[0][0]-M[2][0],x)
      resul = float(resul[0])
      M = sum_filas_escalar(M,3,1,1,-resul)
  if M[0][0] == 0 and M[1][0] ==0:
    M = intercambio(M,1,3)
  if M[1][1] != 0 and M[2][1] !=0:
    resul = sp.solve(x*M[1][1]-M[2][1],x)
    resul = float(resul[0])
    M = sum_filas_escalar(M,3,2,1,-resul)
  if M[1][1] == 0 and M[2][1] !=0:
    M = intercambio(M,2,3)
  return M




def solution(M):
  C = sp.solve(x*M[2][2]-M[2][3],x)
  C = float(C[0])
  B = sp.solve(x*M[1][1]+M[1][2]*C-M[1][3],x)
  B = float(B[0])
  A = sp.solve(x*M[0][0]+M[0][1]*B+M[0][2]*C-M[0][3],x)
  A = float(A[0])
  return A,B,C




In [32]:
print(gauss_jordan(A1))
print(solution(gauss_jordan(A1)))

[[ 5  3 -4  1]
 [ 0  3 -8  1]
 [ 0  0 10  2]]
(-0.16, 0.8666666666666667, 0.2)
