In [1]:
import numpy as np
import sympy as sp

In [306]:
M1 = np.array( [[5,-4,0,1],[-4,7,-3,2],[0,-3,5,3]] )
sp.Matrix(M1) # [1,2,3] es para determinar las soluciones

Matrix([
[ 5, -4,  0, 1],
[-4,  7, -3, 2],
[ 0, -3,  5, 3]])

In [3]:
def intercambio (M,i,j):
  I= M.copy()

  I[i]= M1[j]
  I[j]= M1[i]
  return I

In [4]:
intercambio(M1,0,1)

array([[-4,  7, -3],
       [ 5, -4,  0],
       [ 0, -3,  5]])

In [5]:
def suma (M,i,j,a):
  S= M.copy()
  S[j]= a*S[i]+S[j]
  return S

In [6]:
suma(M1,0,1,2)

array([[ 5, -4,  0],
       [ 6, -1, -3],
       [ 0, -3,  5]])

In [7]:
def escalar (M,i,a):
  E= M.copy()
  E[i]= a*E[i]
  return E

In [8]:
escalar(M1,0,2)

array([[10, -8,  0],
       [-4,  7, -3],
       [ 0, -3,  5]])

In [293]:
A= np.array([[2,1,1,5],[4,1,1,1],[6,2,1,4]]) # Para escalares racionales
A

array([[2, 1, 1, 5],
       [4, 1, 1, 1],
       [6, 2, 1, 4]])

In [10]:
# Eliminación gaussiana

F1= suma(A,0,1,-2).copy()
F2= suma(F1,0,2,-3).copy()
F3= suma(F2,1,2,-1)
F3= escalar(F3,2,-1)
F4= suma(F3,2,1,1)
F5= suma(F4,2,0,-1)
F6= suma(F5,1,0,1)
F7= escalar(F6,1,-1)
F8= escalar(F7,0,1/2)
F8

array([[ 1.,  0.,  0., -2.],
       [-0.,  1., -0.,  7.],
       [-0., -0.,  1.,  2.]])

In [163]:
M1

array([[ 5, -4,  0,  1],
       [-4,  7, -3,  2],
       [ 0, -3,  5,  3]])

In [312]:
def eliminacion_gaussiana(M):

  Mc = M.copy().astype(float) # operar con racionales
  n = len(M)
  soluciones = np.zeros(np.shape(Mc[0:n,n]))

  for i in range(n):
    Mc = escalar(Mc, i,1 / Mc[i, i]) # pivotes
    for j in range(i + 1, n):
      Mc = suma(Mc, i, j, -Mc[j, i]) #reducción

  # Para determinar las soluciones

  for i in range(n - 1, -1, -1):
    soluciones[i] = (Mc[i, -1] - np.dot(Mc[i, i + 1:n], soluciones[i + 1:])) / Mc[i, i]

  return Mc, soluciones

In [313]:
matriz, soluciones = eliminacion_gaussiana(A)
print(f"Matriz reducida: {matriz} ")
print(f"La solución es: {soluciones}") # concuerda con la solución manual

Matriz reducida: [[ 1.   0.5  0.5  2.5]
 [-0.   1.   1.   9. ]
 [-0.  -0.   1.   2. ]] 
La solución es: [-2.  7.  2.]


In [314]:
matriz1, soluciones1 = eliminacion_gaussiana(M1)
print(f"Matriz reducida: {matriz1} ")
print(f"La solución es: {soluciones1}")

Matriz reducida: [[ 1.00000000e+00 -8.00000000e-01  0.00000000e+00  2.00000000e-01]
 [ 0.00000000e+00  1.00000000e+00 -7.89473684e-01  7.36842105e-01]
 [ 0.00000000e+00 -1.68753900e-16  1.00000000e+00  1.98000000e+00]] 
La solución es: [2.04 2.3  1.98]
