In [1]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as la

# Actividad 08: Algebra Lineal y Matrices

---
### Profesor: Juan Marcos Marín
### Nombre: ______
*Métodos computacionales 2024-II*

---

#1

Escriba una función que calcule el producto escalar y vectorial para dos vectores, compare sus resultados con `np.dot` y `np.cross`.

In [2]:


def producto_escalar(v1, v2):
    #Calcula el producto escalar de dos vectores.
    if len(v1) != len(v2):
        raise ValueError("Los vectores deben tener la misma dimensión.")
    return sum(x * y for x, y in zip(v1, v2))

def producto_vectorial(v1, v2):
    """Calcula el producto vectorial de dos vectores en R^3."""
    if len(v1) != 3 or len(v2) != 3:
        raise ValueError("Los vectores deben ser de dimensión 3.")
    return [v1[1]*v2[2] - v1[2]*v2[1],
            v1[2]*v2[0] - v1[0]*v2[2],
            v1[0]*v2[1] - v1[1]*v2[0]]

In [3]:
# Vectores de ejemplo
v1 = [1, 2, 3]
v2 = [4, 5, 6]

# Producto escalar
escalar_manual = producto_escalar(v1, v2)
escalar_numpy = np.dot(v1, v2)
print("Producto escalar (manual):", escalar_manual)
print("Producto escalar (numpy):", escalar_numpy)

# Producto vectorial
vectorial_manual = producto_vectorial(v1, v2)
vectorial_numpy = np.cross(v1, v2)
print("Producto vectorial (manual):", vectorial_manual)
print("Producto vectorial (numpy):", vectorial_numpy)

Producto escalar (manual): 32
Producto escalar (numpy): 32
Producto vectorial (manual): [-3, 6, -3]
Producto vectorial (numpy): [-3  6 -3]


#2

Crear una función llamada `mulmat()` donde a partir de dos matrices $A$ y $B$ encuentre su multplicación. También realiza una función que calcule la transpuesta y otra el determinante de una matriz $3\times 3$. Compare sus resultado con `@`, `np.dot`, `transpose` y `la.det`.

In [42]:
import numpy as np
import scipy.linalg as la

def mulmat(A, B):
    #calcula la multiplicación de dos matrices
    if A.shape[1] != B.shape[0]:
        raise ValueError("El número de columnas de A debe ser igual al número de filas de B.")

    result = [[0 for _ in range(B.shape[1])] for _ in range(A.shape[0])]

    for i in range(A.shape[0]):
        for j in range(B.shape[1]):
            for k in range(A.shape[1]):
                result[i][j] += A[i][k] * B[k][j]

    return np.array(result)

def transpuesta(A):
    #Calcula la transpuesta de una matriz.
    rows, cols = A.shape
    result = [[0 for _ in range(rows)] for _ in range(cols)]

    for i in range(rows):
        for j in range(cols):
            result[j][i] = A[i][j]

    return np.array(result)

def determinante(A):
    #Calcula el determinante de una matriz 3x3.
    if A.shape != (3, 3):
        raise ValueError("La matriz debe ser de 3x3.")

    return (A[0][0] * (A[1][1] * A[2][2] - A[1][2] * A[2][1]) -
            A[0][1] * (A[1][0] * A[2][2] - A[1][2] * A[2][0]) +
            A[0][2] * (A[1][0] * A[2][1] - A[1][1] * A[2][0]))

In [6]:
# Matrices de ejemplo
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

B = np.array([[9, 8, 7],
              [6, 5, 4],
              [3, 2, 1]])

# Multiplicación de matrices
mulmat_manual = mulmat(A, B)
mulmat_numpy = A @ B  # Usando el operador @
mulmat_numpy_dot = np.dot(A, B)
print("Multiplicación de matrices (manual):\n", mulmat_manual)
print("Multiplicación de matrices (numpy @):\n", mulmat_numpy)
print("Multiplicación de matrices (numpy dot):\n", mulmat_numpy_dot)

# Transpuesta de la matriz
transpuesta_manual = transpuesta(A)
transpuesta_numpy = A.T  # Usando el atributo T
transpuesta_numpy_transpose = np.transpose(A)
print("Transpuesta de la matriz (manual):\n", transpuesta_manual)
print("Transpuesta de la matriz (numpy T):\n", transpuesta_numpy)
print("Transpuesta de la matriz (numpy transpose):\n", transpuesta_numpy_transpose)

# Determinante de la matriz
determinante_manual = determinante(A)
determinante_scipy = la.det(A)
print("Determinante de la matriz (manual):", determinante_manual)
print("Determinante de la matriz (scipy det):", determinante_scipy)

Multiplicación de matrices (manual):
 [[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]
Multiplicación de matrices (numpy @):
 [[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]
Multiplicación de matrices (numpy dot):
 [[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]
Transpuesta de la matriz (manual):
 [[1 4 7]
 [2 5 8]
 [3 6 9]]
Transpuesta de la matriz (numpy T):
 [[1 4 7]
 [2 5 8]
 [3 6 9]]
Transpuesta de la matriz (numpy transpose):
 [[1 4 7]
 [2 5 8]
 [3 6 9]]
Determinante de la matriz (manual): 0
Determinante de la matriz (scipy det): 0.0


#3
Escriba tres matrices aleatorias $A$, $B$ y $C$ de $3\times 3$, y demuestre las siguientes relaciones

- $ \mathbf{A}\mathbf{B} \neq \mathbf{B}\mathbf{A} $, en general.
- $ (\mathbf{A}\mathbf{B})\mathbf{C} = \mathbf{A}(\mathbf{B}\mathbf{C}) $.
- $ \mathbf{A}(\mathbf{B} + \mathbf{C}) = \mathbf{A}\mathbf{B} + \mathbf{A}\mathbf{C} $.
- $ (\mathbf{A} + \mathbf{B})\mathbf{C} = \mathbf{A}\mathbf{C} + \mathbf{B}\mathbf{C} $.
- $ (\mathbf{A}\mathbf{B})^\top = \mathbf{B}^\top \mathbf{A}^\top $.
- $ \det(\mathbf{A}\mathbf{B}) = \det(\mathbf{A}) \det(\mathbf{B}) $.
- $ (\mathbf{A}^\top)^\top = \mathbf{A} $.
- $ (c\mathbf{A})^\top = c\mathbf{A}^\top $.
- $ (\mathbf{A} + \mathbf{B})^\top = \mathbf{A}^\top + \mathbf{B}^\top $.



In [7]:

# Generar matrices aleatorias de 3x3
A = np.random.rand(3, 3)
B = np.random.rand(3, 3)
C = np.random.rand(3, 3)

print("Matriz A:\n", A)
print("\nMatriz B:\n", B)
print("\nMatriz C:\n", C)

Matriz A:
 [[0.24318961 0.13219738 0.49698339]
 [0.96344728 0.13637703 0.04021597]
 [0.72811964 0.24342123 0.41558862]]

Matriz B:
 [[0.6027007  0.96535989 0.01831439]
 [0.54274951 0.89041062 0.6553219 ]
 [0.84938696 0.01564707 0.02672261]]

Matriz C:
 [[0.61722654 0.13370918 0.02145617]
 [0.04695742 0.27215636 0.72770278]
 [0.37116845 0.61118078 0.41704754]]


In [8]:
# AB vs. BA
AB = np.dot(A, B)
BA = np.dot(B, A)
print("\nAB:\n", AB)
print("\nBA:\n", BA)
print("AB == BA:", np.array_equal(AB, BA))


AB:
 [[0.64045182 0.36025178 0.1043664 ]
 [0.68884783 1.05213417 0.10809047]
 [0.92395053 0.92614509 0.18395994]]

BA:
 [[1.08997897 0.21578648 0.34596637]
 [1.46700748 0.35270088 0.57789054]
 [0.24109447 0.12092548 0.43386608]]
AB == BA: False


In [9]:
# (AB)C vs. A(BC)
ABC = np.dot(np.dot(A, B), C)
A_BC = np.dot(A, np.dot(B, C))
print("\n(AB)C:\n", ABC)
print("\nA(BC):\n", A_BC)
print("(AB)C == A(BC):", np.allclose(ABC, A_BC))


(AB)C:
 [[0.45095787 0.24746584 0.31942361]
 [0.51470045 0.44451311 0.82549986]
 [0.6820563  0.48802973 0.77050283]]

A(BC):
 [[0.45095787 0.24746584 0.31942361]
 [0.51470045 0.44451311 0.82549986]
 [0.6820563  0.48802973 0.77050283]]
(AB)C == A(BC): True


In [10]:
# A(B+C) vs. AB + AC
A_BC_sum = np.dot(A, B + C)
AB_AC_sum = np.dot(A, B) + np.dot(A, C)
print("\nA(B+C):\n", A_BC_sum)
print("\nAB + AC:\n", AB_AC_sum)
print("A(B+C) == AB + AC:", np.allclose(A_BC_sum, AB_AC_sum))


A(B+C):
 [[0.98122711 0.73249351 0.41305041]
 [1.30484387 1.24265102 0.24477627]
 [1.53904912 1.34374978 0.55004112]]

AB + AC:
 [[0.98122711 0.73249351 0.41305041]
 [1.30484387 1.24265102 0.24477627]
 [1.53904912 1.34374978 0.55004112]]
A(B+C) == AB + AC: True


In [11]:
# (A+B)C vs. AC + BC
AB_sum_C = np.dot(A + B, C)
AC_BC_sum = np.dot(A, C) + np.dot(B, C)
print("\n(A+B)C:\n", AB_sum_C)
print("\nAC + BC:\n", AC_BC_sum)
print("(A+B)C == AC + BC:", np.allclose(AB_sum_C, AC_BC_sum))


(A+B)C:
 [[0.76490669 0.72675058 1.0317487 ]
 [1.23604164 0.9059385  1.06958579]
 [1.1500161  0.55176632 0.40683677]]

AC + BC:
 [[0.76490669 0.72675058 1.0317487 ]
 [1.23604164 0.9059385  1.06958579]
 [1.1500161  0.55176632 0.40683677]]
(A+B)C == AC + BC: True


In [12]:
# (A+B)C vs. AC + BC
AB_sum_C = np.dot(A + B, C)
AC_BC_sum = np.dot(A, C) + np.dot(B, C)
print("\n(A+B)C:\n", AB_sum_C)
print("\nAC + BC:\n", AC_BC_sum)
print("(A+B)C == AC + BC:", np.allclose(AB_sum_C, AC_BC_sum))


(A+B)C:
 [[0.76490669 0.72675058 1.0317487 ]
 [1.23604164 0.9059385  1.06958579]
 [1.1500161  0.55176632 0.40683677]]

AC + BC:
 [[0.76490669 0.72675058 1.0317487 ]
 [1.23604164 0.9059385  1.06958579]
 [1.1500161  0.55176632 0.40683677]]
(A+B)C == AC + BC: True


In [13]:
# (AB)^T vs. B^T A^T
AB_T = np.dot(A, B).T
BT_AT = np.dot(B.T, A.T)
print("\n(AB)^T:\n", AB_T)
print("\nB^T A^T:\n", BT_AT)
print("(AB)^T == B^T A^T:", np.allclose(AB_T, BT_AT))


(AB)^T:
 [[0.64045182 0.68884783 0.92395053]
 [0.36025178 1.05213417 0.92614509]
 [0.1043664  0.10809047 0.18395994]]

B^T A^T:
 [[0.64045182 0.68884783 0.92395053]
 [0.36025178 1.05213417 0.92614509]
 [0.1043664  0.10809047 0.18395994]]
(AB)^T == B^T A^T: True


In [14]:
# det(AB) vs. det(A) det(B)
det_AB = np.linalg.det(np.dot(A, B))
det_A_det_B = np.linalg.det(A) * np.linalg.det(B)
print("\ndet(AB):", det_AB)
print("det(A) det(B):", det_A_det_B)
print("det(AB) == det(A) det(B):", np.allclose(det_AB, det_A_det_B))


det(AB): 0.01529926670700919
det(A) det(B): 0.01529926670700919
det(AB) == det(A) det(B): True


In [15]:
# (A^T)^T vs. A
ATT = A.T.T
print("\n(A^T)^T:\n", ATT)
print("\nA:\n", A)
print("(A^T)^T == A:", np.allclose(ATT, A))


(A^T)^T:
 [[0.24318961 0.13219738 0.49698339]
 [0.96344728 0.13637703 0.04021597]
 [0.72811964 0.24342123 0.41558862]]

A:
 [[0.24318961 0.13219738 0.49698339]
 [0.96344728 0.13637703 0.04021597]
 [0.72811964 0.24342123 0.41558862]]
(A^T)^T == A: True


In [16]:
# (cA)^T vs. cA^T
c = np.random.rand()  # Escalar aleatorio
cA_T = (c * A).T
cAT = c * A.T
print("\n(cA)^T:\n", cA_T)
print("\ncA^T:\n", cAT)
print("(cA)^T == cA^T:", np.allclose(cA_T, cAT))


(cA)^T:
 [[0.11068544 0.43850385 0.33139672]
 [0.06016838 0.06207071 0.11079086]
 [0.22619726 0.01830391 0.1891512 ]]

cA^T:
 [[0.11068544 0.43850385 0.33139672]
 [0.06016838 0.06207071 0.11079086]
 [0.22619726 0.01830391 0.1891512 ]]
(cA)^T == cA^T: True


In [17]:
# (A+B)^T vs. A^T + B^T
AB_sum_T = (A + B).T
AT_BT_sum = A.T + B.T
print("\n(A+B)^T:\n", AB_sum_T)
print("\nA^T + B^T:\n", AT_BT_sum)
print("(A+B)^T == A^T + B^T:", np.allclose(AB_sum_T, AT_BT_sum))


(A+B)^T:
 [[0.84589032 1.50619679 1.57750661]
 [1.09755727 1.02678764 0.2590683 ]
 [0.51529777 0.69553787 0.44231123]]

A^T + B^T:
 [[0.84589032 1.50619679 1.57750661]
 [1.09755727 1.02678764 0.2590683 ]
 [0.51529777 0.69553787 0.44231123]]
(A+B)^T == A^T + B^T: True


#4

El **Teorema de Laplace** es un método para calcular el determinante de una matriz cuadrada, particularmente útil para matrices de orden mayor a 2. Este teorema se basa en la expansión del determinante por los elementos de una fila o una columna cualquiera.



$$
\det(A) = \sum_{j=1}^n (-1)^{1+j} a_{1j} M_{1j}
$$

donde:
- $a_{1j}$ es el elemento de la primera fila y columna $j$.
- $M_{1j}$ es el menor asociado al elemento $a_{1j}$, es decir, el determinante de la submatriz de $3 \times 3$ que se obtiene al eliminar la fila 1 y la columna $j$.
- $(-1)^{1+j}$ es el signo correspondiente al cofactor del elemento $a_{1j}$.

Podemos realizar una función recursiva para el cálculo del determinante, sabiendo que el valor del determinante de una matriz de orden uno es el único elemento de esa matriz, y el de una matriz de orden superior a uno es la suma de cada uno de los elementos de una fila o columna por los Adjuntos a ese elemento, como en la función recursiva se emplea la misma función definida el cálculo lo haremos por Menor complementario, un ejemplo desarrollado por la primera fila sería:

$$
   \det (A_{j,j}) =
   \left \{
   \begin{array}{llcl}
      si & j = 1 & \to & a_{1,1} \\
                                 \\
      si & j > 1 & \to & \displaystyle \sum_{k=1}^j \; (-1)^{(1+k)} \cdot a_{1,k} \cdot \det( \alpha_{1,k})
   \end{array}
   \right .
$$

Realice una función que encuentre el determinante de una matriz usando la recursividad aqui planteada, explique explicitamente su código

In [18]:

def determinante(matriz):
    """Calcula el determinante de una matriz utilizando recursividad."""
    filas = len(matriz)
    columnas = len(matriz[0])


    # Caso recursivo: matriz nxn (n > 1)
    if filas == columnas: #Solamente puede calcularse el determinante para matrices cuadradas
        det = 0
        for j in range(columnas):
            # Calcular la submatriz según la expansión del teorema de laplace, quitando la primer fila y la primera columna, luego la primera fila y la segunda columna etc
            #Garda una submatriz que una vez calculado el dettermiante es reemplazada por la isguiente submatriz
            submatriz = [fila[:j] + fila[j+1:] for fila in matriz[1:]]

            # Calcular el cofactor que correponde al termino a1j del teorema de laplace, osea el elemento de la fila 1 y columna j
            cofactor = (-1) ** (1 + j + 1) * matriz[0][j]

            # Calcular el determinante de la submatriz recursivamente multiplicando el cofactor por la submatriz
            det += cofactor * determinante(submatriz)
        return det
    else:
        raise ValueError("La matriz debe ser cuadrada.")

#5

El método de Jacobi reescribe el sistema $ Ax = b $ descomponiendo la matriz $ A $ como:

$$
A = D + L + U,
$$

donde:
- $ D $: Matriz diagonal de $ A $,
- $ L $: Matriz triangular inferior sin la diagonal,
- $ U $: Matriz triangular superior sin la diagonal.

El sistema se reorganiza como:

$$
x = D^{-1}(b - (L + U)x).
$$

Esto se implementa iterativamente como:

$$
x_i^{(k+1)} = \frac{1}{a_{ii}} \left(b_i - \sum_{j \neq i} a_{ij} x_j^{(k)}\right),
$$

donde $ a_{ii} $ son los elementos diagonales de $ A $.

* Escriba una función explicita que realice de manera iterativa este método con una tol = 1e-7 y un máximo de 100 iteraciones. Defina una documentación clara que explique los métodos usados, lasa entradas y salidas.

* Para una matriz aleatoria 5$\times$ 5, encuentre la solución usando su función y determine el error con respecto a `solve` y el método de inversa de matriz.

In [19]:

def jacobi_method(A, b, tol=1e-7, max_iter=100):

    #Resuelve un sistema de ecuaciones lineales Ax = b utilizando el método de Jacobi.

    #Parámetros:
    #A (numpy.ndarray): Matriz de coeficientes (nxn).
    #b (numpy.ndarray): Vector de términos independientes (n).
    #tol (float): Tolerancia para la convergencia.
    #max_iter (int): Número máximo de iteraciones.

    #Retorna:
    #numpy.ndarray: Vector solución x.
    #int: Número de iteraciones realizadas.

    n = len(b)
    x = np.zeros(n)  # Inicialización de la solución
    x_new = np.zeros(n)

    for k in range(max_iter): # k cantidad de iteraciones, cuando k==max_iter y el error < tol entonces no converje
        for i in range(n):
            suma = 0
            for j in range(n):
                if i != j:
                    suma += A[i][j] * x[j]
            x_new[i] = (b[i] - suma) / A[i][i]

        # Verificar convergencia
        if np.linalg.norm(x_new - x) < tol:
            return x_new, k + 1

        x = x_new.copy()  # Actualizar la solución

    return x, max_iter  # No convergió dentro del número máximo de iteraciones

In [22]:
# Generar matriz aleatoria 5x5 y vector b
np.random.seed(0)  # Para reproducibilidad
A = np.random.rand(5, 5)
b = np.random.rand(5)

# Resolver el sistema utilizando el método de Jacobi
x_jacobi, iteraciones = jacobi_method(A, b)
print("Solución (Jacobi):", x_jacobi)
print("Iteraciones (Jacobi):", iteraciones)

Solución (Jacobi): [-3.04322736e+79 -3.94155137e+79 -2.13580918e+79 -2.55567732e+79
 -1.21036858e+80]
Iteraciones (Jacobi): 100


In [24]:
# Resolver el sistema utilizando numpy.linalg.solve
x_solve = np.linalg.solve(A, b)
print("Solución (solve):", x_solve)

# Resolver el sistema utilizando el método de inversa
A_inv = np.linalg.inv(A)
x_inv = np.dot(A_inv, b)
print("Solución (inversa):", x_inv)

# Calcular errores
error_jacobi_solve = np.linalg.norm(x_jacobi - x_solve)
error_jacobi_inv = np.linalg.norm(x_jacobi - x_inv)
print("Error Jacobi vs. solve:", error_jacobi_solve)
print("Error Jacobi vs. inversa:", error_jacobi_inv)


#El resultado es casi identico usando el metodo de jacobi, de la inversa o el solve

Solución (solve): [-7.44095801  5.42647186 -4.16168606  6.91406389 -0.98235854]
Solución (inversa): [-7.44095801  5.42647186 -4.16168606  6.91406389 -0.98235854]
Error Jacobi vs. solve: 1.350516339321266e+80
Error Jacobi vs. inversa: 1.350516339321266e+80


#6

Verifique que cualquier matriz hermitiana de 2 × 2 $ L $ puede escribirse como una suma de cuatro términos:

$$ L = a\sigma_x + b\sigma_y + c\sigma_z + dI $$

donde $ a $, $ b $, $ c $ y $ d $ son números reales.

Las cuatro matrices de Pauli son:

$$ \sigma_x = \begin{pmatrix} 0 & 1 \\ 1 & 0 \end{pmatrix}, \quad \sigma_y = \begin{pmatrix} 0 & -i \\ i & 0 \end{pmatrix}, \quad \sigma_z = \begin{pmatrix} 1 & 0 \\ 0 & -1 \end{pmatrix}, \quad I = \begin{pmatrix} 1 & 0 \\ 0 & 1 \end{pmatrix} $$




In [39]:

sigma_x = np.array([[0, 1], [1, 0]])
sigma_y = np.array([[0, -1j], [1j, 0]])
sigma_z = np.array([[1, 0], [0, -1]])
I = np.eye(2)  # Matriz identidad 2x2

In [40]:
def generar_matriz_hermitiana(a, b, c, d):
    #Genera una matriz hermitiana 2x2.
    return np.array([[d + c, a - 1j * b], [a + 1j * b, d - c]])

In [41]:
def descomponer_matriz_hermitiana(L):
    #Descompone una matriz hermitiana 2x2 en términos de las matrices de Pauli
    d = np.trace(L) / 2
    a = np.real(L[0, 1] + L[1, 0]) / 2
    b = np.imag(L[1, 0] - L[0, 1]) / 2
    c = (L[0, 0] - L[1, 1]) / 2
    return a, b, c, d

def reconstruir_matriz(a, b, c, d):
    #Reconstruye una matriz hermitiana a partir de los coeficientes
    return a * sigma_x + b * sigma_y + c * sigma_z + d * I

# Generar una matriz hermitiana aleatoria
a_rand, b_rand, c_rand, d_rand = np.random.rand(4)
L_rand = generar_matriz_hermitiana(a_rand, b_rand, c_rand, d_rand)

# Descomponer y reconstruir la matriz
a_calc, b_calc, c_calc, d_calc = descomponer_matriz_hermitiana(L_rand)
L_reconstruida = reconstruir_matriz(a_calc, b_calc, c_calc, d_calc)

# Verificar la igualdad
print("Matriz original:\n", L_rand)
print("\nMatriz reconstruida:\n", L_reconstruida)
print("\nIgualdad:", np.allclose(L_rand, L_reconstruida))

Matriz original:
 [[ 0.26934472+0.j          0.46631077-0.24442559j]
 [ 0.46631077+0.24442559j -0.04859444+0.j        ]]

Matriz reconstruida:
 [[ 0.26934472+0.j          0.46631077-0.24442559j]
 [ 0.46631077+0.24442559j -0.04859444+0.j        ]]

Igualdad: True
