In [ ]:
import numpy as np

In [ ]:
import scipy as sc

##1)

1)

In [ ]:
A=np.matrix([[1,-1,4],
             [3,2,-1],
             [2,1,-1]])

In [ ]:
Apolinom=np.poly(A)

In [ ]:
Apolinom

array([ 1., -2., -5.,  6.])

In [ ]:
Avalores=np.linalg.eig(A)[0]

In [ ]:
AP=np.linalg.eig(A)[1]

In [ ]:
Avalores

array([ 3., -2.,  1.])

In [ ]:
AP

matrix([[ 0.40824829,  0.57735027,  0.23570226],
        [ 0.81649658, -0.57735027, -0.94280904],
        [ 0.40824829, -0.57735027, -0.23570226]])

In [ ]:
np.linalg.inv(AP)

matrix([[ 1.22474487e+00, -1.08779196e-15,  1.22474487e+00],
        [ 5.77350269e-01,  5.77350269e-01, -1.73205081e+00],
        [ 7.07106781e-01, -1.41421356e+00,  2.12132034e+00]])

In [ ]:
D=np.linalg.inv(AP)*A*AP

In [ ]:
def cerosmatriz(A):
  for i in range(np.shape(A)[0]):
    for j in range(np.shape(A)[1]):
      if abs(A[i,j])<1E-7:
        A[i,j]=0
  return A

In [ ]:
cerosmatriz(D)

matrix([[ 3.,  0.,  0.],
        [ 0., -2.,  0.],
        [ 0.,  0.,  1.]])

2)

In [ ]:
B=np.matrix([[3,-5],
             [1,-1]])

In [ ]:
Bpolinom=np.poly(B)

In [ ]:
Bpolinom

array([ 1., -2.,  2.])

In [ ]:
Bvalores=np.linalg.eig(B)[0]

In [ ]:
Bvalores

array([1.+1.j, 1.-1.j])

In [ ]:
BP=np.linalg.eig(B)[1]

In [ ]:
D=np.linalg.inv(BP)*B*BP

In [ ]:
cerosmatriz(D)

matrix([[1.+1.j, 0.+0.j],
        [0.+0.j, 1.-1.j]])