In [ ]:
import numpy as np
import sympy

In [ ]:
A=np.random.randint(0,10,(3,4))

In [ ]:
A=A.astype(float)

In [ ]:
A=np.matrix(A)

In [ ]:
A

matrix([[0., 0., 7., 5.],
        [5., 3., 2., 6.],
        [0., 3., 1., 3.]])

In [ ]:
B=A.copy()

In [ ]:
def multiplicacion(A,F1,alpha):
  B=A.copy()
  x=alpha*A[F1,0:np.shape(A)[1]]
  B[F1,0:4]=x
  return B

In [ ]:
multiplicacion(B,0,9)

matrix([[ 0.,  0., 63., 45.],
        [ 5.,  3.,  2.,  6.],
        [ 0.,  3.,  1.,  3.]])

In [ ]:
def intercambio(A,F1,F2):
  Z=A.copy()
  Z[F1]=A[F2]
  Z[F2]=A[F1]
  return Z

In [ ]:
intercambio(A,0,1)

matrix([[5., 3., 2., 6.],
        [0., 0., 7., 5.],
        [0., 3., 1., 3.]])

In [ ]:
def sumamult(A,F1,F2,F3,theta):
  C=A.copy()
  x=theta*C[F1,0:np.shape(A)[1]]
  y=C[F2,0:np.shape(A)[1]]
  C[F3,0:np.shape(A)[1]]=x+y
  return C

In [ ]:
A

matrix([[0., 0., 7., 5.],
        [5., 3., 2., 6.],
        [0., 3., 1., 3.]])

In [ ]:
A

matrix([[0., 0., 7., 5.],
        [5., 3., 2., 6.],
        [0., 3., 1., 3.]])

In [ ]:
def reduccion(A):
  C=A.copy()
  for i in range(0,np.shape(A)[0]):
    if A[i,0]!=0:
      C=intercambio(C,0,i)
      break
  B=C.copy()
  for i in range(0,np.shape(A)[0]):
    if B[i,i]!=0:
      for j in range(0,np.shape(A)[0]):
        if i==j:
          x=0
        else:
          B=sumamult(B,i,j,j,-B[j,i]/B[i,i])
  for i in range(0,np.shape(A)[0]):
    B=multiplicacion(B,i,1/B[i,i])
  return B

In [ ]:
A

matrix([[0., 0., 7., 5.],
        [5., 3., 2., 6.],
        [0., 3., 1., 3.]])

In [ ]:
reduccion(B)

matrix([[ 1.        , -0.6       ,  0.        ,  0.        ],
        [-0.        ,  1.        , -0.        ,  0.76190476],
        [ 0.        ,  3.        ,  1.        ,  3.        ]])