In [818]:
import numpy as np
import matplotlib.pyplot as plt
import sympy as sp

In [819]:
def suma_filas(A,i,j,k):
   # por convención, la suma de filas remplazara la fila k

   A[k] = A[i] + A[j]

   return A


In [820]:
def escalar_filas(A,i,alpha):
  # por convención, la multiplicación por escalar de filas remplazara la fila i

  A[i] = alpha*A[i]
  return A

In [821]:
# Matriz sistema

S = np.array([[2,1,1,5],
              [4,1,1,1],
              [6,2,1,4]])


S_c = S.copy()



In [822]:
S

array([[2, 1, 1, 5],
       [4, 1, 1, 1],
       [6, 2, 1, 4]])

In [823]:
S_c = escalar_filas(S_c,0,-2)
S_c = suma_filas(S_c,1,0,1)
S_c = escalar_filas(S_c,0,-(1/2))


S_c

array([[ 2,  1,  1,  5],
       [ 0, -1, -1, -9],
       [ 6,  2,  1,  4]])

In [824]:
S_c = suma_filas(S_c,0,1,0)
S_c = escalar_filas(S_c,0,1/2)



S_c

array([[ 1,  0,  0, -2],
       [ 0, -1, -1, -9],
       [ 6,  2,  1,  4]])

In [825]:
S_c = escalar_filas(S_c,1,2)
S_c = suma_filas(S_c,1,2,2)
S_c = escalar_filas(S_c,0,-6)
S_c = suma_filas(S_c,0,2,2)
S_c = escalar_filas(S_c,0,-1/6)



S_c

array([[  1,   0,   0,  -2],
       [  0,  -2,  -2, -18],
       [  0,   0,  -1,  -2]])

In [826]:
S_c = escalar_filas(S_c,2,-2)
S_c = suma_filas(S_c,2,1,1)
S_c = escalar_filas(S_c,2,-1/2)

S_c

array([[  1,   0,   0,  -2],
       [  0,  -2,   0, -14],
       [  0,   0,  -1,  -2]])

In [827]:
S_c = escalar_filas(S_c,1,-1/2)
S_c = escalar_filas(S_c,2,-1)

S_c

array([[ 1,  0,  0, -2],
       [ 0,  1,  0,  7],
       [ 0,  0,  1,  2]])

In [828]:
def reduccion_matriz(A):
  for j in range(np.shape(A)[1]-1):
   for i in range(1,np.shape(A)[0]):
     alpha = (A[i][j]/A[j][j])

     A = escalar_filas(A,j,-alpha)
     A = suma_filas(A,j,i,i)
     A = escalar_filas(A,j,-1/alpha)

  return A

In [829]:
S = np.array([[2,1,1,5],
              [4,1,1,1],
              [6,2,1,4]])


S_c = S.copy()

In [830]:
S_c

array([[2, 1, 1, 5],
       [4, 1, 1, 1],
       [6, 2, 1, 4]])

In [831]:
S_c = reduccion_matriz(S_c)
S_c

array([[  2,   1,   1,   5],
       [  0,  -2,   0, -14],
       [  0,   0,  -2,  -4]])