In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as la

# Actividad 08: Algebra Lineal y Matrices

---
### Profesor: Juan Marcos Marín
### Nombre: ______
*Métodos computacionales 2024-II*

---

#1

Escriba una función que calcule el producto escalar y vectorial para dos vectores, compare sus resultados con `np.dot` y `np.cross`.

In [ ]:
v1=np.array([3,4,5])
v2=np.array([2,3,4])

In [ ]:
np.dot(v1,v2)

38

In [ ]:
cruz=np.cross(v1,v2)
print(cruz)

[ 1 -2  1]


In [ ]:
def p_punto(v1,v2):
  result=sum(v1[i]*v2[i] for i in range(len(v1)))
  return result

In [ ]:
def p_cruz(v1,v2):
  result= [
      v1[1] * v2[2] - v1[2] * v2[1],
      v1[2] * v2[0] - v1[0] * v2[2],
      v1[0] * v2[1] - v1[1] * v2[0]
  ]
  return result

In [ ]:
p_punto(v1,v2)

38

In [ ]:
p_cruz(v1,v2)

[1, -2, 1]

#2

Crear una función llamada `mulmat()` donde a partir de dos matrices $A$ y $B$ encuentre su multplicación. También realiza una función que calcule la transpuesta y otra el determinante de una matriz $3\times 3$. Compare sus resultado con `@`, `np.dot`, `transpose` y `la.det`.

In [ ]:
def mulmat(A,B):
  #verificamos que se pueden multiplicar
  if len(A[0])!=len(B): #longitud de columnas en la primera fil de A y longitud en filas de B
     raise ValueError("Las dimensiones de las matrices no son compatibles para la multiplicación.")

  m=int(len(A))
  s=int(len(B[0]))
  n=int(len(A[0]))

  result= np.zeros((m,s))

  #calculo
  for i in range(m):
    for j in range(s):
      for k in range(n):
        result[i,j]+=A[i,k]*B[k,j]

  return np.array(result)

In [ ]:
A=np.array([
    [2, 4],
    [5, 3]
])
B=np.array([
    [4, 2],
    [2, 3]
])

In [ ]:
len(A)

2

In [ ]:
mulmat(A,B)

array([[8., 4.],
       [6., 9.]])

In [ ]:
A@B

array([[8, 4],
       [6, 9]])

In [ ]:
def transpuesta(A):
  return [[A[j][i] for j in range(len(A))] for i in range(len(A[0]))]

In [ ]:
transpuesta(A)

[[2, 5], [4, 3]]

In [ ]:
def determinante(A):
  if len(A)!=3 or len(A[0])!=3:
    raise ValueError('NO')
  return  (A[0][0] * (A[1][1] * A[2][2] - A[1][2] * A[2][1])) - \
          (A[0][1] * (A[1][0] * A[2][2] - A[1][2] * A[2][0])) + \
          (A[0][2] * (A[1][0] * A[2][1] - A[1][1] * A[2][0]))

In [ ]:
A=np.array([
    [4, 2,5],
    [2, 3,7],
    [7, 8,1]
])

In [ ]:
determinante(A)

-143

In [ ]:
np.linalg.det(A)

-142.99999999999994

#3
Escriba tres matrices aleatorias $A$, $B$ y $C$ de $3\times 3$, y demuestre las siguientes relaciones

- $ \mathbf{A}\mathbf{B} \neq \mathbf{B}\mathbf{A} $, en general.
- $ (\mathbf{A}\mathbf{B})\mathbf{C} = \mathbf{A}(\mathbf{B}\mathbf{C}) $.
- $ \mathbf{A}(\mathbf{B} + \mathbf{C}) = \mathbf{A}\mathbf{B} + \mathbf{A}\mathbf{C} $.
- $ (\mathbf{A} + \mathbf{B})\mathbf{C} = \mathbf{A}\mathbf{C} + \mathbf{B}\mathbf{C} $.
- $ (\mathbf{A}\mathbf{B})^\top = \mathbf{B}^\top \mathbf{A}^\top $.
- $ \det(\mathbf{A}\mathbf{B}) = \det(\mathbf{A}) \det(\mathbf{B}) $.
- $ (\mathbf{A}^\top)^\top = \mathbf{A} $.
- $ (c\mathbf{A})^\top = c\mathbf{A}^\top $.
- $ (\mathbf{A} + \mathbf{B})^\top = \mathbf{A}^\top + \mathbf{B}^\top $.



In [ ]:
#matrices aleatorias
A=np.random.rand(3,3)
B=np.random.rand(3,3)
C=np.random.rand(3,3)


In [ ]:
#1

AB = np.dot(A, B)
BA = np.dot(B, A)
print("AB =\n", AB)
print("BA =\n", BA)


AB =
 [[1.65193113 1.02674611 0.94693293]
 [0.83126455 0.68638028 0.70646702]
 [1.23536073 0.65912272 0.63203103]]
BA =
 [[1.64563316 1.08253537 1.2706719 ]
 [1.10507968 0.72331849 0.91382887]
 [0.78987148 0.31979599 0.60139078]]


In [ ]:
#2

A_B= np.dot(A, B)
A_B_C_1=np.dot(A_B,C)

B_C = np.dot(B, C)
A_B_C_2=np.dot(A,B_C)
print("(AB)C =\n", A_B_C_1)
print("A(BC) =\n", A_B_C_2)

(AB)C =
 [[0.89880442 1.66897906 1.31691372]
 [0.60187782 0.88797281 0.89474829]
 [0.61806401 1.22966035 0.86412163]]
A(BC) =
 [[0.89880442 1.66897906 1.31691372]
 [0.60187782 0.88797281 0.89474829]
 [0.61806401 1.22966035 0.86412163]]


In [ ]:
#3
lado_i=np.dot(A,(B+C))
lado_d=np.dot(A,B)+np.dot(A,C)

print(lado_i)
print(lado_d)


[[2.33719339 2.04333538 1.95180841]
 [1.3541361  1.48936878 1.02634683]
 [1.62028067 1.38466446 1.32057273]]
[[2.33719339 2.04333538 1.95180841]
 [1.3541361  1.48936878 1.02634683]
 [1.62028067 1.38466446 1.32057273]]


In [ ]:
#4

lado_i = np.dot(A + B, C)
lado_d = np.dot(A, C) + np.dot(B, C)
print("(A + B)C =\n", lado_i)
print("AC + BC =\n", lado_d)


(A + B)C =
 [[1.21065641 1.97549812 1.62965557]
 [0.74898126 1.58232337 0.63964065]
 [0.6644299  0.92311769 1.28079968]]
AC + BC =
 [[1.21065641 1.97549812 1.62965557]
 [0.74898126 1.58232337 0.63964065]
 [0.6644299  0.92311769 1.28079968]]


In [ ]:
#5

lado_i = AB.T
lado_d = np.dot(B.T, A.T)
print("(AB)^T =\n", lado_i)
print("B^T A^T =\n", lado_d)


(AB)^T =
 [[1.65193113 0.83126455 1.23536073]
 [1.02674611 0.68638028 0.65912272]
 [0.94693293 0.70646702 0.63203103]]
B^T A^T =
 [[1.65193113 0.83126455 1.23536073]
 [1.02674611 0.68638028 0.65912272]
 [0.94693293 0.70646702 0.63203103]]


In [ ]:
# 6.

lado_i= np.linalg.det(A_B)
lado_d1= np.linalg.det(A)
lado_d2= np.linalg.det(B)
print("det(AB) =", lado_i)
print("det(A) det(B) =", lado_d1 * lado_d2)


det(AB) = 0.01995750918326532
det(A) det(B) = 0.019957509183265273


In [ ]:
# 7.
A_t_t = A.T.T
print("(A^T)^T =\n", A_t_t)
print("A =\n", A)

(A^T)^T =
 [[0.95358827 0.76413738 0.80503693]
 [0.77545418 0.01118113 0.68666812]
 [0.71611004 0.6005418  0.37936269]]
A =
 [[0.95358827 0.76413738 0.80503693]
 [0.77545418 0.01118113 0.68666812]
 [0.71611004 0.6005418  0.37936269]]


In [ ]:
# 8.
c = 10
cA_t = (c * A).T
c_A_t = c * A.T
print("(cA)^T =\n", cA_t)
print("cA^T =\n", c_A_t)

(cA)^T =
 [[9.53588268 7.75454178 7.1611004 ]
 [7.64137382 0.11181126 6.00541795]
 [8.05036932 6.86668124 3.79362688]]
cA^T =
 [[9.53588268 7.75454178 7.1611004 ]
 [7.64137382 0.11181126 6.00541795]
 [8.05036932 6.86668124 3.79362688]]


In [ ]:
#10

lado_i=(A+B).T
lado_d=(A).T+(B).T
print("(A+B)^T =\n", lado_i)
print("A^T+B^T =\n", lado_d)

(A+B)^T =
 [[1.90420605 1.62110394 0.83938459]
 [1.17675963 0.28241087 1.1297319 ]
 [1.39037372 0.81004545 0.74516629]]
A^T+B^T =
 [[1.90420605 1.62110394 0.83938459]
 [1.17675963 0.28241087 1.1297319 ]
 [1.39037372 0.81004545 0.74516629]]


#4

El **Teorema de Laplace** es un método para calcular el determinante de una matriz cuadrada, particularmente útil para matrices de orden mayor a 2. Este teorema se basa en la expansión del determinante por los elementos de una fila o una columna cualquiera.



$$
\det(A) = \sum_{j=1}^n (-1)^{1+j} a_{1j} M_{1j}
$$

donde:
- $a_{1j}$ es el elemento de la primera fila y columna $j$.
- $M_{1j}$ es el menor asociado al elemento $a_{1j}$, es decir, el determinante de la submatriz de $3 \times 3$ que se obtiene al eliminar la fila 1 y la columna $j$.
- $(-1)^{1+j}$ es el signo correspondiente al cofactor del elemento $a_{1j}$.

Podemos realizar una función recursiva para el cálculo del determinante, sabiendo que el valor del determinante de una matriz de orden uno es el único elemento de esa matriz, y el de una matriz de orden superior a uno es la suma de cada uno de los elementos de una fila o columna por los Adjuntos a ese elemento, como en la función recursiva se emplea la misma función definida el cálculo lo haremos por Menor complementario, un ejemplo desarrollado por la primera fila sería:

$$
   \det (A_{j,j}) =
   \left \{
   \begin{array}{llcl}
      si & j = 1 & \to & a_{1,1} \\
                                 \\
      si & j > 1 & \to & \displaystyle \sum_{k=1}^j \; (-1)^{(1+k)} \cdot a_{1,k} \cdot \det( \alpha_{1,k})
   \end{array}
   \right .
$$

Realice una función que encuentre el determinante de una matriz usando la recursividad aqui planteada, explique explicitamente su código

In [ ]:
def t_laplace(A):
  #cantidad de filas
  n=len(A)

  #definicion
  if n==1:
    return A[0,0]

  else:
    #inicializamos det
    determinante=0

    #iteramos sobre las columnas y la primera fila
    for j in range(n):

      submatriz=np.delete(A,0,axis=0)
      submatriz=np.delete(submatriz,j,axis=1)

      determinante+=(-1)**(1+j)*A[0,j]*t_laplace(submatriz)

  return determinante


In [ ]:
matriz=np.array([
    [4, 2,5],
    [2, 3,7],
    [7, 8,1]
])

In [ ]:
t_laplace(matriz)

-143

In [ ]:
np.linalg.det(matriz)

-142.99999999999994

#5

El método de Jacobi reescribe el sistema $ Ax = b $ descomponiendo la matriz $ A $ como:

$$
A = D + L + U,
$$

donde:
- $ D $: Matriz diagonal de $ A $,
- $ L $: Matriz triangular inferior sin la diagonal,
- $ U $: Matriz triangular superior sin la diagonal.

El sistema se reorganiza como:

$$
x = D^{-1}(b - (L + U)x).
$$

Esto se implementa iterativamente como:

$$
x_i^{(k+1)} = \frac{1}{a_{ii}} \left(b_i - \sum_{j \neq i} a_{ij} x_j^{(k)}\right),
$$

donde $ a_{ii} $ son los elementos diagonales de $ A $.

* Escriba una función explicita que realice de manera iterativa este método con una tol = 1e-7 y un máximo de 100 iteraciones. Defina una documentación clara que explique los métodos usados, lasa entradas y salidas.

* Para una matriz aleatoria 5$\times$ 5, encuentre la solución usando su función y determine el error con respecto a `solve` y el método de inversa de matriz.

In [ ]:
def jacobi(A,b,max_iter,tol):

  n=len(A[0]) #cantidad de ec en el sistema
  x=np.zeros(n)
  x_new=np.zeros(n)

  for iteracion in range(max_iter):
    for i in range(len(A)):
        #metodo matematico
        suma = sum(np.dot(A[i,j], x[j]) for j in range(n) if j!=i)
        x_new[i] = (b[i] - suma) / A[i, i]

    #verificacion de tol
    error=np.linalg.norm(x_new-x)
    if error<tol:
        return x_new

    #vuelve a iniciar para crear otro x_new
    x=np.copy(x_new)

  return x, 'no convergió, despues de max de iteraciones'

In [ ]:
#matriz aleatoria
A=np.random.rand(5,5)
b=np.random.rand(5,1)
b=b.reshape(5,1)

In [ ]:
print(A)
print(b)

[[0.08038096 0.2515622  0.83400335 0.88977939 0.15667889]
 [0.46730184 0.56564499 0.96893561 0.98126725 0.30568295]
 [0.03916431 0.35361337 0.75824449 0.9203927  0.93186193]
 [0.31244446 0.78866637 0.86621099 0.45296584 0.09794075]
 [0.35081907 0.30305758 0.14071302 0.93423835 0.54747411]]
[[0.20841206]
 [0.07987452]
 [0.46308227]
 [0.63329159]
 [0.35219998]]


In [ ]:
print(b)

[[0.20841206]
 [0.07987452]
 [0.46308227]
 [0.63329159]
 [0.35219998]]


In [ ]:
solucion=jacobi(A,b,100,1e-7)

<ipython-input-12-dd7401d226e9>:10: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  x_new[i] = (b[i] - suma) / A[i, i]


In [ ]:
print(solucion)

[-1.75047151e+75 -5.04774449e+74 -2.41071723e+74 -4.62291900e+74
 -3.95418967e+74]


In [ ]:
sol_exacta=np.linalg.solve(A,b)

In [ ]:
print(sol_exacta)

[[ 0.61185867]
 [ 3.45679646]
 [-0.45914181]
 [-3.62677619]
 [ 2.00751425]]


El metodo de jacobi solo funciona para matrices fuertemente diagonales

In [ ]:
z=np.array([
    [4, 2,2],
    [2, 10,1],
    [1, 2,9]
])
b_=np.array([
    [0.20841206],
    [0.07987452],
    [0.46308227],
])

In [ ]:
solucion=jacobi(z,b_,100,1e-7)

<ipython-input-12-dd7401d226e9>:10: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  x_new[i] = (b[i] - suma) / A[i, i]


In [ ]:
print(solucion)

[ 0.02904095 -0.00270351  0.04882758]


In [ ]:
solucion_exacta=np.linalg.solve(z,b_)
print(solucion_exacta)

[[ 0.02904097]
 [-0.0027035 ]
 [ 0.04882759]]


In [ ]:
solucion_inv=np.linalg.inv(z)@b_
print(solucion_inv)

[[ 0.02904097]
 [-0.0027035 ]
 [ 0.04882759]]


concluimos que cuando la matriz es fuertemente diagonal, el metodo jacobi funciona y el metodo de la inversa también porque ademas es invertible

#6

Verifique que cualquier matriz hermitiana de 2 × 2 $ L $ puede escribirse como una suma de cuatro términos:

$$ L = a\sigma_x + b\sigma_y + c\sigma_z + dI $$

donde $ a $, $ b $, $ c $ y $ d $ son números reales.

Las cuatro matrices de Pauli son:

$$ \sigma_x = \begin{pmatrix} 0 & 1 \\ 1 & 0 \end{pmatrix}, \quad \sigma_y = \begin{pmatrix} 0 & -i \\ i & 0 \end{pmatrix}, \quad \sigma_z = \begin{pmatrix} 1 & 0 \\ 0 & -1 \end{pmatrix}, \quad I = \begin{pmatrix} 1 & 0 \\ 0 & 1 \end{pmatrix} $$




In [ ]:
X=np.array([
    [0,1],
    [1,0]
])

Y=np.array([
    [0,-1j],
    [1j,0]
])

Z=np.array([
    [1j,0],
    [0,-1j]
])

I2=np.eye(2)

In [ ]:
#creamos una matriz hermitiana aleatoria
A = np.random.randn(2, 2) + 1j * np.random.randn(2, 2)  #compleja
H = (A + A.conj().T) / 2
print(A)
H

[[ 0.44014998-0.76767383j  0.30394251+0.31829013j]
 [-0.09251167-0.72096874j -0.73047159-0.94221132j]]


array([[ 0.44014998+0.j        ,  0.10571542+0.51962943j],
       [ 0.10571542-0.51962943j, -0.73047159+0.j        ]])

In [ ]:
H_= np.array([
    [0.44, 0.1 + 0.52*1j],
    [0.1 - 0.52*1j, -0.73]
    ])

In [ ]:
#resolvemos con sympy

from sympy import Eq, symbols, solve

In [ ]:
a,b,c,d= symbols('a,b,c,d')
L_comb=a*X+b*Y+c*Z+d*I2

In [ ]:
eq1=Eq(L_comb[0,0], H_[0,0])
eq2=Eq(L_comb[0,1], H_[0,1])
eq3=Eq(L_comb[1,0], H_[1,0])
eq4=Eq(L_comb[1,1], H_[1,1])

In [ ]:
print(eq1)
print(eq2)
print(eq3)
print(eq4)

Eq(1.0*I*c + 1.0*d, 0.44)
Eq(a - 1.0*I*b, 0.1 + 0.52*I)
Eq(a + 1.0*I*b, 0.1 - 0.52*I)
Eq(-1.0*I*c + 1.0*d, -0.73)


In [ ]:
sol= solve([eq1,eq2,eq3,eq4],(a,b,c,d))

In [ ]:
print(sol) #para el caso de H_

{a: 0.100000000000000, b: -0.520000000000000, c: -0.585*I, d: -0.145000000000000}
