In [1]:
import numpy as np
import torch as pt
import sympy as sp

# Autovalores, autovectores, diagonalización

Una matriz es diagonalizable cuando es semejante a una matriz diagonal. Esto significa que mediante un cambio de base, podemos reducir la matriz original a una forma diagonal. Para que una matriz sea diagonalizable, debe cumplir las siguientes condiciones:

**Autovectores linealmente independientes**: Una matriz $(A \in \mathbb{R}^{n \times n})$ es diagonalizable si y solo si tiene (n) autovectores linealmente independientes. Esto significa que los autovectores asociados a los autovalores deben ser linealmente independientes.

**Semejanza**: Existe una matriz invertible (P) tal que ($P^{-1}AP = D$), donde (D) es una matriz diagonal formada por los autovalores de (A).

La diagonalización es un proceso que transforma una matriz cuadrada ( A ) en una matriz diagonal ( D ) mediante una matriz invertible ( P ), tal que:

$P^{-1}AP = D$

La matriz diagonal ( D ) contiene los autovalores de ( A ) en la diagonal principal, y las columnas de ( P ) son los autovectores correspondientes a esos autovalores.

## Actividad:

Construir un programa que permita elevar una matriz a una potencia.


La exponencial de una matriz ( $e^A$) se define como la serie de Taylor de la función exponencial evaluada en la matriz ( A ):


\begin{equation}
e^A = I + A + \frac{1}{2!}A^2 + \frac{1}{3!}A^3 + \cdots = \sum_{n=0}^{\infty} \frac{1}{n!}A^n
\end{equation}


Donde ( $e^D$ ) es simplemente la matriz exponencial de la matriz diagonal ( D ), que es fácil de calcular porque solo implica elevar los autovalores de (A) a la potencia de (e):



\begin{equation}
e^A = Pe^DP^{-1}
\end{equation}


Exponencial de una matriz diagonal

\begin{equation}
e^D = \begin{bmatrix}
e^{\lambda_1} & 0 & \cdots & 0 \\
0 & e^{\lambda_2} & \cdots & 0 \\
\vdots & \vdots & \ddots & \vdots \\
0 & 0 & \cdots & e^{\lambda_n}
\end{bmatrix}
\end{equation}




In [2]:
from enum import auto
def power_of_matrix_diagonalization(A, n):
    # Diagonalizar la matriz
    autovalores, autovectores = np.linalg.eig(A)
    D = np.diag(autovalores)
    P = autovectores

    # Elevar la matriz diagonal a la potencia n
    D_n = np.diag(np.power(autovalores, n))

    # Obtener la matriz resultante en la base original
    result = np.dot(np.dot(P, D_n), np.linalg.inv(P))

    return result

# Ejemplo de uso
A = np.array([[1, 2], [3, 4]])  # Matriz de ejemplo
n = 3  # Potencia a la que queremos elevar la matriz

result = power_of_matrix_diagonalization(A, n)
print("Matriz A elevada a la potencia", n, "es:")
print(result)


Matriz A elevada a la potencia 3 es:
[[ 37.  54.]
 [ 81. 118.]]


In [3]:
def exp_of_matrix_diagonalization(A):
    # Diagonalizar la matriz
    autovalores, autovectores = np.linalg.eig(A)
    D = np.diag(np.exp(autovalores))
    P = autovectores

    # Obtener la matriz resultante en la base original
    result = np.dot(np.dot(P, D), np.linalg.inv(P))

    return result

# Ejemplo de uso
A = np.array([[1, 2], [3, 4]])  # Matriz de ejemplo

result = exp_of_matrix_diagonalization(A)
print("e^A es:")
print(result)


e^A es:
[[ 51.9689562   74.73656457]
 [112.10484685 164.07380305]]


# Pytorch

Definción de una matrix de tres formas:
Hasta ahora sabemos definir matrices como objetos de numpy y objetos de sympy, en la actualidad, el rápido crecimiento de las unidades de procesamiento gráfico GPU,  permite definir otro tipo de objetos que pueden acelerar el computo computacional.


- Como objeto de numpy
- Como objeto de sympy
- Como objeto de pytorch


La velocidad de ejecución entre PyTorch y Numpy puede variar dependiendo del tamaño de los datos y si se está utilizando o no la aceleración por GPU. Para operaciones con matrices pequeñas y cálculos que no requieren de la paralelización de una GPU, Numpy puede ser más rápido porque opera directamente en la CPU y la memoria principal. Sin embargo, para matrices grandes y operaciones que pueden ser paralelizadas, PyTorch con soporte de GPU puede ser significativamente más rápido.

Comparativa de comandos de ejecución entre pytorch, numpy  y sympy


| Operación | PyTorch | Numpy | SymPy |
|-----------|---------|-------|-------|
| Creación de una matriz | `torch.tensor([[1, 2], [3, 4]])` | `np.array([[1, 2], [3, 4]])` | `Matrix([[1, 2], [3, 4]])` |
| Transposición de una matriz | `torch.transpose(A, 0, 1)` | `A.T` o `np.transpose(A)` | `A.T` |
| Multiplicación de matrices | `torch.matmul(A, B)` | `np.dot(A, B)` o `A @ B` | `A * B` |
| Inversa de una matriz | `torch.inverse(A)` | `np.linalg.inv(A)` | `A**-1` |
| Determinante de una matriz | `torch.det(A)` | `np.linalg.det(A)` | `A.det()` |
| Autovalores y autovectores | `torch.eig(A, eigenvectors=True)` | `np.linalg.eig(A)` | `A.eigenvals()`, `A.eigenvects()` |



Ejemplo básico del comparativo de un problema de algebra lineal, rotación de un vector:

In [4]:

def matrixA(theta, tipo="numpy"):
  if(tipo=="np"):
    return np.array([[np.cos(theta),-np.sin(theta)],[np.sin(theta), np.cos(theta)]])
  elif(tipo=="sp"):
    return np.array([[sp.cos(theta),-sp.sin(theta)],[sp.sin(theta), sp.cos(theta)]])

  elif(tipo=="pt"):
    return pt.tensor([[np.cos(theta),-np.sin(theta)],[np.sin(theta), np.cos(theta)]])

  else:

    print("Define el tipo de variable que desea")


In [5]:
x = sp.Symbol("x")
M = sp.Matrix(matrixA(np.pi/4, tipo="sp"))
M

Matrix([
[0.707106781186548, -0.707106781186547],
[0.707106781186547,  0.707106781186548]])

In [6]:
x=np.pi/4
M = matrixA(x, tipo="np")
M

array([[ 0.70710678, -0.70710678],
       [ 0.70710678,  0.70710678]])

In [7]:
matrixA(x, tipo="pt")
M

array([[ 0.70710678, -0.70710678],
       [ 0.70710678,  0.70710678]])

Actividad: Resolver el problema de la potencia de una matriz empleando pytorch, construir.

In [8]:
import torch

def power_of_matrix_pytorch(A, n):
    A_tensor = torch.tensor(A, dtype=torch.float32)
    result = torch.eye(A.shape[0])  # Matriz identidad del mismo tamaño que A

    for _ in range(n):
        result = torch.matmul(result, A_tensor)  # Multiplicar la matriz resultado por A

    return result.numpy()

# Ejemplo de uso
A = torch.tensor([[1, 2], [3, 4]])  # Matriz de ejemplo
n = 3  # Potencia a la que queremos elevar la matriz

result = power_of_matrix_pytorch(A, n)
print("Matriz A elevada a la potencia", n, "es:")
print(result)


Matriz A elevada a la potencia 3 es:
[[ 37.  54.]
 [ 81. 118.]]


<ipython-input-8-e4f452d13fee>:4: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  A_tensor = torch.tensor(A, dtype=torch.float32)
