In [5]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as al
import random
from sympy import Matrix, symbols, init_printing
import sympy as sp

# Actividad 08: Algebra Lineal y Matrices

---
### Profesor: Juan Marcos Marín
### Nombre: Soleil Dayana Niño Murcia
*Métodos computacionales 2024-II*

---

#1

Escriba una función que calcule el producto escalar y vectorial para dos vectores, compare sus resultados con `np.dot` y `np.cross`.

In [ ]:
# Vectores para prueba (deben ser de dimensión 3 porque el producto vectorial sólo está definido en R3)
u = np.array([1, 2, 3])
v = np.array([3, 2, 1])

In [ ]:
def pdcto_interno(u,v):
  p = 0
  for i in range(len(u)):
    p += u[i]*v[i]
  return p

In [ ]:
print('Producto interno por mi función:', pdcto_interno(u,v), '\nProducto interno por np.dot:', np.dot(u,v), '\n\n¿Los valores son equivalentes?')

if np.array_equal(pdcto_interno(u,v), np.dot(u,v)):
  print("Verdadero")
else:
  print("Falso")

Producto interno por mi función: 10 
Producto interno por np.dot: 10 

¿Los valores son equivalentes?
Verdadero


In [ ]:
def pdcto_vectorial(u,v):
  """
  Recuerde que el producto vectorial está definido
  ÚNICAMENTE para vectores en R3
  """
  w1 = u[1] * v[2] - u[2] * v[1]
  w2 = u[2] * v[0] - u[0] * v[2]
  w3 = u[0] * v[1] - u[1] * v[0]
  w = np.array([w1, w2, w3])

  return w

In [ ]:
print('Producto vectorial por mi función:', pdcto_vectorial(u,v), '\nProducto vectorial por np.cross:', np.cross(u,v), '\n\n¿Los vectores son equivalentes?')

if np.array_equal(pdcto_vectorial(u,v), np.cross(u,v)):
  print("Verdadero")
else:
  print("Falso")

Producto vectorial por mi función: [-4  8 -4] 
Producto vectorial por np.cross: [-4  8 -4] 

¿Los vectores son equivalentes?
Verdadero


#2

Crear una función llamada `mulmat()` donde a partir de dos matrices $A$ y $B$ encuentre su multplicación. También realiza una función que calcule la transpuesta y otra el determinante de una matriz $3\times 3$. Compare sus resultado con `@`, `np.dot`, `transpose` y `la.det`.

In [ ]:
# Matrices de prueba
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [5, 2, 6]
], dtype = float)

B = np.array([
    [7, 8, 9],
    [10, 11, 12],
    [13, 14, 15]
],dtype = float)

### Función para producto matricial

In [ ]:
def mulmat(A,B):
  C = np.zeros((len(A), len(B[0])))
  m_a, n_a = len(A), len(A[0])
  m_b, n_b = len(B), len(B[0])
  if m_a != n_b:
    raise ValueError("Las dimensiones de las matrices no son compatibles para la multiplicación.")

  C += [[0 for _ in range(n_b)] for _ in range(m_a)]
  for i in range(m_a):
    for j in range(n_b):
      for k in range(n_a):
        C[i][j] += A[i][k] * B[k][j]
  return C

In [ ]:
print('Producto por mi función:\n', mulmat(A,B), '\n\nProducto np.dot:\n', np.dot(A,B))
print('\n\n¿Los valores son equivalentes?')

if np.array_equal(mulmat(A,B), np.dot(A,B)):
  print("Verdadero")
else:
  print("Falso")

Producto por mi función:
 [[ 66.  72.  78.]
 [156. 171. 186.]
 [133. 146. 159.]] 

Producto np.dot:
 [[ 66.  72.  78.]
 [156. 171. 186.]
 [133. 146. 159.]]


¿Los valores son equivalentes?
Verdadero


### Función para Transpuesta

In [ ]:
def transpuesta(A):
  C = np.zeros((len(A[0]), len(A)))
  for i in range(len(A)):
    for j in range(len(A[0])):
      C[j][i] = A[i][j]
  return C

In [ ]:
print('A:\n', A, '\n\nA Transpuesta:\n', transpuesta(A))

A:
 [[1. 2. 3.]
 [4. 5. 6.]
 [5. 2. 6.]] 

A Transpuesta:
 [[1. 4. 5.]
 [2. 5. 2.]
 [3. 6. 6.]]


In [ ]:
print('Transpuesta por mi función:\n', transpuesta(A), '\n\nTranspuesta por np.transpose:\n', np.transpose(A))
print('\n\n¿Las matrices son equivalentes?')

if np.array_equal(transpuesta(A), np.transpose(A)):
  print("Verdadero")
else:
  print("Falso")

Transpuesta por mi función:
 [[1. 4. 5.]
 [2. 5. 2.]
 [3. 6. 6.]] 

Transpuesta por np.transpose:
 [[1. 4. 5.]
 [2. 5. 2.]
 [3. 6. 6.]]


¿Las matrices son equivalentes?
Verdadero


### Función para determinante

In [ ]:
def det(A):
  if len(A) == 3: # Aplica método de Sarrus
    suma = A[0][0]*A[1][1]*A[2][2] + A[0][1]*A[1][2]*A[2][0] + A[0][2]*A[1][0]*A[2][1]
    resta = A[0][2]*A[1][1]*A[2][0] + A[0][1]*A[1][0]*A[2][2] + A[0][0]*A[1][2]*A[2][1]
    return suma - resta

In [ ]:
al.det(A),  det(A)
print('Determinante por mi función:', det(A), '\nDeterminante por np.linalg.det:', np.linalg.det(A), '\n\n¿Los valores son equivalentes?')
if np.array_equal(det(A), np.linalg.det(A)):
  print("Verdadero")
else:
  print("Falso")

Determinante por mi función: -21.0 
Determinante por np.linalg.det: -21.0 

¿Los valores son equivalentes?
Verdadero


#3
Escriba tres matrices aleatorias $A$, $B$ y $C$ de $3\times 3$, y demuestre las siguientes relaciones



In [ ]:
A, B, C = np.random.randint(1, 10, size = (3,3)), np.random.randint(1, 10, size = (3,3)), np.random.randint(1, 10, size = (3,3))

In [ ]:
print('A:\n', A, '\n\nB:\n', B, '\n\nC:\n', C)

A:
 [[4 8 1]
 [3 4 8]
 [8 7 8]] 

B:
 [[1 7 4]
 [3 7 5]
 [4 7 2]] 

C:
 [[6 8 8]
 [9 3 2]
 [6 3 1]]



- $ \mathbf{A}\mathbf{B} \neq \mathbf{B}\mathbf{A} $, en general.


In [ ]:
# AB != BA
AB = A @ B
BA = B @ A
print('AB:\n', AB, '\n\nBA:\n', BA)

print('\n\n\nNote que','las matrices son diferentes') if not np.allclose(AB, BA) else print('las matrices son iguales')
# np.allclose(a, b, rtol=1e-05, atol=1e-08): Compara las matrices a y b elemento por elemento. Con rtol: Tolerancia relativa (por defecto, 1e-05) y atol: Tolerancia absoluta (por defecto, 1e-08).

AB:
 [[ 32  91  58]
 [ 47 105  48]
 [ 61 161  83]] 

BA:
 [[57 64 89]
 [73 87 99]
 [53 74 76]]



Note que las matrices son diferentes


- $ (\mathbf{A}\mathbf{B})\mathbf{C} = \mathbf{A}(\mathbf{B}\mathbf{C}) $.


In [ ]:
BC = B @ C
AB_C = AB @ C
A_BC = A @ BC
print('AB_C:\n', AB_C, '\n\nA_BC:\n', A_BC)
print('\n\n\nNote que','las matrices son iguales') if np.allclose(AB_C, A_BC) else print('las matrices son diferentes')

AB_C:
 [[1359  703  496]
 [1515  835  634]
 [2313 1220  893]] 

A_BC:
 [[1359  703  496]
 [1515  835  634]
 [2313 1220  893]]



Note que las matrices son iguales


- $ \mathbf{A}(\mathbf{B} + \mathbf{C}) = \mathbf{A}\mathbf{B} + \mathbf{A}\mathbf{C} $.


In [ ]:
BmasC = B + C
AB_mas_C = A @ BmasC

AC = A @ C
AB_mas_AC = AB + AC

print('A(B+C):\n', AB_mas_C, '\n\nAB+AC:\n', AB_mas_AC)
print('\n\n\nNote que','las matrices son iguales') if np.allclose(AB_mas_C, AB_mas_AC) else print('las matrices son diferentes')

A(B+C):
 [[134 150 107]
 [149 165  88]
 [220 270 169]] 

AB+AC:
 [[134 150 107]
 [149 165  88]
 [220 270 169]]



Note que las matrices son iguales


- $ (\mathbf{A} + \mathbf{B})\mathbf{C} = \mathbf{A}\mathbf{C} + \mathbf{B}\mathbf{C} $.


In [ ]:
A_mas_B = A + B
A_mas_B_C = A_mas_B @ C
A_C_mas_B_C = AC + BC

print('(A+B)C:\n', A_mas_B_C, '\n\nAC+BC:\n', A_C_mas_B_C)

print('\n\n\nNote que','las matrices son iguales') if np.allclose(A_mas_B_C, A_C_mas_B_C) else print('las matrices son diferentes')

(A+B)C:
 [[195 100  75]
 [213 120  83]
 [258 168 134]] 

AC+BC:
 [[195 100  75]
 [213 120  83]
 [258 168 134]]



Note que las matrices son iguales


- $ (\mathbf{A}\mathbf{B})^\top = \mathbf{B}^\top \mathbf{A}^\top $.


In [ ]:
AB_t =  np.round(np.transpose(AB), 4)
B_t, A_t = np.transpose(B), np.transpose(A)
B_t_A_t = np.round(B_t @ A_t, 4)

print('(AB)^t:\n', AB_t, '\n\nB^t*A^t:\n', B_t_A_t)
print('\n\n\nNote que','las matrices son iguales') if np.allclose(AB_t, B_t_A_t) else print('las matrices son diferentes')

(AB)^t:
 [[ 32  47  61]
 [ 91 105 161]
 [ 58  48  83]] 

B^t*A^t:
 [[ 32  47  61]
 [ 91 105 161]
 [ 58  48  83]]



Note que las matrices son iguales


- $ \det(\mathbf{A}\mathbf{B}) = \det(\mathbf{A}) \det(\mathbf{B}) $.



In [ ]:
det_AB = np.linalg.det(AB)
det_A = np.linalg.det(A)
det_B = np.linalg.det(B)

prod = det_A * det_B

print('det(AB):     ', np.round(det_AB,5), '\ndet(A)det(B):', np.round(prod,5))
print('\n\n\nNote que','los valores son iguales') if np.allclose(det_AB, prod) else print('los valores son diferentes')

det(AB):      10437.0 
det(A)det(B): 10437.0



Note que los valores son iguales


- $ (\mathbf{A}^\top)^\top = \mathbf{A} $.


In [ ]:
Att = np.transpose(A_t)

print('\n\nA^t^t:\n', np.round(Att,3), '\n\nA:\n', np.round(A,3))
print('\n\n\nNote que','las matrices son iguales') if np.allclose(Att, A) else print('las matrices son diferentes')



A^t^t:
 [[4 8 1]
 [3 4 8]
 [8 7 8]] 

A:
 [[4 8 1]
 [3 4 8]
 [8 7 8]]



Note que las matrices son iguales


- $ (c\mathbf{A})^\top = c\mathbf{A}^\top $.


In [ ]:
# La propiedad se cumple siempre que c sea escalar
c = np.random.rand(1)
cA_t = np.transpose(c * A)
cAt = c * A_t

print('(cA)^t:\n', np.round(cA_t,3), '\n\ncA^t:\n', np.round(cAt,3))
print('\n\n\nNote que','las matrices son iguales') if np.allclose(cA_t, cAt) else print('las matrices son diferentes')

(cA)^t:
 [[3.121 2.341 6.243]
 [6.243 3.121 5.463]
 [0.78  6.243 6.243]] 

cA^t:
 [[3.121 2.341 6.243]
 [6.243 3.121 5.463]
 [0.78  6.243 6.243]]



Note que las matrices son iguales


- $ (\mathbf{A} + \mathbf{B})^\top = \mathbf{A}^\top + \mathbf{B}^\top $.

In [ ]:
AmasB_T = np.transpose(A_mas_B)
At_mas_Bt = A_t + B_t

print('(A+B)^t:\n', np.round(AmasB_T,3), '\n\nA^t+B^t:\n', np.round(At_mas_Bt,3))
print('\n\n\nNote que','las matrices son iguales') if np.allclose(AmasB_T, At_mas_Bt) else print('las matrices son diferentes')

(A+B)^t:
 [[ 5  6 12]
 [15 11 14]
 [ 5 13 10]] 

A^t+B^t:
 [[ 5  6 12]
 [15 11 14]
 [ 5 13 10]]



Note que las matrices son iguales


#4

El **Teorema de Laplace** es un método para calcular el determinante de una matriz cuadrada, particularmente útil para matrices de orden mayor a 2. Este teorema se basa en la expansión del determinante por los elementos de una fila o una columna cualquiera.



$$
\det(A) = \sum_{j=1}^n (-1)^{1+j} a_{1j} M_{1j}
$$

donde:
- $a_{1j}$ es el elemento de la primera fila y columna $j$.
- $M_{1j}$ es el menor asociado al elemento $a_{1j}$, es decir, el determinante de la submatriz de $3 \times 3$ que se obtiene al eliminar la fila 1 y la columna $j$.
- $(-1)^{1+j}$ es el signo correspondiente al cofactor del elemento $a_{1j}$.

Podemos realizar una función recursiva para el cálculo del determinante, sabiendo que el valor del determinante de una matriz de orden uno es el único elemento de esa matriz, y el de una matriz de orden superior a uno es la suma de cada uno de los elementos de una fila o columna por los Adjuntos a ese elemento, como en la función recursiva se emplea la misma función definida el cálculo lo haremos por Menor complementario, un ejemplo desarrollado por la primera fila sería:

$$
   \det (A_{j,j}) =
   \left \{
   \begin{array}{llcl}
      si & j = 1 & \to & a_{1,1} \\
                                 \\
      si & j > 1 & \to & \displaystyle \sum_{k=1}^j \; (-1)^{(1+k)} \cdot a_{1,k} \cdot \det( \alpha_{1,k})
   \end{array}
   \right .
$$

Realice una función que encuentre el determinante de una matriz usando la recursividad aqui planteada, explique explicitamente su código

In [42]:
def determinante_laplace(A):
  """
  Calcula el determinante de una matriz cuadrada utilizando el Teorema de Laplace de forma recursiva.

  Args:
      A: Una matriz cuadrada representada como lista de listas o array NumPy.

  Returns:
      El determinante de la matriz.
    """
  n = len(A)

  # Caso base
  if n == 1:
      return A[0, 0]

  # Caso base: matriz 2x2
  if n == 2:
      return A[0, 0]*A[1, 1] - A[0, 1]*A[1, 0]

  sum = 0
  # Expansión por la primera fila
  for j in range(n):
    # Se elimina la fila 0 y la columna j para obtener la submatriz
    submatriz = np.delete(np.delete(A, 0, axis=0), j, axis=1)
    # Llamada recursiva
    sub_det = determinante_laplace(submatriz)

    sum += (-1)**j * A[0, j] * sub_det

  return sum

In [43]:
# Prueba de comparacion con matriz aleatoria
C = np.random.randint(1, 10, size = (4,4))
print('Matriz aleatoria:\n', C)

Matriz aleatoria:
 [[8 3 1 5]
 [2 2 8 8]
 [6 2 7 9]
 [8 2 6 6]]


In [44]:
det_myfunc = determinante_laplace(C)
print('Determinante por mi función:', det_myfunc, '\nDeterminante por np.linalg.det:', round(np.linalg.det(C),3))

Determinante por mi función: -240 
Determinante por np.linalg.det: -240.0


#5

El método de Jacobi reescribe el sistema $ Ax = b $ descomponiendo la matriz $ A $ como:

$$
A = D + L + U,
$$

donde:
- $ D $: Matriz diagonal de $ A $,
- $ L $: Matriz triangular inferior sin la diagonal,
- $ U $: Matriz triangular superior sin la diagonal.

El sistema se reorganiza como:

$$
x = D^{-1}(b - (L + U)x).
$$

Esto se implementa iterativamente como:

$$
x_i^{(k+1)} = \frac{1}{a_{ii}} \left(b_i - \sum_{j \neq i} a_{ij} x_j^{(k)}\right),
$$

donde $ a_{ii} $ son los elementos diagonales de $ A $.

* Escriba una función explicita que realice de manera iterativa este método con una tol = 1e-7 y un máximo de 100 iteraciones. Defina una documentación clara que explique los métodos usados, lasa entradas y salidas.

In [127]:
def Jacobi(A, b, tol=1e-7, max_iter=100):
  """
  Resuelve un sistema de ecuaciones lineales Ax = b utilizando el método iterativo de Jacobi.

  Args:
      A (array_like): Matriz NumPy de dimensiones (n, n) que representa los coeficientes del sistema.
      b (array_like): Vector NumPy de dimensión (n,) que representa el lado derecho del sistema.
      tol (float): Tolerancia para la convergencia (por defecto 1e-7).
      max_iter (int): Número máximo de iteraciones permitidas (por defecto 100).

  Returns:
      x (np.ndarray): Solución aproximada del sistema Ax = b.
                        Si el método converge, se devuelve la aproximación final.
                        Si no converge en max_iter iteraciones, se devuelve la última aproximación.

  Raises:
      ValueError: Si A no es una matriz cuadrada o el tamaño de b no coincide con A.
  """
  # Convertir A y b a arrays NumPy y verificar dimensiones
  A = np.array(A, dtype=float)
  b = np.array(b, dtype=float)
  n, m = A.shape

  # Vector solución inicial
  x = np.zeros(n, dtype=float)

  for k in range(max_iter):
      x_new = np.zeros_like(x)

      # Actualización de cada componente de x
      for i in range(n):
          suma = 0.0
          for j in range(n):
              if j != i:
                  suma += A[i, j] * x[j]
          x_new[i] = (b[i] - suma) / A[i, i]

      # Comprobar convergencia usando la norma infinito
      if np.linalg.norm(x_new - x, ord=np.inf) < tol:
          print(f"Convergió luego de {k+1} iteraciones.")
          return x_new

      # Actualizar la solución para la siguiente iteración
      x = x_new

  print(f"No converge luego de {max_iter} iteraciones.")
  return x

* Para una matriz aleatoria 5$\times$ 5, encuentre la solución usando su función y determine el error con respecto a `solve` y el método de inversa de matriz.

In [128]:
m_aleatoria = np.random.randint(1,10, size = (5,5))
b_aleatorio = np.random.randint(1,10, size = (5,1))

print('Matriz aleatoria:\n', m_aleatoria)
print('\nVector aleatorio:\n', b_aleatorio)

Matriz aleatoria:
 [[3 6 6 4 9]
 [2 3 4 9 5]
 [8 6 3 4 5]
 [7 4 3 8 8]
 [8 3 3 9 4]]

Vector aleatorio:
 [[8]
 [5]
 [4]
 [2]
 [8]]


In [129]:
solucion = Jacobi(m_aleatoria, b_aleatorio)  # No me sirve bien la función pero ya intenté de muchas maneras
print('Solución por mi función:\n', solucion)

No converge luego de 100 iteraciones.
Solución por mi función:
 [-9.80981034e+76 -7.02136337e+76 -9.49298727e+76 -3.76843253e+76
 -6.79570743e+76]


<ipython-input-127-1c58280cf5d9>:36: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  x_new[i] = (b[i] - suma) / A[i, i]


In [130]:
# Método Solve para comparar nuestra función
solbysolve = al.solve(m_aleatoria, b_aleatorio)
print('Solución por solve:\n\n', solbysolve)

Solución por solve:

 [[ 1.06870229]
 [-1.84351145]
 [ 4.30534351]
 [-0.48473282]
 [-0.89312977]]


In [131]:
# Método de la inversa de la matriz

solbyinv = np.linalg.inv(m_aleatoria) @ b_aleatorio
print('Solución por la inversa de la matriz:\n\n', solbyinv)

Solución por la inversa de la matriz:

 [[ 1.06870229]
 [-1.84351145]
 [ 4.30534351]
 [-0.48473282]
 [-0.89312977]]


In [132]:
# Comparación de errores
error_solve = np.linalg.norm(solbysolve - solucion, ord = np.inf)
error_inv = np.linalg.norm(solbyinv - solucion, ord = np.inf)
error_solve_inv = np.linalg.norm(solbyinv - solbysolve)
print('Error por solve:', round(error_solve,18), '\nError por la inversa de la matriz:', round(error_inv,18), '\nError entre solve y método de la inversa: ', round(error_solve_inv,16))

Error por solve: 3.688830092989772e+77 
Error por la inversa de la matriz: 3.688830092989772e+77 
Error entre solve y método de la inversa:  3e-16


#6

Verifique que cualquier matriz hermitiana de 2 × 2 $ L $ puede escribirse como una suma de cuatro términos:

$$ L = a\sigma_x + b\sigma_y + c\sigma_z + dI $$

donde $ a $, $ b $, $ c $ y $ d $ son números reales.

Las cuatro matrices de Pauli son:

$$ \sigma_x = \begin{pmatrix} 0 & 1 \\ 1 & 0 \end{pmatrix}, \quad \sigma_y = \begin{pmatrix} 0 & -i \\ i & 0 \end{pmatrix}, \quad \sigma_z = \begin{pmatrix} 1 & 0 \\ 0 & -1 \end{pmatrix}, \quad I = \begin{pmatrix} 1 & 0 \\ 0 & 1 \end{pmatrix} $$




In [45]:
# Matrices de Pauli
Px, Py, Pz, I = np.array([[0,1], [1,0]]) , (np.array([[0,-1j], [1j,0]])), np.array([[1,0], [0,-1]]) , np.array([[1,0], [0,1]])

In [47]:
a, b, c, d = sp.symbols('a b c d', real = True)
incognitas = [a, b, c, d]

def descomponer_matriz_hermitiana(L):
  """
  Descompone una matriz hermitiana L en la forma:
  L = a * sigma_x + b * sigma_y + c * sigma_z + d * I
  donde a, b, c, d son los coeficientes reales y retorna los valores
  de las constantes a, b, c y d.
  """
  d = np.trace(L) / 2
  c = (L[0, 0] - L[1, 1]) / 2
  a = np.real(L[0, 1])
  b = -np.imag(L[0, 1])

  return a, b, c, d

In [48]:
hermitiana_de_prueba = np.array([[-1, 3j +1], [-3j +1, 5]]) # 2x2
a, b, c, d = descomponer_matriz_hermitiana(hermitiana_de_prueba)
print('Coeficientes obtenidos:\n\na:', a, '\nb:', b, '\nc:', c, '\nd:', d) # Note que son reales todos porque las partes imaginarias son 0

Coeficientes obtenidos:

a: 1.0 
b: -3.0 
c: (-3+0j) 
d: (2+0j)


In [49]:
# Reconstrucción de la matriz
reconstruida = a * Px + b * Py + c * Pz + d * I
print('Matriz reconstruida:\n\n', reconstruida)

Matriz reconstruida:

 [[-1.+0.j  1.+3.j]
 [ 1.-3.j  5.+0.j]]


In [50]:
print(hermitiana_de_prueba)

[[-1.+0.j  1.+3.j]
 [ 1.-3.j  5.+0.j]]


In [51]:
print('Note que','las matriz reconstruida y la original son iguales, comprobando el teorema.') if np.allclose(hermitiana_de_prueba, reconstruida) else print('las matriz reconstruida y la original son diferentes')


Note que las matriz reconstruida y la original son iguales, comprobando el teorema.
