In [5]:
import numpy as np
import sympy as sp
import scipy as sc

In [6]:
def intercambio(M,i,j):
  M = M.astype(float)
  s = M.shape
  if(i >= s[0] | j >= s[0]):
    print("El número de fila a intercambiar excede el número de filas de la matriz")
    return None
  print("intercambiar fila ",i," con la fila ",j)
  aux = M[i].copy()
  M[i] = M[j]
  M[j] = aux
  return M

def multiplicarEscalar(M,i,escalar):
  M = M.astype(float)
  s = M.shape
  if(i >= s[0]):
    print("El número de fila excede el número de filas de la matriz")
    return None
  print("multiplicar la fila ",i, " por ",escalar)
  aux = M[i].copy()
  M[i]= aux*escalar
  return M

def sumar_i_j_set_j(M,i,j,multiplo_i = 1):
  M = M.astype(float)
  s = M.shape
  if(i >= s[0] | j >= s[0]):
    print("El número de filas a sumar exceden el número de filas de la matriz")
    return None
  print("Sumar ",multiplo_i, " veces la fila ", i ," a la fila ",j)
  aux = M[j].copy()
  M[j] = (M[i]*multiplo_i) + aux
  return M

In [7]:
def gaussJorndan(M):
  s = M.shape
  B = M.copy()
  B = B.astype(float)
  max = s[0]
  if (s[0]>s[1]):
    max = s[1]
  for i in range(0,max):
    if(B[i,i] == 0):
      for j in range(i+1,s[0]):
        if(B[j,i] != 0):
          B = intercambio(B,i,j)
          print(B)
          break
    for j in range(i+1,s[0]):
      if ((B[j,i]!=0)):
        multiplo_i = -1* B[j,i]/B[i,i]
        B = sumar_i_j_set_j(B,i,j,multiplo_i)
        print(B)
  return B

In [ ]:
def reduccionCompleta(M):
  s = M.shape
  B = M.copy()
  B = B.astype(float)
  max = s[0]
  if (s[0]>s[1]):
    max = s[1]
  for i in range(0,max):
    if(B[i,i] == 0):
      for j in range(i+1,s[0]):
        if(B[j,i] != 0):
          B = intercambio(B,i,j)
          print(B)
          break
    if(B[i,i] != 1):
      escalar = 1/B[i,i];
      B = multiplicarEscalar(B,i,escalar)
      print(B)
    for j in range(0,s[0]):
      if ((i != j) & (B[j,i]!=0)):
        multiplo_i = -1* B[j,i]
        B = sumar_i_j_set_j(B,i,j,multiplo_i)
        print(B)
  return B

In [ ]:
A = np.matrix(np.array([[2,1,-1,5],[4,1,1,1],[6,2,1,4]]))
print(A)

[[ 2  1 -1  5]
 [ 4  1  1  1]
 [ 6  2  1  4]]


In [ ]:
C = gaussJorndan(A)
print("Matriz Triangular ")
print(C)

Sumar  -2.0  veces la fila  0  a la fila  1
[[ 2.  1. -1.  5.]
 [ 0. -1.  3. -9.]
 [ 6.  2.  1.  4.]]
Sumar  -3.0  veces la fila  0  a la fila  2
[[  2.   1.  -1.   5.]
 [  0.  -1.   3.  -9.]
 [  0.  -1.   4. -11.]]
Sumar  -1.0  veces la fila  1  a la fila  2
[[ 2.  1. -1.  5.]
 [ 0. -1.  3. -9.]
 [ 0.  0.  1. -2.]]
Matriz Triangular 
[[ 2.  1. -1.  5.]
 [ 0. -1.  3. -9.]
 [ 0.  0.  1. -2.]]


In [ ]:
M = np.matrix(np.array([[0,1,2,1],[4,0,6,2],[5,1,0,4]]))
print(M)

[[0 1 2 1]
 [4 0 6 2]
 [5 1 0 4]]


In [ ]:
B = gaussJorndan(M)

print("Matriz Triangular ")
print(B)

intercambiar fila  0  con la fila  1
[[4. 0. 6. 2.]
 [0. 1. 2. 1.]
 [5. 1. 0. 4.]]
Sumar  -1.25  veces la fila  0  a la fila  2
[[ 4.   0.   6.   2. ]
 [ 0.   1.   2.   1. ]
 [ 0.   1.  -7.5  1.5]]
Sumar  -1.0  veces la fila  1  a la fila  2
[[ 4.   0.   6.   2. ]
 [ 0.   1.   2.   1. ]
 [ 0.   0.  -9.5  0.5]]
Matriz Triangular 
[[ 4.   0.   6.   2. ]
 [ 0.   1.   2.   1. ]
 [ 0.   0.  -9.5  0.5]]
