In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as la

# Actividad 08: Algebra Lineal y Matrices

---
### Profesor: Juan Marcos Marín
### Nombre: ______
*Métodos computacionales 2024-II*

---

#1

Escriba una función que calcule el producto escalar y vectorial para dos vectores, compare sus resultados con `np.dot` y `np.cross`.

In [ ]:
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])
def producto_escalar(v1, v2):
  v3 = []
  for i in range(len(v1)):
    v3.append(v1[i] * v2[i])
  return sum(v3)
def producto_vectorial(v1, v2):
  v3 = []
  if len(v1) == 2 or len(v2) == 2:
    v3.append(v1[0] * v2[1] - v1[1] * v2[0])
    return v3
  v3.append(v1[1] * v2[2] - v1[2] * v2[1])
  v3.append(v1[2] * v2[0] - v1[0] * v2[2])
  v3.append(v1[0] * v2[1] - v1[1] * v2[0])
  return v3
print(producto_escalar(v1, v2), np.dot(v1, v2))
print(producto_vectorial(v1, v2), np.cross(v1, v2))

32 32
[-3, 6, -3] [-3  6 -3]


#2

Crear una función llamada `mulmat()` donde a partir de dos matrices $A$ y $B$ encuentre su multplicación. También realiza una función que calcule la transpuesta y otra el determinante de una matriz $3\times 3$. Compare sus resultado con `@`, `np.dot`, `transpose` y `la.det`.

In [ ]:
def mulmat(A, B):
  if len(A[0]) == len(B):
    C = [[0 for i in range(len(B[0]))] for j in range(len(A))]
    for i in range(len(A)):
      for j in range(len(B[0])):
        for k in range(len(B)):
          C[i][j] += A[i][k] * B[k][j]
    return np.array(C)
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])
print(mulmat(A, B))
print(A @ B)
print(np.dot(A, B))

[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]
[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]
[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]


In [ ]:
def transpose(A):
  C = [[0 for i in range(len(A))] for j in range(len(A[0]))]
  for i in range(len(A)):
    for j in range(len(A[0])):
      C[j][i] = A[i][j]
  return np.array(C)
print(transpose(A))
print(A.T)

[[1 4 7]
 [2 5 8]
 [3 6 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [ ]:
A = np.array([[1, 2, 3], [4, 4, 6], [7, 1, 9]])
def determinante(A):
  det = A[0][0]*(A[1][1]*A[2][2] - A[2][1]*A[1][2]) -  A[0][1]*(A[1][0]*A[2][2] - A[1][2]*A[2][0]) + A[0][2]*(A[1][0]*A[2][1] - A[1][1] * A[2][0])
  return det
print(determinante(A))
print(np.linalg.det(A))



-30
-29.99999999999999


In [ ]:
print(A[0][2])

3


#3
Escriba tres matrices aleatorias $A$, $B$ y $C$ de $3\times 3$, y demuestre las siguientes relaciones

- $ \mathbf{A}\mathbf{B} \neq \mathbf{B}\mathbf{A} $, en general.
- $ (\mathbf{A}\mathbf{B})\mathbf{C} = \mathbf{A}(\mathbf{B}\mathbf{C}) $.
- $ \mathbf{A}(\mathbf{B} + \mathbf{C}) = \mathbf{A}\mathbf{B} + \mathbf{A}\mathbf{C} $.
- $ (\mathbf{A} + \mathbf{B})\mathbf{C} = \mathbf{A}\mathbf{C} + \mathbf{B}\mathbf{C} $.
- $ (\mathbf{A}\mathbf{B})^\top = \mathbf{B}^\top \mathbf{A}^\top $.
- $ \det(\mathbf{A}\mathbf{B}) = \det(\mathbf{A}) \det(\mathbf{B}) $.
- $ (\mathbf{A}^\top)^\top = \mathbf{A} $.
- $ (c\mathbf{A})^\top = c\mathbf{A}^\top $.
- $ (\mathbf{A} + \mathbf{B})^\top = \mathbf{A}^\top + \mathbf{B}^\top $.



In [ ]:
A = np.random.rand(3, 3)
B = np.random.rand(3, 3)
C = np.random.rand(3, 3)
if not np.array_equal(A @ B, B @ A):
  print("A @ B != B @ A")
AB_C = np.dot(np.dot(A,B),C)
A_BC = np.dot(A, np.dot(B, C))
print(AB_C)
print(A_BC)



A @ B != B @ A
[[1.19182797 0.89926906 0.82626765]
 [0.68066903 0.54962895 0.49450488]
 [0.92746148 0.7015424  0.6369458 ]]
[[1.19182797 0.89926906 0.82626765]
 [0.68066903 0.54962895 0.49450488]
 [0.92746148 0.7015424  0.6369458 ]]


In [ ]:
A_B_C = np.dot(A,(B + C))
A_B_C2 = np.dot(A,B) + np.dot(A,C)
print(A_B_C)
print(A_BC) #Raro

[[2.14381604 1.75643081 1.44806531]
 [1.18871745 0.84881616 0.81386767]
 [1.26253321 1.15000485 0.99211634]]
[[1.19182797 0.89926906 0.82626765]
 [0.68066903 0.54962895 0.49450488]
 [0.92746148 0.7015424  0.6369458 ]]


In [ ]:
D = np.dot(A,B)
D_t = D.T
E = np.dot(B.T, A.T)
print(D_t)
print(E)

[[0.63125095 0.3946675  0.45031877]
 [0.62811896 0.30936311 0.47167488]
 [0.48502016 0.3194399  0.40082812]]
[[0.63125095 0.3946675  0.45031877]
 [0.62811896 0.30936311 0.47167488]
 [0.48502016 0.3194399  0.40082812]]


In [ ]:
D = np.dot(A,B)
D_det = np.linalg.det(D)
Det = np.linalg.det(A) * np.linalg.det(B)
print(D_det)
print(Det)

-0.003125779576804148
-0.003125779576804152


In [ ]:
A_t_t = A.T.T
print(A_t_t)
print(A)

[[0.32697635 0.65510813 0.83182268]
 [0.25293007 0.46178123 0.30856526]
 [0.41538859 0.3117733  0.44616907]]
[[0.32697635 0.65510813 0.83182268]
 [0.25293007 0.46178123 0.30856526]
 [0.41538859 0.3117733  0.44616907]]


In [ ]:
A_2 = (2 * A).T
A_2_t = 2 * A.T
print(A_2)
print(A_2_t)


[[0.6539527  0.50586013 0.83077719]
 [1.31021626 0.92356246 0.62354661]
 [1.66364537 0.61713051 0.89233813]]
[[0.6539527  0.50586013 0.83077719]
 [1.31021626 0.92356246 0.62354661]
 [1.66364537 0.61713051 0.89233813]]


In [ ]:
C = A + B
C_t = C.T
A_t = A.T
B_t = B.T
C_t2 = A_t + B_t
print(C_t)
print(C_t2)

[[0.86060261 0.66550807 0.63957649]
 [1.21830173 0.47194844 0.83749513]
 [1.4607513  0.5678826  0.57780106]]
[[0.86060261 0.66550807 0.63957649]
 [1.21830173 0.47194844 0.83749513]
 [1.4607513  0.5678826  0.57780106]]


#4

El **Teorema de Laplace** es un método para calcular el determinante de una matriz cuadrada, particularmente útil para matrices de orden mayor a 2. Este teorema se basa en la expansión del determinante por los elementos de una fila o una columna cualquiera.



$$
\det(A) = \sum_{j=1}^n (-1)^{1+j} a_{1j} M_{1j}
$$

donde:
- $a_{1j}$ es el elemento de la primera fila y columna $j$.
- $M_{1j}$ es el menor asociado al elemento $a_{1j}$, es decir, el determinante de la submatriz de $3 \times 3$ que se obtiene al eliminar la fila 1 y la columna $j$.
- $(-1)^{1+j}$ es el signo correspondiente al cofactor del elemento $a_{1j}$.

Podemos realizar una función recursiva para el cálculo del determinante, sabiendo que el valor del determinante de una matriz de orden uno es el único elemento de esa matriz, y el de una matriz de orden superior a uno es la suma de cada uno de los elementos de una fila o columna por los Adjuntos a ese elemento, como en la función recursiva se emplea la misma función definida el cálculo lo haremos por Menor complementario, un ejemplo desarrollado por la primera fila sería:

$$
   \det (A_{j,j}) =
   \left \{
   \begin{array}{llcl}
      si & j = 1 & \to & a_{1,1} \\
                                 \\
      si & j > 1 & \to & \displaystyle \sum_{k=1}^j \; (-1)^{(1+k)} \cdot a_{1,k} \cdot \det( \alpha_{1,k})
   \end{array}
   \right .
$$

Realice una función que encuentre el determinante de una matriz usando la recursividad aqui planteada, explique explicitamente su código

In [ ]:
import numpy as np

def determinante_l(matriz):
    # Caso base: si la matriz es de tamaño 1x1, el determinante es el único elemento
    if len(matriz) == 1:
        return matriz[0][0]

    det = 0
    # Expansión por la primera fila (puedes elegir cualquier fila o columna)
    for j in range(len(matriz[0])):
        # Crear el menor complementario al eliminar la primera fila y la columna j
        menor = [fila[:j] + fila[j+1:] for fila in matriz[1:]]  # Eliminar la primera fila y columna j

        # Cálculo recursivo del determinante de la submatriz
        cofactor = (-1)**(1+j+1) * matriz[0][j] * determinante(menor)

        # Sumar el resultado al determinante total
        det += cofactor

    return det


In [ ]:
A = np.random.rand(5, 5)
print("Matriz A:")
print(A)
print("\nDeterminante de A:", determinante(A.tolist()))
print("\nDeterminante de A:", np.linalg.det(A))

Matriz A:
[[0.39801465 0.85618412 0.32435101 0.0539835  0.69455441]
 [0.69428807 0.2743584  0.61214001 0.55051612 0.34743089]
 [0.73178682 0.76174335 0.37400784 0.44153488 0.45523239]
 [0.97717185 0.73372278 0.085958   0.3808019  0.1722024 ]
 [0.15514143 0.65466766 0.55168464 0.74235942 0.30734303]]

Determinante de A: 0.12287639547976259

Determinante de A: 0.008901331627833154


#5

El método de Jacobi reescribe el sistema $ Ax = b $ descomponiendo la matriz $ A $ como:

$$
A = D + L + U,
$$

donde:
- $ D $: Matriz diagonal de $ A $,
- $ L $: Matriz triangular inferior sin la diagonal,
- $ U $: Matriz triangular superior sin la diagonal.

El sistema se reorganiza como:

$$
x = D^{-1}(b - (L + U)x).
$$

Esto se implementa iterativamente como:

$$
x_i^{(k+1)} = \frac{1}{a_{ii}} \left(b_i - \sum_{j \neq i} a_{ij} x_j^{(k)}\right),
$$

donde $ a_{ii} $ son los elementos diagonales de $ A $.

* Escriba una función explicita que realice de manera iterativa este método con una tol = 1e-7 y un máximo de 100 iteraciones. Defina una documentación clara que explique los métodos usados, lasa entradas y salidas.

* Para una matriz aleatoria 5$\times$ 5, encuentre la solución usando su función y determine el error con respecto a `solve` y el método de inversa de matriz.

In [ ]:
import numpy as np

def metodo_jacobi(A, b, tol=1e-7, max_iter=1000):
    """
    Resuelve el sistema de ecuaciones Ax = b usando el método de Jacobi.

    Parámetros:
    A : array_like, matriz de coeficientes del sistema (matriz cuadrada de tamaño n x n)
    b : array_like, vector de términos independientes (tamaño n)
    tol : float, tolerancia para la convergencia del método (por defecto 1e-7)
    max_iter : int, número máximo de iteraciones (por defecto 100)

    Salidas:
    x : array_like, vector solución aproximada del sistema Ax = b
    num_iter : int, número de iteraciones realizadas
    """

    # Inicialización de variables
    n = len(b)
    x = np.zeros(n)  # Vector inicial de soluciones (todos ceros)
    x_old = np.zeros(n)  # Vector para comparar con la solución anterior

    # Descomposición de A
    D = np.diag(np.diag(A))  # Matriz diagonal
    L = np.tril(A, -1)  # Matriz triangular inferior (sin la diagonal)
    U = np.triu(A, 1)  # Matriz triangular superior (sin la diagonal)

    # Iteración de Jacobi
    for num_iter in range(max_iter):
        # Calcular el nuevo valor de x
        x_new = np.linalg.inv(D).dot(b - (L + U).dot(x))

        # Verificar si la diferencia entre las iteraciones es suficientemente pequeña
        if np.linalg.norm(x_new - x) < tol:
            return x_new, num_iter + 1

        # Actualizar x para la siguiente iteración
        x = x_new

    # Si no convergió en el número máximo de iteraciones
    return x, num_iter + 1


In [ ]:

# Generar una matriz aleatoria 5x5
A = np.random.rand(5, 5)
b = np.random.rand(5)
C = np.array([[4, -1, 1], [-2, 6, 1], [1, 1, 5]])
d = np.array([7, 9, -6])
# Resolver el sistema usando el método de Jacobi
solucion_jacobi, iteraciones = metodo_jacobi(A, b)

# Usar np.linalg.solve para comparar con el resultado exacto
solucion_exacta = np.linalg.solve(A, b)

# Calcular el error de la solución de Jacobi
error_jacobi = np.linalg.norm(solucion_jacobi - solucion_exacta)

solucion_jacobi1, iteraciones1 = metodo_jacobi(C, d)
solucion_exacta1 = np.linalg.solve(C, d)
error_jacobi1 = np.linalg.norm(solucion_jacobi1 - solucion_exacta1)

# Mostrar los resultados


print("Solución obtenida con el método de Jacobi:")
print(solucion_jacobi)
print("Número de iteraciones:", iteraciones)

print("\nSolución exacta (con np.linalg.solve):")
print(solucion_exacta)

print("\nError con respecto a la solución exacta:")
print(error_jacobi)

print("\Solución obtenida con el método de Jacobi A1:")
print(solucion_jacobi1)
print("Número de iteraciones A1:", iteraciones1)
print("\nSolución exacta (con np.linalg.solve) A1:")
print(solucion_exacta1)
print("\nError con respecto a la solución exacta A1:")
print(error_jacobi1)



Solución obtenida con el método de Jacobi:
[nan nan nan nan nan]
Número de iteraciones: 1000

Solución exacta (con np.linalg.solve):
[-1.9265784   0.41735817 -0.01775949  0.54317209  1.98544924]

Error con respecto a la solución exacta:
nan
\Solución obtenida con el método de Jacobi A1:
[ 3.08247419  2.92783501 -2.40206182]
Número de iteraciones A1: 24

Solución exacta (con np.linalg.solve) A1:
[ 3.08247423  2.92783505 -2.40206186]

Error con respecto a la solución exacta A1:
6.267470001151087e-08


#6

Verifique que cualquier matriz hermitiana de 2 × 2 $ L $ puede escribirse como una suma de cuatro términos:

$$ L = a\sigma_x + b\sigma_y + c\sigma_z + dI $$

donde $ a $, $ b $, $ c $ y $ d $ son números reales.

Las cuatro matrices de Pauli son:

$$ \sigma_x = \begin{pmatrix} 0 & 1 \\ 1 & 0 \end{pmatrix}, \quad \sigma_y = \begin{pmatrix} 0 & -i \\ i & 0 \end{pmatrix}, \quad \sigma_z = \begin{pmatrix} 1 & 0 \\ 0 & -1 \end{pmatrix}, \quad I = \begin{pmatrix} 1 & 0 \\ 0 & 1 \end{pmatrix} $$




In [ ]:
import numpy as np

# Definimos las matrices de Pauli y la identidad
sigma_x = np.array([[0, 1], [1, 0]])
sigma_y = np.array([[0, -1j], [1j, 0]])
sigma_z = np.array([[1, 0], [0, -1]])
I = np.array([[1, 0], [0, 1]])

def descomponer_matriz_hermitiana(L):
    """
    Descompone una matriz hermitiana L en la forma:
    L = a * sigma_x + b * sigma_y + c * sigma_z + d * I
    donde a, b, c, d son los coeficientes reales.

    Parámetros:
    L : np.array
        Una matriz hermitiana 2x2.

    Retorna:
    a, b, c, d : float
        Los coeficientes de la descomposición de L.
    """
    # Comprobamos que L es hermitiana
    if not np.allclose(L, L.conj().T):
        raise ValueError("La matriz no es hermitiana.")

    # Calculamos los coeficientes a, b, c, d
    d = np.trace(L) / 2
    c = (L[0, 0] - L[1, 1]) / 2
    a = np.real(L[0, 1])
    b = -np.imag(L[0, 1])

    return a, b, c, d

# Ejemplo de matriz hermitiana aleatoria 2x2
L = np.array([[1, 2+3j], [2-3j, 4]])

# Descomponemos la matriz L en términos de las matrices de Pauli
a, b, c, d = descomponer_matriz_hermitiana(L)

# Mostramos los coeficientes
print(f"Matriz L: \n{L}\n")
print(f"Coeficientes de la descomposición:")
print(f"a = {a}")
print(f"b = {b}")
print(f"c = {c}")
print(f"d = {d}")

# Reconstruimos L a partir de la descomposición
reconstruido = a * sigma_x + b * sigma_y + c * sigma_z + d * I

print("\nMatriz reconstruida a partir de la descomposición:")
print(reconstruido)

# Verificamos si la matriz reconstruida es igual a la original
print("\n¿La matriz reconstruida es igual a la original?")
print(np.allclose(L, reconstruido))


Matriz L: 
[[1.+0.j 2.+3.j]
 [2.-3.j 4.+0.j]]

Coeficientes de la descomposición:
a = 2.0
b = -3.0
c = (-1.5+0j)
d = (2.5+0j)

Matriz reconstruida a partir de la descomposición:
[[1.+0.j 2.+3.j]
 [2.-3.j 4.+0.j]]

¿La matriz reconstruida es igual a la original?
True
