**ELiminación gausiana para una matriz creada aleatoria mente**

In [ ]:
import numpy as np

def eliminacion_gaussiana(A):
    n = len(A)

    for i in range(0, n):
        # Búsqueda del pivote
        max_fila = abs(A[i:, i]).argmax() + i
        # Intercambiar la fila del pivote por la fila actual
        A[[i, max_fila]] = A[[max_fila, i]]

        for j in range(i+1, n):
            factor = A[j,i] / A[i,i]
            A[j, :] -= factor * A[i,:]

    return A

A = np.random.randint(0,10,(5,6)).astype(float)

print(A)

print(eliminacion_gaussiana(A))


[[5. 1. 4. 0. 9. 5.]
 [8. 0. 9. 2. 6. 3.]
 [8. 2. 4. 2. 6. 4.]
 [8. 6. 1. 3. 8. 1.]
 [9. 8. 9. 4. 1. 3.]]
[[ 9.          8.          9.          4.          1.          3.        ]
 [ 0.         -7.11111111  1.         -1.55555556  5.11111111  0.33333333]
 [ 0.          0.         -7.15625    -0.3125      6.3125     -1.71875   ]
 [ 0.          0.          0.         -1.40393013  4.65938865  3.52838428]
 [ 0.          0.          0.          0.         -3.49300156  1.64541213]]


**Solución de un sistema AX = B  eliminación gaussiana**

In [ ]:

import numpy as np


def eliminacion_gaussiana(A):
    n = len(A)

    for i in range(0, n):
        # Búsqueda del pivote
        max_fila = abs(A[i:, i]).argmax() + i
        # Intercambiar la fila del pivote por la fila actual
        A[[i, max_fila]] = A[[max_fila, i]]

        for j in range(i+1, n):
            factor = A[j,i] / A[i,i]
            A[j, :] -= factor * A[i,:]

    return A


def regresion(A_ampliada):
    n = A_ampliada.shape[0]
    m = A_ampliada.shape[1]

    # Eliminación Gaussiana
    A_gauss = eliminacion_gaussiana(A_ampliada[:,0:n])

    # Inicializar soluciones
    x = np.zeros(n)

    # Sustitución hacia atrás
    for i in range(n-1,-1,-1):
        suma = 0
        for j in range(i+1,n):
            suma += A_gauss[i,j]*x[j]
        x[i] = (A_ampliada[i,-1] - suma)/A_gauss[i,i]

    return x

#crear matriz ampliada de manera aleatoria
A = np.random.randint(-10,10,(5,6)).astype(float)
sol = regresion(A)
print("La solución del sistema es:")
print(sol)

# Matriz de coeficientes
coefficients = A[:, :-1]

# Vector de términos constantes
constants = -A[:, -1]

solution = np.linalg.solve(coefficients, constants)

print('Verificación usando librerías')
print(solution)



La solución del sistema es:
[0.12791215 2.24422706 0.98604482 0.97283355 1.73831776]
Verificación usando librerías
[-0.12791215 -2.24422706 -0.98604482 -0.97283355 -1.73831776]


**Determinante de una matriz 4x4**

In [ ]:
# determinante de una matriz 4x4

import numpy as np


#**************************************************
def determinante(B,elemento,i):
    det =0
    det= B[0,0]*B[1,1]- B[0,1]*B[1,0]

    #print(B)
    #print(i)
    #print(elemento)
    #print(det)


    return det*elemento * (-1)**i
#*******************************************************


def determinante2(A):



    # Extraer la primera fila de A
    fila = A[0, :]

    # Extraer la segunda columna de A
    columna = A[:, 1]

    # Crear la matriz B a partir de las filas y columnas restantes
    # Esto se puede hacer excluyendo la fila y la columna extraídas
    suma = 0




    for i in range(0,len(A[0]-1)):

        B = np.delete(np.delete(A, 0, axis=0), i, axis=1)
        elemento = A[0,i]
        #print(B)
        #print('suma', determinante( B , elemento , i))
        suma += determinante( B , elemento , i)





    #print(suma)




    return suma
print('A = ')
print(A)
A = np.array([[1, 2, 3, 4],
                [8, 5, 6,7],
                [10,7, 8, 9],
                [11,12,13,14] ])


B = np.delete(np.delete(A, 0, axis=0), 1 , axis=1)

print(B)
print(determinante2(B))
print(np.linalg.det(B))




A = 
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 8  6  7]
 [10  8  9]
 [11 13 14]]
8
7.999999999999973


**Resolución de un sistema AX =B por diagonalización de matrices**







SI  $A$ tiene \(n\) autovectores linealmente independientes entonces $A$ es
 diagonalizable, donde. $\lambda_i$ son los autovalores  y  $v_i$ son los autovectores asociados a la matriz $A$.

 **Construir la matriz P:** La matriz P se forma colocando los autovectores como columnas. Es decir, si $v_i$ es el $i$-ésimo autovector, entonces $P = [v_1, v_2, ..., v_n]$.

**Calcular la matriz diagonal D:** $D = P^{-1}AP$

 **Resolver** $Dy = P^{-1}B\$

  El sistema $Dy = P^{-1}B\$ es más fácil de resolver porque D es una matriz diagonal. Puedes resolver cada ecuación por separado.

**Encontrar la solución de** $Ax = B$

La solución $x$ del sistema original se encuentra usando $x = Py$.



In [ ]:
import numpy as np

def diagonali(A, B):
    # Paso 1: Diagonalización
    eigenvalues, eigenvectors = np.linalg.eig(A)
    P = eigenvectors
    D = np.linalg.inv(P) @ A @ P

    # Paso 2: Resolver Dy = P^{-1}B
    D_inv = np.linalg.inv(D)
    y = D_inv @ P.T @ B

    # Paso 3: Encontrar la solución de Ax = B
    x = P @ y

    return x

# Ejemplo
A = np.random.randint(-10,10,(2,2)).astype(float)
B = np.random.randint(-10,10,(2)).astype(float)

solution = diagonali(A, B)
print("Solución del sistema Ax = B:", solution)




Solución del sistema Ax = B: [-1.19245283  1.02641509]
