In [1]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as la

# Actividad 08: Algebra Lineal y Matrices

---
### Profesor: Juan Marcos Marín
### Nombre: ______
*Métodos computacionales 2024-II*

---

#1

Escriba una función que calcule el producto escalar y vectorial para dos vectores, compare sus resultados con `np.dot` y `np.cross`.

In [2]:
def escalar(a,b):
  n = len(a)
  resultado = 0
  for i in range(n):
    j = a[i] * b[i]
    resultado += j
  return resultado

a = np.array([12,23,1])
b = np.array([3,4,1])

print(f"Resultado con la funcion: {escalar(a,b)}")
print(f"Resultado con np.dot: {np.dot(a,b)}")

Resultado con la funcion: 129
Resultado con np.dot: 129


In [3]:
def vectorial(a,b):
  n = len(a)
  if n==2:
    k = a[0]*b[1] - a[1]*b[0]
    return np.array([k])
  elif n==3:
    i,j,k = a[1]*b[2] - a[2]*b[1], a[2]*b[0] - a[0]*b[2], a[0]*b[1] - a[1]*b[0]
    return np.array([i,j,k])
  else:
    print("Error")

print(f"Resultado con la funcion: {vectorial(a,b)}")
print(f"Resultado con np.cross: {np.cross(a,b)}")

Resultado con la funcion: [ 19  -9 -21]
Resultado con np.cross: [ 19  -9 -21]


#2

Crear una función llamada `mulmat()` donde a partir de dos matrices $A$ y $B$ encuentre su multplicación. También realiza una función que calcule la transpuesta y otra el determinante de una matriz $3\times 3$. Compare sus resultado con `@`, `np.dot`, `transpose` y `la.det`.

In [4]:
A = np.array([    #Matris 3x4
  [1, 2, 3, 4],
  [5, 6, 7, 8],
  [9, 10, 11, 12]
])

B = np.array([    #Matriz 4x3
  [1, 2, 3],
  [4, 5, 6],
  [7, 8, 9],
  [10, 11, 12]])


def mulmat(a,b):
  n, m = a.shape
  p = b.shape[1]
  resultado = np.zeros((n, p))

  for i in range(n):
    for j in range(p):
      suma = 0
      for k in range(m):
        suma += a[i,k] * b[k,j]
      resultado[i,j] = suma
  return resultado

print(f"Con funcion mulmat: {mulmat(A,B)}")
print(f"Con @: {A@B}")

Con funcion mulmat: [[ 70.  80.  90.]
 [158. 184. 210.]
 [246. 288. 330.]]
Con @: [[ 70  80  90]
 [158 184 210]
 [246 288 330]]


In [5]:
def traspuesta(a):
  n, m = a.shape
  b = np.zeros((m,n))
  for i in range(m):
    for j in range(n):
      b[i,j] = a[j,i]
  return b

print(f"Con función traspuesta: {traspuesta(A)}")
print(f"Con función transpose: {np.transpose(A)}")

Con función traspuesta: [[ 1.  5.  9.]
 [ 2.  6. 10.]
 [ 3.  7. 11.]
 [ 4.  8. 12.]]
Con función transpose: [[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


In [6]:
B = np.array([
  [1, 15, 3],
  [13, 5, 6],
  [7, 21, 9]])

def determinante(a):
  return a[0,0]*(a[1,1]*a[2,2]-a[1,2]*a[2,1]) - a[0,1]*(a[1,0]*a[2,2]-a[1,2]*a[2,0]) + a[0,2]*(a[1,0]*a[2,1]-a[1,1]*a[2,0])

print(f"Con funcion determinante: {determinante(B)}")
print(f"Con la.det: {la.det(B)}")

Con funcion determinante: -492
Con la.det: -492.0


#3
Escriba tres matrices aleatorias $A$, $B$ y $C$ de $3\times 3$, y demuestre las siguientes relaciones

- $ \mathbf{A}\mathbf{B} \neq \mathbf{B}\mathbf{A} $, en general.
- $ (\mathbf{A}\mathbf{B})\mathbf{C} = \mathbf{A}(\mathbf{B}\mathbf{C}) $.
- $ \mathbf{A}(\mathbf{B} + \mathbf{C}) = \mathbf{A}\mathbf{B} + \mathbf{A}\mathbf{C} $.
- $ (\mathbf{A} + \mathbf{B})\mathbf{C} = \mathbf{A}\mathbf{C} + \mathbf{B}\mathbf{C} $.
- $ (\mathbf{A}\mathbf{B})^\top = \mathbf{B}^\top \mathbf{A}^\top $.
- $ \det(\mathbf{A}\mathbf{B}) = \det(\mathbf{A}) \det(\mathbf{B}) $.
- $ (\mathbf{A}^\top)^\top = \mathbf{A} $.
- $ (c\mathbf{A})^\top = c\mathbf{A}^\top $.
- $ (\mathbf{A} + \mathbf{B})^\top = \mathbf{A}^\top + \mathbf{B}^\top $.



In [7]:
B = np.array([
  [1, 15, 3],
  [13, 5, 6],
  [7, 21, 9]], dtype=float)

C = np.array([
    [2, 1, 6],
    [1, 3, 5],
    [9, 8, 10]
], dtype=float)

D = np.array([
    [5, 24, 1],
    [17, 45, 3],
    [1, 6, 1]
], dtype=float)

#BC y CB
print("-Multiplicación de matrices")
print(f"BC= {mulmat(B,C)}")
print(f"CB= {mulmat(C,B)}")
print("----------------------")

#(BC)D y B(CD)
print("-Propiedad asociativa multiplicación de matrices")
print(f"(BC)D= {mulmat(mulmat(B,C),D)}")
print(f"B(CD)= {mulmat(B,mulmat(C,D))}")
print("----------------------")

#B(C+D) y BC+CD
print("-Propiedad distributiva")
print(f"B(C+D)= {mulmat(B,C+D)}")
print(f"BC+CD= {mulmat(B,C)+mulmat(B,D)}")
print("----------------------")

#(B+C)D y BD+CD
print(f"(B+C)D= {mulmat(B+C,D)}")
print(f"BD+CD= {mulmat(B,D)+mulmat(C,D)}")
print("----------------------")

#BCt y CtBt
print("-Multiplicación de transpuestas")
print(f"(BC)t= {traspuesta(mulmat(B,C))}")
print(f"CtBt= {mulmat(traspuesta(C),traspuesta(B))}")
print("----------------------")

#det(BC) y det(B)det(C)
print("-Determinantes")
print(f"det(BC)t= {determinante(mulmat(B,C))}")
print(f"del(B)det(C)= {determinante(B)*determinante(C)}")
print("----------------------")

#(Bt)t y B
print("-Transpuesta de una transpesta")
print(f"Matriz B= {B}")
print(f"(Bt)t= {traspuesta(traspuesta(B))}")
print("----------------------")

#(B+C)t y Bt+Ct
print("-Suma de transpuestas")
print(f"(B+C)t= {traspuesta(B+C)}")
print(f"Bt+Ct= {traspuesta(B)+traspuesta(C)}")
print("----------------------")

-Multiplicación de matrices
BC= [[ 44.  70. 111.]
 [ 85.  76. 163.]
 [116. 142. 237.]]
CB= [[ 57. 161.  66.]
 [ 75. 135.  66.]
 [183. 385. 165.]]
----------------------
-Propiedad asociativa multiplicación de matrices
(BC)D= [[ 1521.  4872.   365.]
 [ 1880.  6438.   476.]
 [ 3231. 10596.   779.]]
B(CD)= [[ 1521.  4872.   365.]
 [ 1880.  6438.   476.]
 [ 3231. 10596.   779.]]
----------------------
-Propiedad distributiva
B(C+D)= [[ 307.  787.  160.]
 [ 241.  649.  197.]
 [ 517. 1309.  316.]]
BC+CD= [[ 307.  787.  160.]
 [ 241.  649.  197.]
 [ 517. 1309.  316.]]
----------------------
(B+C)D= [[ 296.  846.   60.]
 [ 217.  762.   49.]
 [ 592. 1803.  122.]]
BD+CD= [[ 296.  846.   60.]
 [ 217.  762.   49.]
 [ 592. 1803.  122.]]
----------------------
-Multiplicación de transpuestas
(BC)t= [[ 44.  85. 116.]
 [ 70.  76. 142.]
 [111. 163. 237.]]
CtBt= [[ 44.  85. 116.]
 [ 70.  76. 142.]
 [111. 163. 237.]]
----------------------
-Determinantes
det(BC)t= 48708.0
del(B)det(C)= 48708.0
----------

#4

El **Teorema de Laplace** es un método para calcular el determinante de una matriz cuadrada, particularmente útil para matrices de orden mayor a 2. Este teorema se basa en la expansión del determinante por los elementos de una fila o una columna cualquiera.



$$
\det(A) = \sum_{j=1}^n (-1)^{1+j} a_{1j} M_{1j}
$$

donde:
- $a_{1j}$ es el elemento de la primera fila y columna $j$.
- $M_{1j}$ es el menor asociado al elemento $a_{1j}$, es decir, el determinante de la submatriz de $3 \times 3$ que se obtiene al eliminar la fila 1 y la columna $j$.
- $(-1)^{1+j}$ es el signo correspondiente al cofactor del elemento $a_{1j}$.

Podemos realizar una función recursiva para el cálculo del determinante, sabiendo que el valor del determinante de una matriz de orden uno es el único elemento de esa matriz, y el de una matriz de orden superior a uno es la suma de cada uno de los elementos de una fila o columna por los Adjuntos a ese elemento, como en la función recursiva se emplea la misma función definida el cálculo lo haremos por Menor complementario, un ejemplo desarrollado por la primera fila sería:

$$
   \det (A_{j,j}) =
   \left \{
   \begin{array}{llcl}
      si & j = 1 & \to & a_{1,1} \\
                                 \\
      si & j > 1 & \to & \displaystyle \sum_{k=1}^j \; (-1)^{(1+k)} \cdot a_{1,k} \cdot \det( \alpha_{1,k})
   \end{array}
   \right .
$$

Realice una función que encuentre el determinante de una matriz usando la recursividad aqui planteada, explique explicitamente su código

In [8]:
def det(A):
  n = len(A)
  if n == 1:   #Si la matriz solo tiene un elemento el determinante es ese elemento
    return A[0][0]

  else:   #Para matrices 2x2 o mas grandes
    suma = 0
    for k in range(n):   #
      menor = np.delete(np.delete(A, 0, axis=0), k, axis=1)
      suma += (-1)**k * A[0][k] * det(menor)
    return suma

B = np.array([
  [1, 15, 3],
  [13, 5, 6],
  [7, 21, 9]], dtype=float)

print(det(B))
print(np.linalg.det(B))


-492.0
-491.99999999999943


#5

El método de Jacobi reescribe el sistema $ Ax = b $ descomponiendo la matriz $ A $ como:

$$
A = D + L + U,
$$

donde:
- $ D $: Matriz diagonal de $ A $,
- $ L $: Matriz triangular inferior sin la diagonal,
- $ U $: Matriz triangular superior sin la diagonal.

El sistema se reorganiza como:

$$
x = D^{-1}(b - (L + U)x).
$$

Esto se implementa iterativamente como:

$$
x_i^{(k+1)} = \frac{1}{a_{ii}} \left(b_i - \sum_{j \neq i} a_{ij} x_j^{(k)}\right),
$$

donde $ a_{ii} $ son los elementos diagonales de $ A $.

* Escriba una función explicita que realice de manera iterativa este método con una tol = 1e-7 y un máximo de 100 iteraciones. Defina una documentación clara que explique los métodos usados, lasa entradas y salidas.

* Para una matriz aleatoria 5$\times$ 5, encuentre la solución usando su función y determine el error con respecto a `solve` y el método de inversa de matriz.

In [9]:
def jacobi(A,b,tol=1e-7,max_iter=100):
  n = len(b)
  x = np.zeros_like(b, dtype = float)   #Solución inicial

  for k in range(max_iter):
    x_new = np.copy(x)
    for i in range(n):
      suma = 0
      suma = sum(A[i,j]*x[j] for j in range(n) if j!=i)
      x_new[i] = (b[i]-suma)/A[i,i]

    #Examinar la convergencia
    if np.max(np.abs(x_new-x))<tol:
      print(f"Converge después de {k+1} iteraciones")
      return x_new
    x = x_new

  print("No converge")
  return x

A5 = np.array([[20, 1, 3, 4, 5],
              [1, 9, 2, 5, 4],
              [4, 2, 50, 3, 1],
              [5, 4, 1, 28, 3],
              [3, 5, 4, 1, 29]],dtype=float )



b5 = np.array([10, 15, 20, 25, 30])

print(jacobi(A5,b5))
print(la.solve(A5,b5))

Converge después de 32 iteraciones
[0.07643026 0.86387569 0.30359867 0.65784035 0.81307224]
[0.07643027 0.86387572 0.30359868 0.65784037 0.81307226]


#6

Verifique que cualquier matriz hermitiana de 2 × 2 $ L $ puede escribirse como una suma de cuatro términos:

$$ L = a\sigma_x + b\sigma_y + c\sigma_z + dI $$

donde $ a $, $ b $, $ c $ y $ d $ son números reales.

Las cuatro matrices de Pauli son:

$$ \sigma_x = \begin{pmatrix} 0 & 1 \\ 1 & 0 \end{pmatrix}, \quad \sigma_y = \begin{pmatrix} 0 & -i \\ i & 0 \end{pmatrix}, \quad \sigma_z = \begin{pmatrix} 1 & 0 \\ 0 & -1 \end{pmatrix}, \quad I = \begin{pmatrix} 1 & 0 \\ 0 & 1 \end{pmatrix} $$




In [28]:
#Matriz Hermitiana
A6 = np.array([
    [2,1j+3],
    [3-1j,5]])

A6.conj().T

array([[2.-0.j, 3.+1.j],
       [3.-1.j, 5.-0.j]])

In [35]:
ox = np.array([
    [0,1],
    [1,0]
])

oy = np.array([
    [0,-1j],
    [1j,0]
])

oz = np.array([
    [1,0],
    [0,-1]
])

I = np.array([
    [1,0],
    [0,1]
])

a,b,c,d = 3,-1,-1.5,3.5

np.allclose(A6,a*ox + b*oy + c*oz + d*I)

True