In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as la

# Actividad 08: Algebra Lineal y Matrices

---
### Profesor: Juan Marcos Marín
### Nombre: Isaac Villada
*Métodos computacionales 2024-II*

---

#1

Escriba una función que calcule el producto escalar y vectorial para dos vectores, compare sus resultados con `np.dot` y `np.cross`.

In [2]:
def producto_escalar(v1, v2):
    return sum(a * b for a, b in zip(v1, v2))

def producto_vectorial(v1, v2):
    return [v1[1] * v2[2] - v1[2] * v2[1],
            v1[2] * v2[0] - v1[0] * v2[2],
            v1[0] * v2[1] - v1[1] * v2[0]]

v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])

escalar_manual = producto_escalar(v1, v2)
vectorial_manual = producto_vectorial(v1, v2)

escalar_np = np.dot(v1, v2)
vectorial_np = np.cross(v1, v2)

print("Producto escalar manual:", escalar_manual)
print("Producto escalar con np.dot:", escalar_np)
print("Producto vectorial manual:", vectorial_manual)
print("Producto vectorial con np.cross:", vectorial_np)


Producto escalar manual: 32
Producto escalar con np.dot: 32
Producto vectorial manual: [-3, 6, -3]
Producto vectorial con np.cross: [-3  6 -3]


#2

Crear una función llamada `mulmat()` donde a partir de dos matrices $A$ y $B$ encuentre su multplicación. También realiza una función que calcule la transpuesta y otra el determinante de una matriz $3\times 3$. Compare sus resultado con `@`, `np.dot`, `transpose` y `la.det`.

In [3]:
def mulmat(A, B):
    filas_A, columnas_A = len(A), len(A[0])
    filas_B, columnas_B = len(B), len(B[0])
    if columnas_A != filas_B:
        raise ValueError("El número de columnas de A debe ser igual al número de filas de B")
    resultado = [[sum(A[i][k] * B[k][j] for k in range(columnas_A)) for j in range(columnas_B)] for i in range(filas_A)]
    return resultado

def transpuesta(M):
    return [[M[j][i] for j in range(len(M))] for i in range(len(M[0]))]

def determinante_3x3(M):
    if len(M) != 3 or len(M[0]) != 3:
        raise ValueError("La matriz debe ser de 3x3")
    return (M[0][0] * (M[1][1] * M[2][2] - M[1][2] * M[2][1]) -
            M[0][1] * (M[1][0] * M[2][2] - M[1][2] * M[2][0]) +
            M[0][2] * (M[1][0] * M[2][1] - M[1][1] * M[2][0]))

A = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
B = [[9, 8, 7], [6, 5, 4], [3, 2, 1]]

multiplicacion_manual = mulmat(A, B)
multiplicacion_np = np.dot(A, B)

transpuesta_manual = transpuesta(A)
transpuesta_np = np.transpose(A)

determinante_manual = determinante_3x3(A)
determinante_np = np.linalg.det(A)

print("Multiplicación manual:", multiplicacion_manual)
print("Multiplicación con np.dot:", multiplicacion_np)

print("Transpuesta manual:", transpuesta_manual)
print("Transpuesta con np.transpose:", transpuesta_np)

print("Determinante manual:", determinante_manual)
print("Determinante con np.linalg.det:", determinante_np)


Multiplicación manual: [[30, 24, 18], [84, 69, 54], [138, 114, 90]]
Multiplicación con np.dot: [[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]
Transpuesta manual: [[1, 4, 7], [2, 5, 8], [3, 6, 9]]
Transpuesta con np.transpose: [[1 4 7]
 [2 5 8]
 [3 6 9]]
Determinante manual: 0
Determinante con np.linalg.det: 0.0


#3
Escriba tres matrices aleatorias $A$, $B$ y $C$ de $3\times 3$, y demuestre las siguientes relaciones

- $ \mathbf{A}\mathbf{B} \neq \mathbf{B}\mathbf{A} $, en general.
- $ (\mathbf{A}\mathbf{B})\mathbf{C} = \mathbf{A}(\mathbf{B}\mathbf{C}) $.
- $ \mathbf{A}(\mathbf{B} + \mathbf{C}) = \mathbf{A}\mathbf{B} + \mathbf{A}\mathbf{C} $.
- $ (\mathbf{A} + \mathbf{B})\mathbf{C} = \mathbf{A}\mathbf{C} + \mathbf{B}\mathbf{C} $.
- $ (\mathbf{A}\mathbf{B})^\top = \mathbf{B}^\top \mathbf{A}^\top $.
- $ \det(\mathbf{A}\mathbf{B}) = \det(\mathbf{A}) \det(\mathbf{B}) $.
- $ (\mathbf{A}^\top)^\top = \mathbf{A} $.
- $ (c\mathbf{A})^\top = c\mathbf{A}^\top $.
- $ (\mathbf{A} + \mathbf{B})^\top = \mathbf{A}^\top + \mathbf{B}^\top $.



In [4]:
A = np.random.randint(1, 10, (3, 3))
B = np.random.randint(1, 10, (3, 3))
C = np.random.randint(1, 10, (3, 3))
c = np.random.randint(1, 10)

print("A:\n", A)
print("B:\n", B)
print("C:\n", C)
print("Escalar c:", c)

print("AB ≠ BA:", np.all(A @ B != B @ A))
print("(AB)C = A(BC):", np.all((A @ B) @ C == A @ (B @ C)))
print("A(B + C) = AB + AC:", np.all(A @ (B + C) == A @ B + A @ C))
print("(A + B)C = AC + BC:", np.all((A + B) @ C == A @ C + B @ C))
print("(AB)^T = B^T A^T:", np.all((A @ B).T == B.T @ A.T))
print("det(AB) = det(A) det(B):", np.isclose(np.linalg.det(A @ B), np.linalg.det(A) * np.linalg.det(B)))
print("(A^T)^T = A:", np.all(A.T.T == A))
print("(cA)^T = cA^T:", np.all((c * A).T == c * A.T))
print("(A + B)^T = A^T + B^T:", np.all((A + B).T == A.T + B.T))


A:
 [[2 4 2]
 [6 5 7]
 [5 2 9]]
B:
 [[5 2 4]
 [9 2 4]
 [2 9 2]]
C:
 [[7 6 6]
 [5 5 5]
 [3 5 7]]
Escalar c: 6
AB ≠ BA: True
(AB)C = A(BC): True
A(B + C) = AB + AC: True
(A + B)C = AC + BC: True
(AB)^T = B^T A^T: True
det(AB) = det(A) det(B): True
(A^T)^T = A: True
(cA)^T = cA^T: True
(A + B)^T = A^T + B^T: True


#4

El **Teorema de Laplace** es un método para calcular el determinante de una matriz cuadrada, particularmente útil para matrices de orden mayor a 2. Este teorema se basa en la expansión del determinante por los elementos de una fila o una columna cualquiera.



$$
\det(A) = \sum_{j=1}^n (-1)^{1+j} a_{1j} M_{1j}
$$

donde:
- $a_{1j}$ es el elemento de la primera fila y columna $j$.
- $M_{1j}$ es el menor asociado al elemento $a_{1j}$, es decir, el determinante de la submatriz de $3 \times 3$ que se obtiene al eliminar la fila 1 y la columna $j$.
- $(-1)^{1+j}$ es el signo correspondiente al cofactor del elemento $a_{1j}$.

Podemos realizar una función recursiva para el cálculo del determinante, sabiendo que el valor del determinante de una matriz de orden uno es el único elemento de esa matriz, y el de una matriz de orden superior a uno es la suma de cada uno de los elementos de una fila o columna por los Adjuntos a ese elemento, como en la función recursiva se emplea la misma función definida el cálculo lo haremos por Menor complementario, un ejemplo desarrollado por la primera fila sería:

$$
   \det (A_{j,j}) =
   \left \{
   \begin{array}{llcl}
      si & j = 1 & \to & a_{1,1} \\
                                 \\
      si & j > 1 & \to & \displaystyle \sum_{k=1}^j \; (-1)^{(1+k)} \cdot a_{1,k} \cdot \det( \alpha_{1,k})
   \end{array}
   \right .
$$

Realice una función que encuentre el determinante de una matriz usando la recursividad aqui planteada, explique explicitamente su código

In [6]:
def determinante_laplace(A):
    if len(A) == 1:
        return A[0, 0]

    det = 0
    for j in range(A.shape[1]):
        menor = np.delete(np.delete(A, 0, axis=0), j, axis=1)
        det += ((-1) ** j) * A[0, j] * determinante_laplace(menor)

    return det

A = np.random.randint(1, 10, (3, 3))
print("Matriz A:\n", A)
print("Determinante calculado con Laplace:", determinante_laplace(A))
print("Determinante con numpy.linalg.det:", np.linalg.det(A))


Matriz A:
 [[6 7 5]
 [1 8 2]
 [6 4 7]]
Determinante calculado con Laplace: 103
Determinante con numpy.linalg.det: 103.00000000000001


#5

El método de Jacobi reescribe el sistema $ Ax = b $ descomponiendo la matriz $ A $ como:

$$
A = D + L + U,
$$

donde:
- $ D $: Matriz diagonal de $ A $,
- $ L $: Matriz triangular inferior sin la diagonal,
- $ U $: Matriz triangular superior sin la diagonal.

El sistema se reorganiza como:

$$
x = D^{-1}(b - (L + U)x).
$$

Esto se implementa iterativamente como:

$$
x_i^{(k+1)} = \frac{1}{a_{ii}} \left(b_i - \sum_{j \neq i} a_{ij} x_j^{(k)}\right),
$$

donde $ a_{ii} $ son los elementos diagonales de $ A $.

* Escriba una función explicita que realice de manera iterativa este método con una tol = 1e-7 y un máximo de 100 iteraciones. Defina una documentación clara que explique los métodos usados, lasa entradas y salidas.

* Para una matriz aleatoria 5$\times$ 5, encuentre la solución usando su función y determine el error con respecto a `solve` y el método de inversa de matriz.

In [7]:
def jacobi(A, b, tol=1e-7, max_iter=100):
    x = np.zeros_like(b, dtype=np.float64)
    D = np.diag(A)
    R = A - np.diagflat(D)

    for _ in range(max_iter):
        x_new = (b - np.dot(R, x)) / D
        if np.linalg.norm(x_new - x, ord=np.inf) < tol:
            return x_new
        x = x_new

    return x

A = np.random.randint(1, 10, (5, 5))
b = np.random.randint(1, 10, 5)

x_jacobi = jacobi(A, b)
x_solve = np.linalg.solve(A, b)
x_inv = np.dot(np.linalg.inv(A), b)

error_solve = np.linalg.norm(x_jacobi - x_solve)
error_inv = np.linalg.norm(x_jacobi - x_inv)

print("Solución por Jacobi:", x_jacobi)
print("Solución por solve:", x_solve)
print("Solución por inversa:", x_inv)
print("Error respecto a solve:", error_solve)
print("Error respecto a inversa:", error_inv)


Solución por Jacobi: [-1.25481032e+72 -4.76015573e+71 -7.41719604e+71 -5.92351409e+71
 -1.43383935e+72]
Solución por solve: [-0.421875  1.3125   -0.421875 -0.171875  0.484375]
Solución por inversa: [-0.421875  1.3125   -0.421875 -0.171875  0.484375]
Error respecto a solve: 2.1812985177850927e+72
Error respecto a inversa: 2.1812985177850927e+72


#6

Verifique que cualquier matriz hermitiana de 2 × 2 $ L $ puede escribirse como una suma de cuatro términos:

$$ L = a\sigma_x + b\sigma_y + c\sigma_z + dI $$

donde $ a $, $ b $, $ c $ y $ d $ son números reales.

Las cuatro matrices de Pauli son:

$$ \sigma_x = \begin{pmatrix} 0 & 1 \\ 1 & 0 \end{pmatrix}, \quad \sigma_y = \begin{pmatrix} 0 & -i \\ i & 0 \end{pmatrix}, \quad \sigma_z = \begin{pmatrix} 1 & 0 \\ 0 & -1 \end{pmatrix}, \quad I = \begin{pmatrix} 1 & 0 \\ 0 & 1 \end{pmatrix} $$




In [8]:
sigma_x = np.array([[0, 1], [1, 0]])
sigma_y = np.array([[0, -1j], [1j, 0]])
sigma_z = np.array([[1, 0], [0, -1]])
I = np.array([[1, 0], [0, 1]])

a, b, c, d = np.random.randn(4)

L = a * sigma_x + b * sigma_y + c * sigma_z + d * I

es_hermitiana = np.allclose(L, L.conj().T)

print("Matriz L:\n", L)
print("¿Es hermitiana?", es_hermitiana)

Matriz L:
 [[ 1.6338985 +0.j        -1.3491518 +0.1198744j]
 [-1.3491518 -0.1198744j -0.21611074+0.j       ]]
¿Es hermitiana? True
