In [ ]:
import numpy as np
import sympy as sp
import scipy as sy

In [ ]:
A = np.matrix([[2,1, -1, 5],
        [4,1, 1, 1],
        [6, 2, 1,4]])

A


matrix([[ 2,  1, -1,  5],
        [ 4,  1,  1,  1],
        [ 6,  2,  1,  4]])

In [ ]:
# funcion que intercambia filas
def intercambio(A,i,j):
  B = A.copy()
  B[i] = A[j]
  B[j] = A[i]
  return B


In [ ]:
# Funcion de la multiplicacion por esclar
def mul_escalar(A,i,x):
  B = A.copy()
  B[i] = x*A[i]
  return B


In [ ]:
# Funcion de suma y resta entre filas
def suma_resta(A,i,j,x):
  B = A.copy()
  B[j] = x*A[i] + A[j]
  return B


In [ ]:
C = suma_resta(A,0,1,-2)
C

matrix([[ 2,  1, -1,  5],
        [ 0, -1,  3, -9],
        [ 6,  2,  1,  4]])

In [ ]:
# i es la fila que le voy a sumar o restar a j
# j es la fila que voy a modificar
# x escalar que me defina si se suma o se resta
C = suma_resta(C,0,2,-3)
C

matrix([[  2,   1,  -1,   5],
        [  0,  -1,   3,  -9],
        [  0,  -1,   4, -11]])

In [ ]:
C = mul_escalar(C,1,-1)
C

matrix([[  2,   1,  -1,   5],
        [  0,   1,  -3,   9],
        [  0,  -1,   4, -11]])

In [ ]:
C = suma_resta(C,1,2,1)
C

matrix([[ 2,  1, -1,  5],
        [ 0,  1, -3,  9],
        [ 0,  0,  1, -2]])

In [ ]:
C = suma_resta(C,2,1,3)
C=C.astype(float)
C

matrix([[ 2.,  1., -1.,  5.],
        [ 0.,  1.,  0.,  3.],
        [ 0.,  0.,  1., -2.]])

In [ ]:
C = mul_escalar(C,0,1/2).astype(float)
C

matrix([[ 1. ,  0.5, -0.5,  2.5],
        [ 0. ,  1. ,  0. ,  3. ],
        [ 0. ,  0. ,  1. , -2. ]])

In [ ]:
C = suma_resta(C,1,0,-0.5)
C

matrix([[ 1. ,  0. , -0.5,  1. ],
        [ 0. ,  1. ,  0. ,  3. ],
        [ 0. ,  0. ,  1. , -2. ]])

In [ ]:
C = suma_resta(C,2,0,0.5)
C

matrix([[ 1. ,  0. ,  0.5, -1. ],
        [ 0. ,  1. ,  0. ,  3. ],
        [ 0. ,  0. ,  1. , -2. ]])

In [ ]:
n = np.shape(A)[0]
n

3

In [ ]:
A[2,0]

6