In [3]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as al
import random
from sympy import Matrix, symbols, init_printing
import sympy as sp

# Actividad 08: Algebra Lineal y Matrices

---
### Profesor: Juan Marcos Marín
### Nombre: Juan Josè Usuga Giraldo 1020482080
*Métodos computacionales 2024-II*

---

#1

Escriba una función que calcule el producto escalar y vectorial para dos vectores, compare sus resultados con `np.dot` y `np.cross`.

In [16]:
def producto_punto(vector1, vector2):
  tamaño = len(vector1)  # Asumiendo que ambos vectores tienen el mismo tamaño
  producto_punto = 0
  for i in range(tamaño):
    producto_punto += vector1[i] * vector2[i]
  return producto_punto

In [17]:
def producto_punto(vector1, vector2):
  tamaño = len(vector1)  # Asumiendo que ambos vectores tienen el mismo tamaño
  producto_punto = 0
  for i in range(tamaño):
    producto_punto += vector1[i] * vector2[i]
  return producto_punto

# Ejemplo de uso
vector1 = np.array([17, 2, 3])
vector2 = np.array([4, 5, 6])

# Calcular y mostrar el producto punto
resultado = producto_punto(vector1, vector2)
print(f"Producto punto: {resultado}")

Producto punto: 96


In [18]:
vector1 = np.array([17, 2, 3])
vector2 = np.array([4, 5, 6])

# Calcular y mostrar el producto punto usando la función y np.dot
resultado_funcion = producto_punto(vector1, vector2)
resultado_npdot = np.dot(vector1, vector2)

print(f"Producto punto (función): {resultado_funcion}")
print(f"Producto punto (np.dot): {resultado_npdot}")

Producto punto (función): 96
Producto punto (np.dot): 96


In [19]:
def producto_vectorial(vector1, vector2):
  # Verificar si los vectores tienen 3 dimensiones
  if len(vector1) != 3 or len(vector2) != 3:
    raise ValueError("Los vectores deben tener 3 dimensiones.")

  # Calcular las componentes del producto vectorial
  x = vector1[1] * vector2[2] - vector1[2] * vector2[1]
  y = vector1[2] * vector2[0] - vector1[0] * vector2[2]
  z = vector1[0] * vector2[1] - vector1[1] * vector2[0]

  # Devolver el producto vectorial como un array de NumPy
  return np.array([x, y, z])

# Ejemplo de uso
vector1 = np.array([1, 2, 3])
vector2 = np.array([4, 5, 6])

# Calcular y mostrar el producto vectorial
resultado = producto_vectorial(vector1, vector2)
print(f"Producto vectorial: {resultado}")

Producto vectorial: [-3  6 -3]


In [14]:
vector1 = np.array([1, 2, 3])
vector2 = np.array([4, 5, 6])

# Calcular y mostrar el producto vectorial usando la función y np.cross
resultado_funcion = producto_vectorial(vector1, vector2)
resultado_npcross = np.cross(vector1, vector2)

print(f"Producto vectorial (función): {resultado_funcion}")
print(f"Producto vectorial (np.cross): {resultado_npcross}")

Producto vectorial (función): [-3  6 -3]
Producto vectorial (np.cross): [-3  6 -3]


#2

Crear una función llamada `mulmat()` donde a partir de dos matrices $A$ y $B$ encuentre su multplicación. También realiza una función que calcule la transpuesta y otra el determinante de una matriz $3\times 3$. Compare sus resultado con `@`, `np.dot`, `transpose` y `la.det`.

In [24]:
# Matrices de prueba
A = np.array([
    [1, 2, 3],
    [4, 47, 6],
    [5, 2, 6]
], dtype = float)

B = np.array([
    [7, 8, 9],
    [10, 11, 12],
    [13, 14, 15]
],dtype = float)

In [22]:
def mulmat(A,B):
  C = np.zeros((len(A), len(B[0])))
  m_a, n_a = len(A), len(A[0])
  m_b, n_b = len(B), len(B[0])
  if m_a != n_b:
    raise ValueError("Las dimensiones de las matrices no son compatibles para la multiplicación.")

  C += [[0 for _ in range(n_b)] for _ in range(m_a)]
  for i in range(m_a):
    for j in range(n_b):
      for k in range(n_a):
        C[i][j] += A[i][k] * B[k][j]
  return C

In [23]:
print('Producto por mi función:\n', mulmat(A,B), '\n\nProducto np.dot:\n', np.dot(A,B))
print('\n\n¿Los valores son equivalentes?')

if np.array_equal(mulmat(A,B), np.dot(A,B)):
  print("Verdadero")
else:
  print("Falso")

Producto por mi función:
 [[ 66.  72.  78.]
 [156. 171. 186.]
 [133. 146. 159.]] 

Producto np.dot:
 [[ 66.  72.  78.]
 [156. 171. 186.]
 [133. 146. 159.]]


¿Los valores son equivalentes?
Verdadero


In [26]:
def transpuesta(A):
  C = np.zeros((len(A[0]), len(A)))
  for i in range(len(A)):
    for j in range(len(A[0])):
      C[j][i] = A[i][j]
  return C
print('A:\n', A, '\n\nA Transpuesta:\n', transpuesta(A))

A:
 [[ 1.  2.  3.]
 [ 4. 47.  6.]
 [ 5.  2.  6.]] 

A Transpuesta:
 [[ 1.  4.  5.]
 [ 2. 47.  2.]
 [ 3.  6.  6.]]


In [27]:
print('Transpuesta por mi función:\n', transpuesta(A), '\n\nTranspuesta por np.transpose:\n', np.transpose(A))
print('\n\n¿Las matrices son equivalentes?')

if np.array_equal(transpuesta(A), np.transpose(A)):
  print("Verdadero")
else:
  print("Falso")

Transpuesta por mi función:
 [[ 1.  4.  5.]
 [ 2. 47.  2.]
 [ 3.  6.  6.]] 

Transpuesta por np.transpose:
 [[ 1.  4.  5.]
 [ 2. 47.  2.]
 [ 3.  6.  6.]]


¿Las matrices son equivalentes?
Verdadero


In [28]:
def det(A):
  if len(A) == 3: # Aplica método de Sarrus
    suma = A[0][0]*A[1][1]*A[2][2] + A[0][1]*A[1][2]*A[2][0] + A[0][2]*A[1][0]*A[2][1]
    resta = A[0][2]*A[1][1]*A[2][0] + A[0][1]*A[1][0]*A[2][2] + A[0][0]*A[1][2]*A[2][1]
    return suma - resta

In [29]:
al.det(A),  det(A)
print('Determinante por mi función:', det(A), '\nDeterminante por np.linalg.det:', np.linalg.det(A), '\n\n¿Los valores son equivalentes?')
if np.array_equal(det(A), np.linalg.det(A)):
  print("Verdadero")
else:
  print("Falso")

Determinante por mi función: -399.0 
Determinante por np.linalg.det: -399.0000000000001 

¿Los valores son equivalentes?
Falso


#3
Escriba tres matrices aleatorias $A$, $B$ y $C$ de $3\times 3$, y demuestre las siguientes relaciones

- $ \mathbf{A}\mathbf{B} \neq \mathbf{B}\mathbf{A} $, en general.
- $ (\mathbf{A}\mathbf{B})\mathbf{C} = \mathbf{A}(\mathbf{B}\mathbf{C}) $.
- $ \mathbf{A}(\mathbf{B} + \mathbf{C}) = \mathbf{A}\mathbf{B} + \mathbf{A}\mathbf{C} $.
- $ (\mathbf{A} + \mathbf{B})\mathbf{C} = \mathbf{A}\mathbf{C} + \mathbf{B}\mathbf{C} $.
- $ (\mathbf{A}\mathbf{B})^\top = \mathbf{B}^\top \mathbf{A}^\top $.
- $ \det(\mathbf{A}\mathbf{B}) = \det(\mathbf{A}) \det(\mathbf{B}) $.
- $ (\mathbf{A}^\top)^\top = \mathbf{A} $.
- $ (c\mathbf{A})^\top = c\mathbf{A}^\top $.
- $ (\mathbf{A} + \mathbf{B})^\top = \mathbf{A}^\top + \mathbf{B}^\top $.



In [30]:
import numpy as np

# Crear tres matrices aleatorias de 3x3
A = np.random.rand(3, 3)
B = np.random.rand(3, 3)
C = np.random.rand(3, 3)



In [31]:
# Demostrar AB ≠ BA
print("AB ≠ BA, en general:")
print(np.array_equal(A @ B, B @ A))  # False en general

AB ≠ BA, en general:
False


In [32]:
# Demostrar (AB)C = A(BC)
print("(AB)C = A(BC):")
AB = A @ B
BC = B @ C

(AB)C = A(BC):


In [33]:
# Check if (AB)C = A(BC) with tolerance
result = np.allclose((A @ B) @ C, A @ (B @ C), atol=1e-8)

# Print the result
print(f"(AB)C = A(BC):\n{result}")  # Output: True (most likely)

(AB)C = A(BC):
True


In [34]:
# Demostrar A(B + C) = AB + AC
print("A(B + C) = AB + AC:")
print(np.allclose(A @ (B + C), A @ B + A @ C))  # True

A(B + C) = AB + AC:
True


In [35]:
# Demostrar (AB)ᵀ = BᵀAᵀ
print("(AB)ᵀ = BᵀAᵀ:")
print(np.allclose((A @ B).T, B.T @ A.T))  # True

(AB)ᵀ = BᵀAᵀ:
True


In [36]:
print("det(AB) = det(A)det(B):")
print(np.isclose(np.linalg.det(A @ B), np.linalg.det(A) * np.linalg.det(B)))  # True

det(AB) = det(A)det(B):
True


In [37]:
print("(Aᵀ)ᵀ = A:")
print(np.array_equal(A.T.T, A))  # True

(Aᵀ)ᵀ = A:
True


In [38]:
print("(cA)ᵀ = cAᵀ:")
c=2 #en particular, es cualquier constante
print(np.array_equal((c * A).T, c * A.T))  # True

(cA)ᵀ = cAᵀ:
True


In [39]:
print("(A + B)ᵀ = Aᵀ + Bᵀ:")
print(np.array_equal((A + B).T, A.T + B.T))  # True

(A + B)ᵀ = Aᵀ + Bᵀ:
True


#4

El **Teorema de Laplace** es un método para calcular el determinante de una matriz cuadrada, particularmente útil para matrices de orden mayor a 2. Este teorema se basa en la expansión del determinante por los elementos de una fila o una columna cualquiera.



$$
\det(A) = \sum_{j=1}^n (-1)^{1+j} a_{1j} M_{1j}
$$

donde:
- $a_{1j}$ es el elemento de la primera fila y columna $j$.
- $M_{1j}$ es el menor asociado al elemento $a_{1j}$, es decir, el determinante de la submatriz de $3 \times 3$ que se obtiene al eliminar la fila 1 y la columna $j$.
- $(-1)^{1+j}$ es el signo correspondiente al cofactor del elemento $a_{1j}$.

Podemos realizar una función recursiva para el cálculo del determinante, sabiendo que el valor del determinante de una matriz de orden uno es el único elemento de esa matriz, y el de una matriz de orden superior a uno es la suma de cada uno de los elementos de una fila o columna por los Adjuntos a ese elemento, como en la función recursiva se emplea la misma función definida el cálculo lo haremos por Menor complementario, un ejemplo desarrollado por la primera fila sería:

$$
   \det (A_{j,j}) =
   \left \{
   \begin{array}{llcl}
      si & j = 1 & \to & a_{1,1} \\
                                 \\
      si & j > 1 & \to & \displaystyle \sum_{k=1}^j \; (-1)^{(1+k)} \cdot a_{1,k} \cdot \det( \alpha_{1,k})
   \end{array}
   \right .
$$

Realice una función que encuentre el determinante de una matriz usando la recursividad aqui planteada, explique explicitamente su código



    Caso base:
        if n == 1:: Si la matriz es de tamaño 1x1 (un solo elemento), el determinante es simplemente ese elemento (matriz[0, 0]).

    Paso recursivo:
        determinante = 0: Inicializa el determinante a 0.
        for k in range(n):: Itera a través de cada elemento de la primera fila de la matriz (índice k).
            submatriz = np.delete(np.delete(matriz, 0, axis=0), k, axis=1): Crea una submatriz eliminando la primera fila y la k-ésima columna de la matriz original.
            determinante += (-1)**(1 + k) * matriz[0, k] * determinante_recursivo(submatriz): Calcula el determinante de la submatriz recursivamente y lo agrega al determinante general. Este paso aplica la fórmula de expansión de Laplace, donde (-1)**(1 + k) determina el signo (cofactor) y matriz[0, k] es el elemento que se está considerando.

    Retorno:
        return determinante: Devuelve el determinante calculado.

En esencia, la función descompone el cálculo del determinante de una matriz grande en el cálculo de determinantes de submatrices más pequeñas, hasta que llega al caso base de una matriz 1x1.

In [42]:
def determinante_recursivo(matriz):
  n = len(matriz)
  if n == 1:
    return matriz[0, 0]
  determinante = 0
  for k in range(n):
    submatriz = np.delete(np.delete(matriz, 0, axis=0), k, axis=1)
    determinante += (-1)**(1 + k) * matriz[0, k] * determinante_recursivo(submatriz)
  return determinante

# Ejemplo de uso
matriz = np.array([[1, 5, 3], [4, 5, 6], [7, 8, 9]])
determinante = determinante_recursivo(matriz)
print("Determinante:", determinante)
dett=np.linalg.det(matriz)
print('Determinante por np.linalg.det:', dett)

Determinante: 18
Determinante por np.linalg.det: 18.000000000000014


#5

El método de Jacobi reescribe el sistema $ Ax = b $ descomponiendo la matriz $ A $ como:

$$
A = D + L + U,
$$

donde:
- $ D $: Matriz diagonal de $ A $,
- $ L $: Matriz triangular inferior sin la diagonal,
- $ U $: Matriz triangular superior sin la diagonal.

El sistema se reorganiza como:

$$
x = D^{-1}(b - (L + U)x).
$$

Esto se implementa iterativamente como:

$$
x_i^{(k+1)} = \frac{1}{a_{ii}} \left(b_i - \sum_{j \neq i} a_{ij} x_j^{(k)}\right),
$$

donde $ a_{ii} $ son los elementos diagonales de $ A $.

* Escriba una función explicita que realice de manera iterativa este método con una tol = 1e-7 y un máximo de 100 iteraciones. Defina una documentación clara que explique los métodos usados, lasa entradas y salidas.

* Para una matriz aleatoria 5$\times$ 5, encuentre la solución usando su función y determine el error con respecto a `solve` y el método de inversa de matriz.

In [43]:
import numpy as np

def jacobi_iterativo(A, b, tol=1e-7, max_iter=100):
    n = A.shape[0]
    x = np.zeros(n)
    error = 1
    num_iter = 0

    while error > tol and num_iter < max_iter:
        x_old = x.copy()
        for i in range(n):
            x[i] = (b[i] - np.dot(A[i, :i], x_old[:i]) - np.dot(A[i, i + 1:], x_old[i + 1:])) / A[i, i]

        error = np.linalg.norm(x - x_old) / np.linalg.norm(x)
        num_iter += 1

    if num_iter == max_iter and error > tol:
        print(f"Advertencia: No se alcanzó la convergencia después de {max_iter} iteraciones.")

    return x, error, num_iter

# Ejemplo de uso
A = np.array([[4, -1, 0, 0],
              [-1, 4, -1, 0],
              [0, -1, 4, -1],
              [0, 0, -1, 3]], dtype=float)

b = np.array([15, 10, 10, 10], dtype=float)

x, error, iteraciones = jacobi_iterativo(A, b)

print(f"Solución: {x}")
print(f"Error relativo: {error}")
print(f"Número de iteraciones: {iteraciones}")


Solución: [4.99999989 4.99999982 4.9999998  4.99999984]
Error relativo: 4.5566232573914235e-08
Número de iteraciones: 20


In [45]:
def jacobi_iterativo(A, b, tol=1e-7, max_iter=100):
    n = A.shape[0]
    x = np.zeros(n)
    error = 1
    num_iter = 0

    while error > tol and num_iter < max_iter:
        x_old = x.copy()
        for i in range(n):
            x[i] = (b[i] - np.dot(A[i, :i], x_old[:i]) - np.dot(A[i, i + 1:], x_old[i + 1:])) / A[i, i]

        error = np.linalg.norm(x - x_old) / np.linalg.norm(x)
        num_iter += 1

    if num_iter == max_iter and error > tol:
        print(f"Advertencia: No se alcanzó la convergencia después de {max_iter} iteraciones.")

    return x, error, num_iter

# Generar una matriz aleatoria 5x5 y un vector b
np.random.seed(0)  # Para obtener resultados reproducibles
A = np.random.rand(5, 5)
b = np.random.rand(5)

# Resolver usando el método de Jacobi
x_jacobi, error_jacobi, iteraciones = jacobi_iterativo(A, b)

# Resolver usando np.linalg.solve (método directo)
x_solve = np.linalg.solve(A, b)

# Resolver usando el método de la inversa de la matriz
x_inv = np.linalg.inv(A).dot(b)

# Calcular los errores
error_jacobi_solve = np.linalg.norm(x_jacobi - x_solve)
error_jacobi_inv = np.linalg.norm(x_jacobi - x_inv)

# Imprimir resultados
print("Solución usando Jacobi:", x_jacobi)
print("Solución usando np.linalg.solve:", x_solve)
print("Solución usando la inversa de la matriz:", x_inv)
print(f"Error de Jacobi respecto a solve: {error_jacobi_solve}")
print(f"Error de Jacobi respecto a la inversa de la matriz: {error_jacobi_inv}")
print(f"Iteraciones en Jacobi: {iteraciones}")


Advertencia: No se alcanzó la convergencia después de 100 iteraciones.
Solución usando Jacobi: [-3.04322736e+79 -3.94155137e+79 -2.13580918e+79 -2.55567732e+79
 -1.21036858e+80]
Solución usando np.linalg.solve: [-7.44095801  5.42647186 -4.16168606  6.91406389 -0.98235854]
Solución usando la inversa de la matriz: [-7.44095801  5.42647186 -4.16168606  6.91406389 -0.98235854]
Error de Jacobi respecto a solve: 1.3505163393212658e+80
Error de Jacobi respecto a la inversa de la matriz: 1.3505163393212658e+80
Iteraciones en Jacobi: 100


#6

Verifique que cualquier matriz hermitiana de 2 × 2 $ L $ puede escribirse como una suma de cuatro términos:

$$ L = a\sigma_x + b\sigma_y + c\sigma_z + dI $$

donde $ a $, $ b $, $ c $ y $ d $ son números reales.

Las cuatro matrices de Pauli son:

$$ \sigma_x = \begin{pmatrix} 0 & 1 \\ 1 & 0 \end{pmatrix}, \quad \sigma_y = \begin{pmatrix} 0 & -i \\ i & 0 \end{pmatrix}, \quad \sigma_z = \begin{pmatrix} 1 & 0 \\ 0 & -1 \end{pmatrix}, \quad I = \begin{pmatrix} 1 & 0 \\ 0 & 1 \end{pmatrix} $$




In [46]:
# Matrices de Pauli
Px, Py, Pz, I = np.array([[0,1], [1,0]]) , (np.array([[0,-1j], [1j,0]])), np.array([[1,0], [0,-1]]) , np.array([[1,0], [0,1]])

In [47]:
a, b, c, d = sp.symbols('a b c d', real = True)
incognitas = [a, b, c, d]

def descomponer_matriz_hermitiana(L):
  """
  Descompone una matriz hermitiana L en la forma:
  L = a * sigma_x + b * sigma_y + c * sigma_z + d * I
  donde a, b, c, d son los coeficientes reales y retorna los valores
  de las constantes a, b, c y d.
  """
  # Comprobar que L es hermitiana
  if not np.allclose(L, L.conj().T):
      raise ValueError("La matriz no es hermitiana.")

  d = np.trace(L) / 2
  c = (L[0, 0] - L[1, 1]) / 2
  a = np.real(L[0, 1])
  b = -np.imag(L[0, 1])

  return a, b, c, d

In [48]:
hermitiana_de_prueba = np.array([[-1, 3j +1], [-3j +1, 5]]) # 2x2
a, b, c, d = descomponer_matriz_hermitiana(hermitiana_de_prueba)
print('Coeficientes obtenidos:\n\na:', a, '\nb:', b, '\nc:', c, '\nd:', d) # Note que son reales todos porque las partes imaginarias son 0

Coeficientes obtenidos:

a: 1.0 
b: -3.0 
c: (-3+0j) 
d: (2+0j)


In [49]:
# Reconstrucción de la matriz
reconstruida = a * Px + b * Py + c * Pz + d * I
print('Matriz reconstruida:\n\n', reconstruida)

Matriz reconstruida:

 [[-1.+0.j  1.+3.j]
 [ 1.-3.j  5.+0.j]]


In [50]:
print(hermitiana_de_prueba)

[[-1.+0.j  1.+3.j]
 [ 1.-3.j  5.+0.j]]
